TRANSLATION "BRAZILIAN"
BEGIN
    "Translator" = "Mauricio Montel"
    "Translator's email" = "maumontel@hotmail.com"

    "long_notifySettingString" = ""\
    "* Registros\n"\
    "Selecione 'todos' caso você queira notificar "\
    "todos os eventos nesta categoria. "\
    "Selecione 'selecionado'para notificar somente o registro "\
    "atual.\n\n"\
    "* Existente\n"\
    "Selecionar 'manter' se deseja manter as notificações existentes. "\
    "Selecione 'alterar' caso você queira que as notificações sejam alteradas.\n\n"\
    "* Alarme\n"\
    "Para colocar um horário na notificação. Indique "\
	"o número de dias de antecipação que você quer ser notificado.\n\n"\
    "* Hora\n"\
	"Horário do evento\n\n"\
    "* Repetir por\n"\
    "Estabelece o intervalo da notificação. "\
    "Utiliza -1 para repetir sempre os eventos solares, e "\
    "repetir por 5 anos os eventos lunares.\n"

	"long_notifySettingMoreString" = ""\
	"Para o numero do ícone AN, consulte o manual do Action Names . DateBk3Icon é "\
	"lido a partir do MemoPad. Se você não tem um registro DateBk3 Icon no MemoPad, "\
	"nada será mostrado.\n"

    "long_customErrorString" = ""\
    "'Birthday' é o custom field padrão."\
    "Para mudar o nome do custom field, "\
    "selecione 'Preferências'.\n\n"\
    "IMPORTANTE: Você precisa lançar seu Addressbook e selecionar 'Options/"\
    "Rename Custom Fields' para renomear o custom field para 'Birthday' "\
    "ou o que você ajuste como nome do custom field nas Preferências do "\
    "HappyDays.\n"

    "long_aboutString" = ""\
    "'HappyDays' ajudará você a lembrar os aniversários e comemorações "\
    "de seus amigos e familiares, bem como outros eventos."\
    "\n\nUse um dos custom fields da aplicação Address Book "\
    "e renomeie para 'Birthday'."\
    "\n\nExemplos:\n"\
    " Last Name: Jeong\n"\
    " First name: JaeMok\n"\
    " ...\n"\
    " Birthday: -)12/4/70\n\n"\
    "Formatos:\n"\
    " [-)|#)]Data\n"\
    " -) significa calendário lunar\n"\
    " #) significa calendário lunar bissexto\n\n"\
    "O formato da data é automaticamente lido a partir das preferências do sistema. "\
    "Você pode omitir o campo ano. Ao escrever um ano menor que 100 assume-se que seja "\
    "um ano do séc. 20,se você não estiver certo do formato do ano, "\
    "escreva-o no formato AAAA (ex. 1970).\n\n"\
    "Para entradas múltiplas, consulte o manual.\n\n" \
	"Nome1 & nome2 mostrados na lista do HappyDays List são determinados pelo "\
	"'AddressBook/Preferences/List by'. Caso você troque esta preferência, "\
	"você obtém diferentes visualizações.\n\n"\
	"O formato da data é determinado por System/Prefs/Formats/Date Format.\n\n"\
	"Escrevendo uma letra ou numero na área do graffiti, a coluna similar será "\
	"realçada. Por exemplo, caso você escreva um  'a' no graffiti, o "\
	"primeiro registro começado  com  'a' ou 'A' será realçado. "\
	"Escrevendo '1' no graffiti, o próximo registro depois de "\
	"Janeiro será realçado.\n"

    "long_cleanupAlertString" = ""\
    "As entradas de notificação serão consideradas do HappyDays se elas contiverem "\
	"{HappyDays ID} nos seus campos de MEMO. "\ 	
    "Se você usa este formato  nas suas entradas "\
    "este registro também poderá ser removido pela Limpeza.\n"

    "long_prefFormString" = ""\
	"* Formato de data alternativo...\n"\
	"Controla a interpretação do custom field Birthday. "\
	"Se for omitido, será o mesmo que a preferência de data do sistema.\n\n"\
	"* Buscar em Notes\n"\
	"Para ler o campo Notes do Address Book, marque esta opção.\n\n"\
    "* Preferir Data Lunar\n"\
    "Se selecionado, uma linha pontilhada será desenhada junto a data lunar .\n\n"\
	"* Formato da Notificação\n"\
	"Descrição do formato da notificação\n\n"\
    "* Custom field\n"\
    "O nome do custom field usado no Address Book para entrada de dados\n\n"\
    "* HappyDays ID\n"\
    "Usado para Notificar e Limpeza\n"

    "long_removeConfirmString" = ""\
    "Você tem certeza que quer remover "\
    "todas as notificações do HappyDays?"

    "long_sl2lnString" = ""\
        "-) significa mês lunar normal\n"\
        "#) significa mês lunar bissexto"

    "long_cantFindAddrString" = ""\
    "Não foi possível encontra um custom field: '%s'\n"\
    "Por favor renomeie um custom field no seu address book."

    "Select Time" = "Selecionar Horário"
    "No Time" = "Sem Horário"
    "Invalid input date" = "Data Inválida"
    "Export to Memo Pad is completed." = "Exportação para o Memo Pad completa."

    "SUN"   = "DOM"
    "MON"   = "SEG"
    "TUE"   = "TER"
    "WED"   = "QUA"
    "THU"   = "QUI"
    "FRI"   = "SEX"
    "SAT"   = "SAB"

    "Not enough memory" = "Memória insuficiente"
    "%d notify entry is created.\n" = "%d Notificações criadas.\n" 
    "%d existing entry " = "%d notificações "
    "is kept untouched." = "sem alterar."
    "is modified." = "alteradas."

    "Could not write prefs." = ""\
		"Não foi possível gravar prefs."
    "Collecting Information..." = "Coletando informações..."

    "HappyDays List" = "Lista do HappyDays"
    "Look Up:" = "Procurar:"

    "HappyDays View" = "Visual. do Happydays"
    "Done"  = "Feito"
    "DB" = "DB" 
    "TD" = "TD"
    "Goto" = "Ir para"

    "Utilities" = "Utilitários"
    "Date Book Notify" = "Notificar no Date Book"
    "Cleanup Date Book"  = "Limpar Date Book"
    "To Do Notify" = "Notificar no To Do"
    "Cleanup To Do"  = "Limpar To Do"
    "Export to Memo Pad" = "Exportar para Memo Pad"
    "Solar to Lunar" = "Solar para Lunar"
    "Lunar to Solar" = "Lunar para Solar"
    "Options" = "Opções"
    "Preferences" = "Preferências"
    "About HappyDays" = "Sobre HappyDays"

    "Edit" = "Editar"
    "Undo" = "Desfazer"
    "Cut" = "Cortar"
    "Copy" = "Copiar" 
    "Paste" = "Colar" 
    "Select All" = "Selecionar todos" 
    "Keyboard" = "Teclado" 
    "Graffiti" = "Graffiti"

    "HappyDays Preferences" = "Preferências do HappyDays"
    "Custom field:" = "Custom field:"
    "HappyDays ID:" = "HappyDays ID:"
    "Emphasize Lunar Date" = "Preferir a data Lunar"

    "OK" = "OK"
    "Cancel" = "Cancelar"

    "Solar to Lunar Convert" = "Conversão de Solar para Lunar"
    "Enter Solar date:" = "Entre a data Solar:"
    "Year must be in 1881-2043" = "O ano deve ser entre 1881-2043"
    "Result Lunar date:" = "Data Lunar resultante:"

    "Convert" = "Converter"

    "Lunar to Solar Convert" = "Conversão de Lunar para Solar"
    "Enter Lunar date:" = "Entre a data Lunar:"
    "Leap" = "Bissexto"
    "Result Solar date:" = "Data Solar resultante:"

    "Records:" = "Registros:"
      "all" = "todos"
      "selected" = "selecionados" 
    "Existing:" = "Existentes:"
      "keep" = "manter"
      "modify" = "modificar"
    "Priority:" = "Prioridade:"
    "Category:" = "Categoria:"
    "Private:" = "Confidencial:"
    "Alarm:" = "Alarme:"
    "Time:" = "Hora:"
    "More..." = "Mais..."

    "Repeat for:" = "Repetir por:"
    "years" = "anos"

    "HappyDays says" = "HappyDays diz"

    "HappyDays Export" = "Exportar HappyDays"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
    	"Você gostaria de exportar a lista do HappyDays para o Memo Pad?" 

    "Custom Field Error" = "Erro no Custom Field"
    "Help" = "Ajuda" 


    "HappyDays Cleanup" = "Limpar HappyDays" 

    "Notify warning" = "Aviso" 
    "^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
  	"^1: Você tem certeza que gostaria de criar notificações para ^2 HappyDays registros?" 
      

    "Invalid event format" = "Formato de evento inválido" 

    "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
    "O registro de endereço ^1\n contém um evento inválido. Como você gostaria de resolver isto?" 

    "Ignore" = "Ignorar" 
    "Ignore all" = "Ignorar todos" 

    "Cleanup Done" = "Limpeza concluída" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    	"^1: ^2 Notificações do HappyDays removidas." 

    "Birthday" = "Aniversário" 
    "All" = "Todos" 
    "HappyDays Export List" = "Exportar Lista do HappyDays" 
    "(not exist in this year)" = "(não existe neste ano)" 
    "Please run Date Book once first." = "Por favor execute o Date Book primeiro."  
    
    "Instead of system date format" = "Ao invés do form. de data do sistema"  
    "Use" = "Use"  
    "M/D/Y" = "M/D/A"  
    "D/M/Y" = "D/M/A"  
    "D.M.Y" = "D.M.A"  
    "D-M-Y" = "D-M-A"  
    "Y/M/D" = "A/M/D"  
    "Y.M.D" = "A.M.D"  
    "Y-M-D" = "A-M-D"  

    "Date Book Icon" = "Ícones do Date Book"  
      "Icon Support" = "Suporte a Ícones"  
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "Número do ícone AN:"  
      "DateBk3 Icon:" = "Ícone do DateBk3:"  

    "Days" = "Dias"  
    "Date Book" = "Date Book"  
    "To Do" = "To Do"  
    "Scan note field" = "Procurar em NOTE"  
    "%d day(s) left" = "%d dias(s) para o evento"  
    "%d day(s) passed" = "%d dia(s) passados"  
    "Notify Format:" = "Formato da Notificação:"  
    "[Last, First] E(1) Year" = "[Sobrenome, Nome] E(1) Ano"  
    "[First Last] E(1) Year" = "[Nome Sobrenome] E(1) Ano"  
    "Event - Last, First Year" = "Evento - Sobrenome, Nome Ano"  
    "Event - First Last Year" = "Evento - Nome Sobrenome Ano"  
    "First Last Year" = "Nome Sobrenome Ano"  
    
    "Processing" = "Processando"  
    "Processed : " = "Processado : " 

	"Name" = "Nome"
	"Date" = "Data"
	"Age" = "Idade"

END


