TRANSLATION "CATALAN"
BEGIN
    "Translator" = "Paco Rivière"
    "Translator's email" = "paco@famosos.com"

    "long_notifySettingString" = ""\
    "* Registres\n"\
      "Trii\"Tots\" per a crear notificacions de "\
      "tots els registres en aquesta categoria. "\
      "Trii \"Marcat\" per a notificar només el registre "\
      "actual.\n\n"\
      "* Existent\n"\
      "Trii \"Deixar\" si no desitja canviar les notificacions actuals. "\
      "Trii \"Canviar\" per a modificar les notificacions.\n\n"\
      "* Alarma\n"\
      "Per a posar l'hora d'alarma en la notificació. Indiqui "\
      "el número de dies d'anticipació per a la notificació.\n\n"\
      "* Hora\n"\
      "Hora del registre.\n\n"\
      "* Repetir\n"\
      "Estableix l'interval de la notificació. "\
      "Utilitzi -1 per a repetir sempre en registres solars i "\
      "repetir per a 5 anys en registres lunars.\n\n"

	"long_notifySettingMoreString" = ""\
      "Per al número d'icone d'Action Names consulti el seu manual. "\
      "Les icones de DateBk3 es llegeixen del bloc de notes. "\
      "Si no existeix l'entrada de DateBk3 en el bloc de notes no es mostra informació.\n"

    "long_customErrorString" = ""\
    "'Naixement' és el nom personalitzat per omisió."\
    "Per a establir un camp personalitzat diferent"\
    " trii 'Preferències'.\n\n"\
    "IMPORTANT: Haurà de fer servir Adreçes i seleccionar 'Opcions/"\
    "Nom dels camps pers...' per a canviar un camp personalitzat a 'Naixement'"\
    " o allò que desitgi establir com a nom en les Preferències de "\
    "HappyDays.\n"

    "long_aboutString" = ""\
      "'HappyDays' l'ajudarà a recordar les dates claus i aniversaris "\
      "del seus amics i familiars.\n\n"\
      "Faci servir un dels camps personalitzats de l'Agenda i canvii el seu nom a 'Naixement'."\
      "\n\nExemples:\n"\
      " Cognoms: Guardiola\n"\
      " Nom: Josep\n"\
      " ...\n"\
      " Naixement: -)12/4/1970\n\n"\
      "Formats:\n"\
      " [-)|#)]Data\n"\
      " -) calendari lunar\n"\
      " #) calendari lunar de trespas\n\n"\
      "S'utilitza el format de data de les preferències del sistema. "\
      "No cal indicar l'any. Si escriu un any menor a 100 s'assumeix del segle XX. "\
      "Si no està segur del format de l'any, escrigui'l en la forma AAAA (com 1970).\n\n"\
      "Per a entrades múltiples consulti el manual.\n"

    "long_cleanupAlertString" = ""\
    "Les notificacions es consideren HappyDays si tenen "\
	"{Ident. HappyDays} en el camp Nota. "\ 	
    "Si fa servir aquest format en les seves pròpies entrades, "\
    "aquest registre pot ser eliminat per la Neteja.\n"

    "long_prefFormString" = ""\
	"* Format de data alternatiu\n"\
	"Controli l'interpretació del camp personalitzat de Naixement. "\
	"Si no s'indica, és el mateix que les preferències de data del sistema.\n\n"\
	"* Cercar en Notes\n"\
	"Trii aquesta opció per a cercar en el camp de notes.\n\n"\
      "* Preferir Calendari Lunar \n"\
      "Si es selecciona, la linea puntejada es dibuixa junt a la data lunar.\n\n"\
	"* Format de Notificació\n"\
	"La descripció del format usat per a la notificació.\n\n"\
      "* Camp pers:\n"\
      "El nom del camp personalitzat utilitzat per a les dades.\n\n"\
      "* Ident. HappyDays\n"\
      "Identificador utilitzat per a notificació i neteja.\n"

    "long_removeConfirmString" = ""\
    "Desitja eliminar totes les notificacions "\
    "de HappyDays?"

    "long_sl2lnString" = ""\
        "-) significa mes lunar normal\n"\
        "#) significa mes lunar de trespas"

    "long_cantFindAddrString" = ""\
    "No es possible trobar cap camp personalitzat: '%s'\n"\
    "Si us plau canvieu el nom d'un camp personalitzat en la vostra Llista d'Adreçes."

    "Select Time" = "Establir hora"
    "No Time" = "Sense hora"
    "Invalid input date" = "Data invàlida"
    "Export to Memo Pad is completed." = "Ha acabat l'exportació a Bloc de notes."

    "SUN"   = "DIU"
    "MON"   = "DIL"
    "TUE"   = "DIM"
    "WED"   = "DIC"
    "THU"   = "DIJ"
    "FRI"   = "DIV"
    "SAT"   = "DIS"

    "Not enough memory" = "Memòria Insuficient"
    "%d notify entry is created.\n" = "%d notificacions creades.\n"
    "%d existing entry " = "%d notificacions "
    "is kept untouched." = "sense modificar."
    "is modified." = "modificades."

    "Could not write prefs." = "No s'ha pogut desar preferències."
    "Collecting Information..." = "Reunint informació..."

    "HappyDays List" = "Llista HappyDays"
    "Look Up" = "Cercar"
    "Today" = "Avui"

    "HappyDays View" = "Detalls HappyDays"
    "Done"  = "Fet"
    "DB" = "Agenda"
    "TD" = "Tasques"
    "Goto" = "Ir a"

    "Utilities" = "Utilitats"
    "Date Book Notify" = "Notificar en Agenda"
    "Cleanup Date Book"  = "Netejar Agenda"
    "To Do Notify" = "Notificar en Tasques"
    "Cleanup To Do"  = "Netejar Tasques"
    "Export to Memo Pad" = "Exportar a Bloc de notes"
    "Solar to Lunar" = "Solar -> Lunar"
    "Lunar to Solar" = "Lunar -> Solar"

    "Options" = "Opcions"
    "Preferences" = "Preferències"
    "About HappyDays" = "Sobre HappyDays"

    "Edit" = "Edició"
    "Undo" = "Desfer"
    "Cut" = "Tallar"
    "Copy" = "Copiar"
    "Paste" = "Enganxar"
    "Select All" = "Selec tot"
    "Keyboard" = "Teclat"
    "Graffiti" = "Ajuda de Graffiti"

    "HappyDays Preferences" = "Preferències HappyDays"
    "Custom field:" = "Camp pers.:"
    "HappyDays ID:" = "Ident. HappyDays:"
    "Emphasize Lunar Date" = "Preferir Calendari Lunar"

    "OK" = "Fet"
    "Cancel" = "Cancelar"
    "Icon" = "Icone"

    "Solar to Lunar Convert" = "Solar -> Lunar"
    "Enter Solar date:" = "Indiqui la data Solar:"
    "Year must be in 1881-2043" = "L'any ha de ser entre 1881 i 2043"
    "Result Lunar date:" = "Data Lunar resultat:"

    "Convert" = "Convertir"

    "Lunar to Solar Convert" = "Lunar -> Solar."
    "Enter Lunar date:" = "Indiqui la data Lunar:"
    "Leap" = "De trespas"
    "Result Solar date:" = "Data Solar resultat:"

    "Records:" = "Registres:"
      "all" = "Tots"
      "selected" = "Marcat"
    "Existing:" = "Actual:"
      "keep" = "Deixar"
      "modify" = "Canviar"
    "Priority:" = "Prioritat:"
	"Category:" = "Categoria:"
    "Private:" = "Confidencial:"
    "Alarm:" = "Alarma:"
    "Time:" = "Hora:"
    "More..." = "Més..."

    "Repeat for:" = "Repetir:"
    "years" = "any(s)"

    "HappyDays says" = "HappyDays diu"

    "HappyDays Export" = "Exportar HappyDays"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
      "¿Desitja exportar la llista HappyDays al Bloc de notes?"

    "Custom Field Error" = "Error en camp personalitzat"
    "Help" = "Ajuda"


    "HappyDays Cleanup" = "Netejar HappyDays"

    "Notify warning" = "Avís"
    "^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
      "^1: Segur que desitja crear notificacions de HappyDays per a ^2 registres?"
      

    "Invalid event format" = "Format de registre invàlid."

    "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
      "El registre d'agenda de ^1\n contè un registre invàlid. Què vol fer?"

    "Ignore" = "Ignorar"
    "Ignore all" = "Ignorar tots"

    "Cleanup Done" = "Neteja acabada"

    "^1: ^2 HappyDays notify entries removed." = ""\
      "^1: ^2 notificacions de HappyDays eliminades."

    "(c) 1999-2000 JaeMok Jeong" = "(c) 1999-2000 JaeMok Jeong"
    "GPL free software" = "Programari gratuït GPL"
	"E-Mail & Web Page" = "E-Mail & Pàgina Web"

    "Birthday" = "Naixement"
    "All" = "Tots"
    "HappyDays Export List" = "Exportar Llista HappyDays"
    "(not exist in this year)" = "(no existeix en aquest any)"
    "Please run Date Book once first." = "Si us plau trii l'Agenda primer."
    
    "Instead of system date format" = "Format de data alternatiu"
    "Use" = "Usar"
    "M/D/Y" = "M/D/A"
    "D/M/Y" = "D/M/A"
    "D.M.Y" = "D.M.A"
    "D-M-Y" = "D-M-A"
    "Y/M/D" = "A/M/D"
    "Y.M.D" = "A.M.D"
    "Y-M-D" = "A-M-D"

    "Date Book Icon" = "Icone d'Agenda"  
      "Icon Support" = "Suport d'Icones"
      "AN" = "AN"  
      "DateBk3" = "DBk3"  
      "AN Icon Number:" = "Número d'Icone AN:"
      "DateBk3 Icon:" = "Icone DateBk3:"

    "Days" = "Dies"
	"Datebook" = "Agenda"
	"To Do" = "Tasques"
	"Scan note field" = "Cercar en Notes"

    "%d day(s) left" = "%d dies per al registre"  
    "%d day(s) passed" = "%d dies transcorreguts"


      "Notify Format:" = "Format de Notificació:"
      "[Last, First] E(1) Year" = "[Cognoms, Nom] E(1) Any"
	"[First Last] E(1) Year" = "[Nom Cognoms] E(1) Any"
	"Event - Last, First Year" = "Registre - Cognoms, Nom Any"
	"Event - First Last Year" = "Registre - Nom Cognoms Any"
	"First Last Year" = "Nom Cognoms Any"

    
      "Processing" = "Procesando"
	"Processed : " = "Processat : "	

      "Name" = "Nom"
	"Date" = "Data"
	"Age"  = "Edat"

END
