TRANSLATION "CZECH"
BEGIN
    "Translator" = "Petr 'PePa' Pavel"
    "Translator's email" = "petr.pavel@email.cz"

    "long_notifySettingString" = ""\
    "* Záznamy\n"\
    "Zvol 'vše', chceš-li vytvoøit upozornìní pro všechny "\
    "události v této kategorii. "\
    "Monost 'zvolenı' vytvoøí událost pouze pro zvolenı záznam.\n\n"\
    "* Existující\n"\
    "Zvol 'nech bıt', pokud upozornìní (ji "\
    "vytvoøená programem HappyDays) nechceš mìnit. "\
    "Monost 'zmìò' tato upozornìní aktualizuje.\n\n"\
    "* Alarm\n"\
    "Aktivuje u pøidávanıch upozornìní alarm. "\
    "Zvol kolik dní dopøedu chceš alarm nastavit.\n\n"\
    "* Èas\n"\
    "Kdy alarm spustí.\n\n"\
    "* Opakuj\n"\
    "Interval urèující, jak dlouho dopøedu se má upozornìní zobrazovat. "\
    "-1 znamená pro události solárního kalendáøe navdy a pro lunární 5 let.\n"

    "long_notifySettingMoreString" = ""\
    "Nápovìdu k ikonám pro Action Names (AN) najdeš v jeho manuálu. "\
    "Ikony pro DateBk3/4 musejí bıt uloeny v Memo Padu. "\
    "Pokud je tam nemáš, nic se nezobrazí.\n"

    "long_customErrorString" = ""\
    "Název uivatelské poloky v Address Booku, "\
    "ze které ète HappyDays datum narozenin a svátkù. "\
    "Pokud ho chceš zmìnit, zvol 'Nastavení'.\n\n"\
    "POZOR: Potøebuješ-li zmìnit názvy uivatelskıch poloek v Address Booku, "\
    "spus jej a v menu 'Options' zvol monost 'Rename Custom Fields'. "\
    "Název aspoò jedné takové poloky musí odpovídat názvu, kterı jsi "\
    "zadal v HappyDays.\n"

    "long_aboutString" = ""\
    "'HappyDays' ti pomùe pamatovat na narozeniny a svátky tvıch pøátel "\
    "a èlenù rodiny.\n\n"\
    "Pouívá k tomu jednu z uivatelskıch poloek Address Booku, kterou "\
    "musíš pojmenovat stejnì, jako jsi uvedl v 'Nastavení' tohoto programu."\
    "\n\nPøíklady:\n"\
    " Pøíjmení: Jeong\n"\
    " Køestní jméno: JaeMok\n"\
    " ...\n"\
    " Narozeniny: -)12/4/70\n\n"\
    "Formáty:\n"\
    " [-)|#)]Datum\n"\
    " -) pro lunární bìnı mìsíc\n"\
    " #) pro lunární pøestupnı mìsíc\n\n"\
    "Formát data se automaticky pøevezme z nastavení v Preferences. "\
    "Rok mùeš vynechat. Je-li rok menší ne 100, pøedpokládá se, e jde "\
    "o dvacáté století. Pokud si nejsi jistı, piš rok ètyøcifernì (napø. 1970).\n\n"\
    "Potøebuješ-li zadat víc událostí, podívej se do manuálu.\n"

    "long_cleanupAlertString" = ""\
    "Události Date Booku a To Do vytvoøené programem HappyDays, mají v poznámce "\
    "èíselnı identifikátor nastavitelnı v 'Nastavení'. "\
    "Pokud podobnı vloíš do poznámky nìkteré události ruènì, mùe se stát, "\
    "e ji HappyDays smae také.\n"

    "long_prefFormString" = ""\
    "* Místo systémového formátu...\n"\
    "Formát uivatelské poloky s daty narozenin nebo svátkù. "\
    "Defaultnì je stejnı jako nastavení v systémovıch 'Preferences'.\n\n"\
    "* Prohledej i poznámky\n"\
    "HappyDays mùe hledat data událostí i v poznámkách kontaktù Address Booku.\n\n"\
    "* Zvırazni lunární datum\n"\
    "Zobrazí pod lunárním datem èárkovanou èáru.\n\n"\
    "* Formát upozornìní\n"\
    "Formát, kterı bude pouit pøi tvorbì upozornìní do Date Booku èi To Do.\n\n"\
    "* Název poloky\n"\
    "Název uivatelské poloky v Address Booku, v ní HappyDays hledá datum události.\n\n"\
    "* Identifikátor\n"\
    "Pouívá se pro oznaèení záznamù v Date Booku a To Do vytvoøenıch programem HappyDays.\n"

    "long_removeConfirmString" = ""\
    "Urèitì chceš odstranit všechna "\
    "upozornìní vytvoøená programem HappyDays?"

    "long_sl2lnString" = ""\
        "-) pro bìnı mìsíc lunárního kalendáøe\n"\
        "#) pro pøestupnı mìsíc lunárního kalendáøe"

    "long_cantFindAddrString" = ""\
    "V Address Booku není ádná uivatelská poloka s názvem: '%s'\n"\
    "Vytvoø takovou nebo zmìò její název v 'Nastavení' programu HappyDays."

    "Select Time" = "Zvol èas"
    "No Time" = "ádnı"
    "Invalid input date" = "Neplatné datum"
    "Export to Memo Pad is completed." = "Export do Memo Padu dokonèen."

    "SUN"   = "Ne"
    "MON"   = "Po"
    "TUE"   = "Út"
    "WED"   = "St"
    "THU"   = "Èt"
    "FRI"   = "Pá"
    "SAT"   = "So"

    "Not enough memory" = "Nedostatek pamìti"
    "%d notify entry is created.\n" = "Vytvoøeno %d upozornìní.\n" 
    "%d existing entry " = "%d existujících upozornìní "
    "is kept untouched." = "ponecháno beze zmìny."
    "is modified." = "zmìnìno."

    "Could not write prefs." = ""\
    "Nemohu uloit nastavení."
    "Collecting Information..." = "Sbírám informace..."

    "HappyDays List" = "Seznam"
    "Look up" = "Hledej"
    "Today" = "Dnes"

    "HappyDays View" = "Detaily"
    "Done"  = "OK"
    "DB" = "DB" 
    "TD" = "TD"
    "Goto" = "Address Book"

    "Utilities" = "Akce"
    "Date Book Notify" = "Upozornìní Date Booku"
    "Cleanup Date Book"  = "Vyèištìní Date Booku"
    "To Do Notify" = "Upozornìní To Do"
    "Cleanup To Do"  = "Vyèištìní To Do"
    "Export to Memo Pad" = "Export do Memo Padu"
    "Solar to Lunar" = "Solarní na lunární"
    "Lunar to Solar" = "Lunární na solární"
    "Options" = "Monosti"
    "Preferences" = "Nastavení"
    "About HappyDays" = "O aplikaci HappyDays"

    "Edit" = "Uprav"
    "Undo" = "Zpìt"
    "Cut" = "Vyjmout"
    "Copy" = "Kopírovat" 
    "Paste" = "Vloit" 
    "Select All" = "Oznaè vše" 
    "Keyboard" = "Klávesnice" 
    "Graffiti" = "Graffiti"

    "HappyDays Preferences" = "Nastavení"
    "Custom field:" = "Název poloky:"
    "HappyDays ID:" = "Identifikátor:"
    "Emphasize Lunar Date" = "Zvırazni lunární datum"

    "OK" = "OK"
    "Cancel" = "Storno"

    "Solar to Lunar Convert" = "Solární na lunární"
    "Enter Solar date:" = "Zadej solární datum:"
    "Year must be in 1881-2043" = "Rok musí bıt mezi 1881 a 2043."
    "Result Lunar date:" = "Vısledné lunární datum:"

    "Convert" = "Pøevod"

    "Lunar to Solar Convert" = "Lunární na solární"
    "Enter Lunar date:" = "Zadej lunární datum:"
    "Leap" = "pøestupnı"
    "Result Solar date:" = "Vısledné solární datum:"

    "Records:" = "Záznamy:"
      "all" = "vše"
      "selected" = "zvolenı" 
    "Existing:" = "Existující:"
      "keep" = "nech bıt"
      "modify" = "zmìò"
    "Priority:" = "Priorita:"
    "Category:" = "Kategorie:"
    "Private:" = "Soukromé:"
    "Alarm:" = "Alarm:"
    "Time:" = "Èas:"
    "More..." = "Další..."

    "Repeat for:" = "Opakuj:"
    "years" = "rok(y)/let"

    "HappyDays says" = "HappyDays"

    "HappyDays Export" = "Export"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
    	"Skuteènì chceš exportovat seznam události z HappyDays do Memo Padu?" 

    "Custom Field Error" = "Chybnı název poloky"
    "Help" = "Nápovìda"


    "HappyDays Cleanup" = "Vyèisti" 

    "Notify warning" = "Upozornìní"
    "^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
  	"^1: Urèitì chceš vytvoøit upozornìní pro ^2 poloek?" 
      

    "Invalid event format" = "Neplatnı formát události" 

    "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
    "Záznam pro ^1\n má neplatnı formát. Co s tím mám dìlat?"

    "Ignore" = "Ignoruj" 
    "Ignore all" = "Ignoruj vše"

    "Cleanup Done" = "Vyèištìní dokonèeno" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    	"^1: Odstranìno ^2 záznamù." 

    "Birthday" = "Narozeniny" 
    "All" = "Všechny" 
    "HappyDays Export List" = "Export" 
    "(not exist in this year)" = "(v tomto roce se nevyskytuje)" 
    "Please run Date Book once first." = "Nejdøív spuste aspoò jednou Date Book."  
    
    "Instead of system date format" = "Místo systémového formátu"
    "Use" = "pouij"
    "M/D/Y" = "M/D/R"
    "D/M/Y" = "D/M/R"  
    "D.M.Y" = "D.M.R"  
    "D-M-Y" = "D-M-R"  
    "Y/M/D" = "R/M/D"  
    "Y.M.D" = "R.M.D"  
    "Y-M-D" = "R-M-D"  

    "Date Book Icon" = "Ikony"
    "Icon Support" = "Ikony pro"  
    "AN" = "AN"  
    "DateBk3" = "DateBk3/4"  
    "AN Icon Number:" = "Èíslo ikony pro AN:"  
    "DateBk3 Icon:" = "Ikona pro DateBk3/4:"  

    "Days" = "dny"  
    "Date Book" = "Date Book"  
    "To Do" = "To Do"  
    "Scan note field" = "Prohledej i poznámky"  
    "%d day(s) left" = "Zbıvá %d dní"  
    "Notify Format:" = "Formát upozornìní:"  
    "[Last, First] E(1) Year" = "[pøíjm., køest.] u (rok)"  
    "[First Last] E(1) Year" = "[køest. pøíjm.] u (rok)"  
    "Event - Last, First Year" = "událost - pøíjm., køest. rok"  
    "Event - First Last Year" = "událost - køest. pøíjm. rok"  
    "First Last Year" = "køest. pøíjm. rok"  
    
    "Processing" = "Vytváøím"  
    "Processed : " = "Vytvoøeno: " 
END
