TRANSLATION "DUTCH"
BEGIN
    "Translator" = "Jan Verhoeven"
    "Translator's email" = "HappyDays@jeve.net"

    "long_notifySettingString" = ""\
    "* Verjaardagen\n"\
    "Kies 'all' als u alle gegevens wilt aanpassen "\
    "in de gekozen categorie"\
    "."\
    "Kies 'selected' als u 1 verjaardag wilt aanpassen "\
    ".\n\n"\
    "* Existing\n"\
    "Kies 'keep' als u de aanwezige HappyDays invoer "\
    "ongewijzigd moet blijven. Kies 'modify' als u wilt dat de "\
    "invoer wordt aangepast.\n\n"\
    "* Alarm\n"\
    "Stelt het alarm in in uw agenda. Selecteer het aantal dagen "\
	"dat u vooraf aan de verjaardag wordt herinnerd.\n\n"\
    "* Time\n"\
	"Tijd van de melding.\n\n"\
    "* Herhaal voor\n"\
    "is de interval van de melding. "\
    "-1 betekend hewrhaling altijd voor een solar event, en "\
    "betekend herhaald voor 5 jaren in lunar event voor de zekerheid.\n"

	"long_notifySettingMoreString" = ""\
	"For AN Icon Number, consult Action Names manual. DateBk3Icon is "\
	"read from MemoPad. If you don't have DateBk3 Icon entry in MemoPad, "\
	"nothing is displayed.\n"

    "long_customErrorString" = ""\
    "'Birthday' is the default custom field name."\
    "To set a different default custom field"\
    " name, tap 'Preferences'.\n\n"\
    "IMPORTANT: You need to launch your Addressbook and select 'Options/"\
    "Rename Custom Fields' to rename a custom field to 'Birthday'"\
    " or whatever you set as a custom field name in the Preferences of "\
    "HappyDays.\n"

    "long_aboutString" = ""\
    "'HappyDays' will help you remember the birthdays and anniversaries "\
    "of your friends and family members, as well as other events."\
    "\n\nUse one of the custom fields in Address Book application "\
    "and rename it to 'Verjaardag'."\
    "\n\nExamples:\n"\
    " Achternaam: Verhoeven\n"\
    " Voornaam: Jan\n"\
    " ...\n"\
    " Verjaardag: -)12/4/70\n\n"\
    "Formats:\n"\
    " [-)|#)]Date\n"\
    " -) betekend lunar kalender\n"\
    " #) betekend lunar loop maand\n\n"\
    "Datum formaat is automatisch uit systeem gegenereerd. "\
    "U kunt het jaar-veld aanpassen. Jaar invoer lager dan 100 wordt aangemerkt als "\
    "een jaar in de 20st eeuw, bent u niet zeker van het juiste jaar, "\
    "gebruik voor jaar JJJJ(b.v. 1970).\n\n"\
    "Voor meerdere gegevens gelijktijdig in te voeren, zie handleiding.\n"

    "long_cleanupAlertString" = ""\
    "Notification entries are considered HappyDays if they have "\
	"{HappyDays ID} in their memo field. "\ 	
    "If you use this format in your own "\
    "entries, this record might also be removed by CleanUp.\n"

    "long_prefFormString" = ""\
	"* Inplaats van de systeemdatum\n"\
	"Controleer op de naam van uw eigen veld hetzelfde is dan die in het adresboek. "\
	"Normaal moeten deze hetzelfde zijn.\n\n"\
	"* Scan notities\n"\
	"Om notities te lezen, check deze optie.\n\n"\
    "* Emphasize Lunar Date\n"\
    "If checkbox is on, the dashed line is drawed beneath lunar date.\n\n"\
	"* Overzicht formaat\n"\
	"De wijze waarop u de lijst kan bekijken\n\n"\
    "* Eigen veld\n"\
    "De naam van het eigen veld in het adresboek voor INVOER\n\n"\
    "* HappyDays ID\n"\
    "Te gebruiken voor meldingen en opschonen\n"

    "long_removeConfirmString" = ""\
    "Weet u zeker dat alles verwijderd moet worden "\
    "HappyDays notify entries?"

    "long_sl2lnString" = ""\
        "-) means plain month in lunar\n"\
        "#) means leap month in lunar"

    "long_cantFindAddrString" = ""\
    "Kan eigen veld niet vinden in het adresboek: '%s'\n"\
    "Wijzig naam van eigen veld in Verjaardag in uw adresboek."

    "Select Time" = "Selecteer tijd"
    "No Time" = "Geen tijd"
    "Invalid input date" = "Onjuiste datum"
    "Export to Memo Pad is completed." = "Export naar Memo is voltooid."

    "SUN"   = "ZON"
    "MON"   = "MAA"
    "TUE"   = "DIN"
    "WED"   = "WOE"
    "THU"   = "DON"
    "FRI"   = "VRY"
    "SAT"   = "ZAT"

    "Not enough memory" = "Niet genoeg geheugen"
    "%d notify entry is created.\n" = "%d melding is niet aangemaakt.\n" 
    "%d existing entry " = "%d incvoer is niet aanwezig "
    "is kept untouched." = "is ongewijzigd bewaard."
    "is modified." = "is aangepast."

    "Could not write prefs." = ""\
		"Kan niet worden aangepast."
    "Collecting Information..." = "Verzameld informatie..."

    "HappyDays List" = "HappyDays Overzicht"
    "Look up" = "Ga naar datum.."
    "Today" = "Vandaag"

    "HappyDays View" = "HappyDays View"
    "Done"  = "Gedaan"
    "DB" = "DB" 
    "TD" = "TD"
    "Goto" = "Ga naar"

    "Utilities" = "Utilities"
    "Date Book Notify" = "Agenda afspraak"
    "Cleanup Date Book"  = "Opschonen agenda"
    "To Do Notify" = "To Do melding"
    "Cleanup To Do"  = "Opschonen To Do"
    "Export to Memo Pad" = "Export naar Memo"
    "Solar to Lunar" = "Solar to Lunar"
    "Lunar to Solar" = "Lunar to Solar"
    "Options" = "Opties"
    "Preferences" = "Eigenschappen"
    "About HappyDays" = "Over HappyDays"

    "Edit" = "Wijzigen"
    "Undo" = "Ongedaan maken"
    "Cut" = "Knippen"
    "Copy" = "Kopieren" 
    "Paste" = "Plakken" 
    "Select All" = "Selecteer alles" 
    "Keyboard" = "Keyboard" 
    "Graffiti" = "Graffiti"

    "HappyDays Preferences" = "HappyDays Eigenschappen"
    "Custom field:" = "Verjaardag:"
    "HappyDays ID:" = "HappyDays ID:"
    "Emphasize Lunar Date" = "Emphasize Lunar Date"

    "OK" = "OK"
    "Cancel" = "Annuleren"

    "Solar to Lunar Convert" = "Solar to Lunar Convert"
    "Enter Solar date:" = "Voer Solar Datum in:"
    "Year must be in 1881-2043" = "Jaartal moet liggen tussen 1881-2043"
    "Result Lunar date:" = "Resultaat Lunar datum:"

    "Convert" = "Converteer"

    "Lunar to Solar Convert" = "Lunar to Solar Converteren"
    "Enter Lunar date:" = "Voer Lunar datum in:"
    "Leap" = "Loopt"
    "Result Solar date:" = "Resultaat Solar datum:"

    "Records:" = "Records:"
      "all" = "allen"
      "selected" = "geselecteerd" 
    "Existing:" = "Aanwezig:"
      "keep" = "bewaren"
      "modify" = "wijzigen"
    "Priority:" = "Prioriteit:"
    "Category:" = "Categorie:"
    "Private:" = "Prive:"
    "Alarm:" = "Alarm:"
    "Time:" = "Tijd:"
    "More..." = "Meer..."

    "Repeat for:" = "Herhaal voor:"
    "years" = "jaren"

    "HappyDays says" = "HappyDays zegt"

    "HappyDays Export" = "HappyDays Export"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
    	" Wilt u de verjaardagen exporteren naar Memo?" 

    "Custom Field Error" = "Eigen veld fout"
    "Help" = "Help" 


    "HappyDays Cleanup" = "HappyDays Opschonen" 

    "Notify warning" = "Notify warning" 
    "^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
  	"^1: Weet u zeker dat u nieuwe gegevens wilt invoeren voor ^2 HappyDays records?" 
      

    "Invalid event format" = "Injuist evenement formaat" 

    "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
    "Het adresveld^1\n bevat een onjuist gegeven. Hoe wilt u dit oplossen?" 

    "Ignore" = "afbreken" 
    "Ignore all" = "Alles afbreken" 

    "Cleanup Done" = "Opschonen voltooid" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    	"^1: ^2 HappyDays invoer is verwijderd." 

    "Birthday" = "Verjaardag" 
    "All" = "Allen" 
    "HappyDays Export List" = "HappyDays Export Lijst" 
    "(not exist in this year)" = "(bestaat niet in dit jaar)" 
    "Please run Date Book once first." = "Open eerst uw agenda."  
    
    "Instead of system date format" = "Instead of system date format"  
    "Use" = "Gebruik"  
    "M/D/Y" = "M/D/Y"  
    "D/M/Y" = "D/M/Y"  
    "D.M.Y" = "D.M.Y"  
    "D-M-Y" = "D-M-Y"  
    "Y/M/D" = "Y/M/D"  
    "Y.M.D" = "Y.M.D"  
    "Y-M-D" = "Y-M-D"  

    "DateBook Icon" = "DateBook Icon"  
      "Icon Support" = "Icon Support"  
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "AN Icon Number:"  
      "DateBk3 Icon:" = "DateBk3 Icon:"  

    "Days" = "Dagen"  
    "Date Book" = "Agenda"  
    "To Do" = "To Do"  
    "Scan note field" = "Scan notitievelden"  
    "%d day(s) left" = "%d dag(en) te gaan"  
    "Notify Format:" = "Notify Format:"  
    "[Last, First] E(1) Year" = "[Achternaam, Voornaam] L(1) Jaar"  
    "[First Last] E(1) Year" = "[Voornaam Achternaam] L(1) Jaar"  
    "Event - Last, First Year" = "Event - Achternaam, Voornaam Jaar"  
    "Event - First Last Year" = "Event - Voornaam Achternaam Jaar"  
    "First Last Year" = "Voornaam Achternaam Jaar"  
    
    "Processing" = "Verwerken"  
    "Processed : " = "Verwerkt : " 
END


