TRANSLATION "ENGLISH"
BEGIN
    "Translator" = "English version"
    "Translator's email" = ""

    "long_notifySettingString" = ""\
    "* Records\n"\
    "Tab 'all' if you'd like to "\
    "make notification entries created for all of your events in this"\
    " category."\
    "Tab 'selected' if only the currently selected record should be "\
    "taken into account.\n\n"\
    "* Existing\n"\
    "Tap 'keep' if existing HappyDays entries "\
    "should be left untouched. Tap 'modify' if you'd like "\
    "these entries to be changed.\n\n"\
    "* Alarm\n"\
    "will set the alarm notification in your datebook entry. Set "\
	"the number of days in advance you'd like to get notified.\n\n"\
    "* Time\n"\
	"Time of the event\n\n"\
    "* Repeat for\n"\
    "is the interval of the notification record. "\
    "-1 means repeat forever in case of solar event, and "\
    "means repeat for 5 years in lunar event for convenience.\n"

	"long_notifySettingMoreString" = ""\
	"For AN Icon Number, consult Action Names manual. DateBk3Icon is "\
	"read from MemoPad. If you don't have DateBk3 Icon entry in MemoPad, "\
	"nothing is displayed.\n"

    "long_customErrorString" = ""\
    "'Birthday' is the default custom field name."\
    "To set a different default custom field"\
    " name, tap 'Preferences'.\n\n"\
    "IMPORTANT: You need to launch your Addressbook and select 'Options/"\
    "Rename Custom Fields' to rename a custom field to 'Birthday'"\
    " or whatever you set as a custom field name in the Preferences of "\
    "HappyDays.\n"

    "long_aboutString" = ""\
    "'HappyDays' will help you remember the birthdays and anniversaries "\
    "of your friends and family members, as well as other events."\
    "\n\nUse one of the custom fields in Address Book application "\
    "and rename it to 'Birthday'."\
    "\n\nExamples:\n"\
    " Last Name: Jeong\n"\
    " First name: JaeMok\n"\
    " ...\n"\
    " Birthday: -)12/4/70\n\n"\
    "Formats:\n"\
    " [-)|#)]Date\n"\
    " -) means lunar calendar\n"\
    " #) means lunar leap month\n\n"\
    "Date format is automatically read from the system preferences. "\
    "You can omit the year field. Year input below 100 is assumed to be "\
    "year in the 20th century, If you are not sure of the year format, "\
    "just write it in form of YYYY(e.g. 1970).\n\n"\
    "To set multiple entry, refer the manual.\n"

    "long_cleanupAlertString" = ""\
    "Notification entries are considered HappyDays if they have "\
	"{HappyDays ID} in their memo field. "\ 	
    "If you use this format in your own "\
    "entries, this record might also be removed by CleanUp.\n"

    "long_prefFormString" = ""\
	"* Instead of system date...\n"\
	"Control the interpretation of the AddressDB Birthday custom field. "\
	"By default this is the same as the system date format preference.\n\n"\
	"* Scan note field\n"\
	"To read note field in Address Book, check this option.\n\n"\
    "* Emphasize Lunar Date\n"\
    "If checkbox is on, the dashed line is drawed beneath lunar date.\n\n"\
	"* Notify format\n"\
	"The description format used for notification\n\n"\
    "* Custom field\n"\
    "The name of custom fields in Address Book used for INPUT\n\n"\
    "* HappyDays ID\n"\
    "Used for Notify and Cleanup\n"

    "long_removeConfirmString" = ""\
    "Are you sure you want to remove all "\
    "HappyDays notify entries?"

    "long_sl2lnString" = ""\
        "-) means plain month in lunar\n"\
        "#) means leap month in lunar"

    "long_cantFindAddrString" = ""\
    "Can't find custom address book field: '%s'\n"\
    "Please rename a custom field of your address book."
END

