TRANSLATION "ENGLISH"
BEGIN
    "Translator" = "English version"
    "Translator's email" = ""

    "long_notifySettingString" = ""\
    "* Records\n"\
    "Tab 'all' if you'd like to "\
    "make notification entries created for all of your events in this"\
    " category."\
    "Tab 'selected' if only the currently selected record should be "\
    "taken into account.\n\n"\
    "* Existing\n"\
    "Tap 'keep' if existing HappyDays entries "\
    "should be left untouched. Tap 'modify' if you'd like "\
    "these entries to be changed.\n\n"\
    "* Alarm\n"\
    "will set the alarm notification in your datebook entry. Set "\
	"the number of days in advance you'd like to get notified.\n\n"\
    "* Time\n"\
	"Time of the event\n\n"\
    "* Repeat for\n"\
    "is the interval of the notification record. "\
    "-1 means repeat forever in case of solar event, and "\
    "means repeat for 5 years in lunar event for convenience.\n"

	"long_notifySettingMoreString" = ""\
	"For AN Icon Number, consult Action Names manual. DateBk3Icon is "\
	"read from MemoPad. If you don't have DateBk3 Icon entry in MemoPad, "\
	"nothing is displayed.\n"

    "long_customErrorString" = ""\
    "'Birthday' is the default custom field name."\
    "To set a different default custom field"\
    " name, tap 'Preferences'.\n\n"\
    "IMPORTANT: You need to launch your Addressbook and select 'Options/"\
    "Rename Custom Fields' to rename a custom field to 'Birthday'"\
    " or whatever you set as a custom field name in the Preferences of "\
    "HappyDays.\n"

    "long_aboutString" = ""\
    "'HappyDays' will help you remember the birthdays and anniversaries "\
    "of your friends and family members, as well as other events."\
    "\n\nUse one of the custom fields in Address Book application "\
    "and rename it to 'Birthday'."\
    "\n\nExamples:\n"\
    " Last Name: Jeong\n"\
    " First name: JaeMok\n"\
    " ...\n"\
    " Birthday: -)12/4/70\n\n"\
    "Formats:\n"\
    " [-)|#)]Date\n"\
    " -) means lunar calendar\n"\
    " #) means lunar leap month\n\n"\
    "Date format is automatically read from the system preferences. "\
    "You can omit the year field. Year input below 100 is assumed to be "\
    "year in the 20th century, If you are not sure of the year format, "\
    "just write it in form of YYYY(e.g. 1970).\n\n"\
    "To set multiple entry, refer the manual.\n\n" \
	"Name1 & name2 displayed in HappyDays List is determined by "\
	"'AddressBook/Preferences/List by'. If you change this preferences, "\
	"you can see the different views.\n\n"\
	"Date format is determined by System/Prefs/Formats/Date Format.\n\n"\
	"If you write character or number in graffiti area, the matching row "\
	"is highlighted. For example, if you write 'a' in graffiti, the "\
	"first record beginning with 'a' or 'A' is highlighted. "\
	"If you write '1' in graffiti, the nearest incoming record after January "\
	"is highlighted.\n"

    "long_cleanupAlertString" = ""\
    "Notification entries are considered HappyDays if they have "\
	"{HappyDays ID} in their memo field. "\ 	
    "If you use this format in your own "\
    "entries, this record might also be removed by CleanUp.\n"

    "long_prefFormString" = ""\
	"* Instead of system date...\n"\
	"Control the interpretation of the AddressDB Birthday custom field. "\
	"By default this is the same as the system date format preference.\n\n"\
	"* Scan note field\n"\
	"To read note field in Address Book, check this option.\n\n"\
    "* Emphasize Lunar Date\n"\
    "If checkbox is on, the dashed line is drawed beneath lunar date.\n\n"\
	"* Notify format\n"\
	"The description format used for notification\n\n"\
    "* Custom field\n"\
    "The name of custom fields in Address Book used for INPUT\n\n"\
    "* HappyDays ID\n"\
    "Used for Notify and Cleanup\n"

    "long_checkDateString" = ""\
    "As HappyDays algorithms use the current date for various date "\
    "calculation, incorrect data value would mislead it."


    "long_removeConfirmString" = ""\
    "Are you sure you want to remove all "\
    "HappyDays notify entries?"

    "long_sl2lnString" = ""\
        "-) means plain month in lunar\n"\
        "#) means leap month in lunar"

    "long_cantFindAddrString" = ""\
    "Can't find custom address book field: '%s'\n"\
    "Please rename a custom field of your address book."

    "Select Time" = "Select Time"
    "No Time" = "No Time"
    "Invalid input date" = "Invalid input date"
    "Export to Memo Pad is completed." = "Export to Memo Pad is completed."

    "SUN"   = "SUN"
    "MON"   = "MON"
    "TUE"   = "TUE"
    "WED"   = "WED"
    "THU"   = "THU"
    "FRI"   = "FRI"
    "SAT"   = "SAT"

    "Not enough memory" = "Not enough memory"
    "%d notify entry is created.\n" = "%d notify entry is created.\n" 
    "%d existing entry " = "%d existing entry "
    "is kept untouched." = "is kept untouched."
    "is modified." = "is modified."

    "Could not write prefs." = ""\
		"Could not write prefs."
    "Collecting Information..." = "Collecting Information..."

    "HappyDays List" = "HappyDays List"
    "Look Up:" = "Look Up:"

    "HappyDays View" = "HappyDays View"
    "Done"  = "Done"
    "DB" = "DB" 
    "TD" = "TD"
    "Goto" = "Goto"

    "Utilities" = "Utilities"
    "Date Book Notify" = "Date Book Notify"
    "Cleanup Date Book"  = "Cleanup Date Book"
    "To Do Notify" = "To Do Notify"
    "Cleanup To Do"  = "Cleanup To Do"
    "Export to Memo Pad" = "Export to Memo Pad"
    "Solar to Lunar" = "Solar to Lunar"
    "Lunar to Solar" = "Lunar to Solar"
    "Options" = "Options"
    "Preferences" = "Preferences"
    "About HappyDays" = "About HappyDays"

    "Edit" = "Edit"
    "Undo" = "Undo"
    "Cut" = "Cut"
    "Copy" = "Copy" 
    "Paste" = "Paste" 
    "Select All" = "Select All" 
    "Keyboard" = "Keyboard" 
    "Graffiti" = "Graffiti"

    "HappyDays Preferences" = "HappyDays Preferences"
    "Custom field:" = "Custom field:"
    "HappyDays ID:" = "HappyDays ID:"
    "Emphasize Lunar Date" = "Emphasize Lunar Date"

    "OK" = "OK"
    "Cancel" = "Cancel"

    "Solar to Lunar Convert" = "Solar to Lunar Convert"
    "Enter Solar date:" = "Enter Solar date:"
    "Year must be in 1881-2043" = "Year must be in 1881-2043"
    "Result Lunar date:" = "Result Lunar date:"

    "Convert" = "Convert"

    "Lunar to Solar Convert" = "Lunar to Solar Convert"
    "Enter Lunar date:" = "Enter Lunar date:"
    "Leap" = "Leap"
    "Result Solar date:" = "Result Solar date:"

    "Records:" = "Records:"
      "all" = "all"
      "selected" = "selected" 
    "Existing:" = "Existing:"
      "keep" = "keep"
      "modify" = "modify"
    "Priority:" = "Priority:"
    "Category:" = "Category:"
    "Private:" = "Private:"
    "Alarm:" = "Alarm:"
    "Time:" = "Time:"
    "More..." = "More..."

    "Repeat for:" = "Repeat for:"
    "years" = "years"

    "HappyDays says" = "HappyDays says"

    "HappyDays Export" = "HappyDays Export"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
    	"Would you like to export HappyDays List to Memo Pad?" 

    "Custom Field Error" = "Custom Field Error"
    "Help" = "Help" 


    "HappyDays Cleanup" = "HappyDays Cleanup" 

    "Notify warning" = "Notify warning" 
    "^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
  	"^1: Are you sure you want to create notify entries for ^2 HappyDays records?" 
      

    "Invalid event format" = "Invalid event format" 

    "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
    "The address record for ^1\n contains an invalid event. How would you like to handle it?" 

    "Ignore" = "Ignore" 
    "Ignore all" = "Ignore all" 

    "Cleanup Done" = "Cleanup Done" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    	"^1: ^2 HappyDays notify entries removed." 

    "Birthday" = "Birthday" 
    "All" = "All" 
    "HappyDays Export List" = "HappyDays Export List" 
    "(not exist in this year)" = "(not exist in this year)" 
    "Please run Date Book once first." = "Please run Date Book once first."  
    
    "Instead of system date format" = "Instead of system date format"  
    "Use" = "Use"  
    "M/D/Y" = "M/D/Y"  
    "D/M/Y" = "D/M/Y"  
    "D.M.Y" = "D.M.Y"  
    "D-M-Y" = "D-M-Y"  
    "Y/M/D" = "Y/M/D"  
    "Y.M.D" = "Y.M.D"  
    "Y-M-D" = "Y-M-D"  

    "Date Book Icon" = "Date Book Icon"  
      "Icon Support" = "Icon Support"  
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "AN Icon Number:"  
      "DateBk3 Icon:" = "DateBk3 Icon:"  

    "Days" = "Days"  
    "Date Book" = "Date Book"  
    "To Do" = "To Do"  
    "Scan note field" = "Scan note field"  
    "%d day(s) left" = "%d day(s) left"  
    "%d day(s) passed" = "%d day(s) passed"  
    "Notify Format:" = "Notify Format:"  
    "[Last, First] E(1) Year" = "[Last, First] E(1) Year"  
    "[First Last] E(1) Year" = "[First Last] E(1) Year"  
    "Event - Last, First Year" = "Event - Last, First Year"  
    "Event - First Last Year" = "Event - First Last Year"  
    "First Last Year" = "First Last Year"  
    
    "Processing" = "Processing"  
    "Processed : " = "Processed : " 

	"Name" = "Name"
	"Date" = "Date"
	"Age" = "Age"

END

