TRANSLATION "FRENCH"
BEGIN
    "Translator" = "Traduction: Cyril-Vianney BEKIER"
    "Translator's email" = "E-Mail: cyril@bekier.org"

    "long_notifySettingString" = ""\
    "* Evènements\n"\
    "Choisir 'Tous' si vous désirez créer des enregistrements "\
    "pour tous les évènements de cette catégorie.\n"\
    "Choisir 'En cours' si vous désirez créer un enregistrement "\
	"seulement pour l'évènement courant.\n\n"\
    "* Existant\n"\
    "Choisir 'Garder' s'il faut garder intact les évènements HappyDays existants.\n"\
	"Choisir 'Modifier' s'il faut les modifier.\n\n"\
    "* Alarme\n"\
    "Cochez cette option pour créer une alarme avec chaque évènement."\
	" Spécifiez combien de jour avant l'évènement vous souhaitez être averti.\n\n"\
    "* Heure\n"\
	"Heure de l'évènement\n\n"\
    "* Répéter\n"\
    " Défini l'intervalle de répétition de l'évènement.\n"\
    "Mettre -1 pour un évènement solaire donne une répétition à l'infini,"\
    "pour un évènement lunaire cela donne une répétition de 5 ans.\n"

	"long_notifySettingMoreString" = ""\
	"Pour les N° d'icône AN, veuillez consulter le manuel d'Action Names.\n\n"\
	"Les icônes DateBk3 sont lus depuis le Bloc-notes. Si vous n'avez pas de mémo DateBk3 rien ne s'affichera.\n"

    "long_customErrorString" = ""\
    "'Anniversaire' est le nom par défaut du champ personnalisé.\n"\
    "ATTENTION: Vous devez lancer 'Adresse' puis choisir 'Renommer champ' dans le menu 'Options'"\
	" pour renommer un des champs personalisés en 'Anniversaire'. "\
    "Vous pouvez aussi définir le nom du champ personalisé dans les préférences d'HappyDays, \n"\
	"pour cela : choisir 'Préférences' dans le menu 'Options'.\n\n"

    "long_aboutString" = ""\
    "'HappyDays' vous évite d'oublier de souhaiter un anniversaire "\
	"ou tout autre évènement de cette importance à un ami ou à un membre de votre famille.\n\n"\
    "Utilisez un des champs personnalisés de votre Carnet d'adresse et renommez le en 'Anniversaire'.\n\n"\
    "Exemple:\n"\
    " Nom:      BEKIER\n"\
    " Prénom: Cyril-Vianney\n"\
    " ...\n"\
    " Anniversaire: -)26/11/71\n\n"\
    "Formats:\n"\
    " [-)|#)]Date\n"\
    " -) signifie calendrier lunaire\n"\
    " #) signifie mois lunaire intercalaire\n\n"\
    "Le Format de Date est automatiquement lu depuis les préférences système. "\
	"Vous pouvez omettre l'année. Les années inférieur à 100 sont considérées "\
	"comme des années du 20ème siècle. Il est conseillé d'écrire les années "\
	"au format AAAA (ex. 1971).\n\n"\
	"Pour définir des entrées multiples, voir le manuel.\n"

    "long_cleanupAlertString" = ""\
    "Les enregistrements HappyDays sont reconnu "\
	"si l'identifiant HappyDays {ID HappyDays} est dans le champ note."\ 	
    "Si vous utilisez le même identifiant dans vos enregistrements, "\
    "ceux-ci seront aussi suuprimés.\n"

    "long_prefFormString" = ""\
	"* Remplacer la Date système par\n"\
	"Contrôle l'interprétation du champ personnalisé dans le carnet d'adresse. "\
	"Par défaut, c'est le format date défini dans 'Préférences'.\n\n"\
	"* Scruter le champ Note\n"\
	"Pour chercher l'anniversaire dans le champ note du carnet d'adresse, cochez cette option.\n\n"\
    "* Souligner les dates lunaire\n"\
    "Une ligne pointillée est dessinée sous les dates lunaires, si cette option est cochée.\n\n"\
	"* Format de l'évènement\n"\
	"Description du format utilisé dans l'évènement.\n\n"\
    "* Champ perso\n"\
    "Nom du champ personnalisé dans le carnet d'adresse utilisé pour l'anniversaire\n\n"\
    "* ID HappyDays\n"\
    "Identifiant servant à reconnaître les évènements HappyDays.\n"\
	"Cet identifiant est inséré dans le champ note.\n"

    "long_sl2lnString" = ""\
        "-) signifie mois lunaire plein\n"\
        "#) signifie mois lunaire intercalaire"

    "long_cantFindAddrString" = ""\
    "Impossible de trouver le champ personnalisé: '%s'\n"\
    "Veuillez renommer un des champs personnalisés du Carnet d'Adresses."
	
	
    "Select Time" = "Choix heure"
    "No Time" = "Sans heure"
    "Invalid input date" = "Date incorrecte"

    "SUN"   = "DIM"
    "MON"   = "LUN"
    "TUE"   = "MAR"
    "WED"   = "MER"
    "THU"   = "JEU"
    "FRI"   = "VEN"
    "SAT"   = "SAM"

    "Not enough memory" = "Plus assez de mémoire"
    "%d notify entry is created.\n" = "%d évènements créés.\n"
    "%d existing entry " = "%d évènements existants "
    "is kept untouched." = "n'ont pas été modifiés."
    "is modified." = "ont été modifiés."

    "Could not write prefs." = "Impossible d'enregistrer vos préférences."
    "Collecting Information..." = "Recherche des Informations..."

    "HappyDays List" = "Liste HappyDays"
    "Look up" = "Aller à"
    "Today" = "Aujourd'hui"

	"HappyDays View" = "Vue HappyDays"
	"%d day(s) left" = "%d jour(s) restant(s)"
    "Done"  = "Terminé"
    "DB" = "Ag"
    "TD" = "Tâ"
    "Goto" = "Allez"

    "Utilities" = "Outils"
    "Date Book Notify" = "Export vers Agenda"
    "Cleanup Date Book"  = "Nettoyer Agenda"
    "To Do Notify" = "Export vers Tâches"
    "Cleanup To Do"  = "Nettoyer Tâches"
    "Export to Memo Pad" = "Export vers Bloc-notes"
    "Solar to Lunar" = "Solaire -> Lunaire"
    "Lunar to Solar" = "Lunaire -> Solaire"

    "Options" = "Options"
    "Preferences" = "Préférences"
    "About HappyDays" = "A propos d'HappyDays"

    "Edit" = "Edition"
    "Undo" = "Annuler"
    "Cut" = "Couper"
    "Copy" = "Copier"
    "Paste" = "Coller"
    "Select All" = "Sélectionner tout"
    "Keyboard" = "Clavier"
    "Graffiti" = "Aide Graffiti"

    "HappyDays Preferences" = "Préférences HappyDays"
    "Custom field:" = "Champ perso:"
    "HappyDays ID:" = "ID HappyDays:"
    "Emphasize Lunar Date" = "Souligner les dates lunaires"

    "OK" = "OK"
    "Cancel" = "Annuler"

    "Solar to Lunar Convert" = "Solaire -> Lunaire"
    "Enter Solar date:" = "Entrez la date Solaire:"
    "Year must be in 1881-2043" = "Année comprise entre 1881 et 2043"
    "Result Lunar date:" = "Résultat Date Lunaire:"

    "Convert" = "Convertir"

    "Lunar to Solar Convert" = "Lunaire -> Solaire"
    "Enter Lunar date:" = "Entrez la date Lunaire:"
    "Leap" = "Intercalaire"
    "Result Solar date:" = "Résultat Date Solaire:"

    "Records:" = "Evènements:"
      "all" = "Tous"
      "selected" = "En cours"
    "Existing:" = "Existant:"
      "keep" = "Garder"
      "modify" = "Modifier"
    "Priority:" = "Priorité:"
	"Category:" = "Catégorie:"
    "Private:" = "Personnel:"
    "Alarm:" = "Alarme:"
    "Time:" = "Heure:"
    "More..." = "Plus..."

    "Repeat for:" = "Répéter:"
    "years" = "An(s)"

    "HappyDays says" = "HappyDays dit"

    "HappyDays Export" = "Export HappyDays"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
      "Voulez-vous exporter HappyDays vers le Bloc-notes?"
    "Export to Memo Pad is completed." = "L'export vers le Bloc-notes est terminé."
	  
    "Custom Field Error" = "Champ Personnalisé"
    "Help" = "Aide"


    "HappyDays Cleanup" = "Nettoyage HappyDays"

    "Notify warning" = "Attention"
    "^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
      "^1: Etes vous certains de vouloir créer ^2 évènements(s) HappyDays?"

    "Invalid event format" = "Format évènements incorrect"

    "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
      "L'anniversaire de ^1, dans le Carnet d'Adresse, est incorrect.\n Voulez-vous l'éditer?"

    "Ignore" = "Ignorer"
    "Ignore all" = "Ignorer tout"

	"long_removeConfirmString" = ""\
    "Etes-vous certains de vouloir supprimer "\
    "tous les évènements HappyDays ?"
    
	"Cleanup Done" = "Nettoyage effectué"

    "^1: ^2 HappyDays notify entries removed." = ""\
      "^1: \n^2 évènement(s) HappyDays supprimé(s)."

    "Birthday" = "Anniversaire"
    "All" = "Tous"
    "HappyDays Export List" = "Liste Exportée par HappyDays"
    "(not exist in this year)" = "(n'existe pas cette année)"
    "Please run Date Book once first." = "Veuillez d'abord ouvrir l'Agenda."
    "Instead of system date format" = "Remplacer la Date système"
    "Use" = "Par:"
    "M/D/Y" = "M/J/A"
    "D/M/Y" = "J/M/A"
    "D.M.Y" = "J.M.A"
    "D-M-Y" = "J-M-A"
    "Y/M/D" = "A/M/J"
    "Y.M.D" = "A.M.J"
    "Y-M-D" = "A-M-J"

	"DateBook Notify More" = "Export vers l'Agenda"
	"Date Book Icon" = "Icône de l'Agenda"
      "Icon Support" = "Gestion des Icônes"
	  "AN" = "AN"
	  "DateBk3" = "DateBk3"
      "AN Icon Number:" = "Numero d'Icône AN:"
      "DateBk3 Icon:" = "Icône DateBk3:"
	  "Icon" = "Icône"
	  

    "Days" = "Jours"
	"Date Book" = "Agenda"
	"To Do" = "Tâches"
	"Scan note field" = "Scruter le champ Note"
	
	"Notify Format:" = "Format d'un évènement:"
    "[Last, First] E(1) Year" = "[Nom, Prénom] évé. (Age)"
	"[First Last] E(1) Year" = "[Prénom  Nom] évé. (Age)"
	"Event - Last, First Year" = "évé. - Nom, Prénom (Age)"
	"Event - First Last Year" = "évé. - Prénom  Nom (Age)"
	"First Last Year" = "Prénom Nom (Age)"
	
	"Processing" = "Traitement"
	"Processed : " = "Traité(s) : "	

	"%d day(s) passed" = "%d jours(s) écoulé(s)"
	"Name" = "Nom"
	"Date" = "Date"
	"Age" = "Age"
	"HappyDays" = "HappyDays"
	"GPL free software" = "Logiciel gratuit GPL"
	"E-Mail & Web Page" = "E-Mail et Page Web"
END
