TRANSLATION "GERMAN"
BEGIN
    "Translator" = "Übersetzung: Gunther Zagatta"
    "Translator's email" = "zagatta@web.de"

    "long_notifySettingString" = ""\
      "* Einträge\n"\
      "Wählen Sie \"alle\" wenn im Kalender Einträge für "\
      "alle Ereignisse dieser Kategorie erzeugt werden sollen. "\
      "Wählen Sie \"Auswahl\" wenn nur die ausgewählten Ereignisse berücksichtigt werden "\
      "sollen.\n\n"\
      "* Vorhandene\n"\
      "Wählen Sie \"lassen\" wenn existierende HappyDays Einträge unberührt bleiben sollen. "\
      "Wählen Sie \"ändern\" wenn diese Einträge geändert werden sollen.\n\n"\
      "* Privat\n"\
      "Erzeugt private Termine für die gewählten Ereignisse.\n\n"\
      "* Alarm\n"\
      "Erzeugt zusammen mit dem Eintrag einen Alarm. Geben Sie die "\
      "Anzahl Tage an, die Sie vor dem Ereignis informiert werden wollen.\n\n"\
      "* Uhrzeit\n"\
      "Uhrzeit des Alarms\n\n"\
      "* Wiederholung\n"\
      "Gibt an, wie oft das Ereignis wiederholt werden soll. "\
      "Dabei bedeutet (-1) für den Gregorianischen Kalender unbegrenzt, "\
      "für den Lunarkalender 5 Jahre.\n\n"

    "long_notifySettingMoreString" = ""\
      "Die AN Icon Nummer schlagen Sie bitte im ActionNames Handbuch nach. "\
      "DateBk3 Icons werden aus dem entsprechenden Merkzettel gelesen. "\
      "Wenn Sie keinen DATEBK3 Merkzettel haben, werden auch keine Icons angezeigt.\n"

    "long_customErrorString" = ""\
      "'Geburtstag' ist der Default Benutzerfeld-Name."\
      "Wenn Sie diesen ändern wollen, tippen Sie 'Einstellungen'.\n\n"\
      "WICHTIG: Sie müssen den Kalender aufrufen und mit 'Optionen/"\
      "Benutzerfelder...' ein Benutzerfeld in 'Geburtstag' umbenennen"\
      " oder einen anderen Namen entsprechend Ihren Einstellungen für HappyDays.\n"

    "long_aboutString" = ""\
      "'HappyDays' hilft Ihnen, Geburtstage und ähnliche Ereignisse Ihrer Freunde "\
      "und Verwandten im Überblick zu behalten.\n\n"\
      "Benennen sie eines der Benutzerfelder im Adreßbuch 'Geburtstag'."\
      "\n\nBeispiel:\n"\
      " Nachname: Jeong\n"\
      " Vorname: JaeMok\n"\
      " ...\n"\
      " Geburtstag: -)4.12.1970\n\n"\
      "Formate:\n"\
      " [-)|#)]Datum\n"\
      " -) für Lunarkalender-Datum\n"\
      " #) für Schaltmonat im Lunarkalender\n\n"\
      "Das Datumsformat wird aus den Systemeinstellungen gelesen, wobei Sie das "\
      "Jahr auch weglassen können. Jahreszahlen unter 100 werden dem 20. Jahrhundert zugeordnet. "\
      "Wenn Sie unsicher sind bezüglich des Jahresformates, "\
      "schreiben Sie einfach das Jahrhundert mit dazu (z.B. 1970).\n\n"\
      "Zum Thema Mehrfach-Einträge lesen Sie bitte die Anleitung.\n"

    "long_cleanupAlertString" = ""\
      "Einträge werden als HappyDays Ereignis angenommen, wenn sie in der Notiz "\
      "die HappyDays ID enthalten. Wenn Sie diese auch in Ihren eigenen Einträgen "\
      "verwenden, werden diese ebenfalls entfernt.\n"

    "long_prefFormString" = ""\
      "* Statt System-Datumsformat\n"\
      "Wenn Sie für Geburtstage ein anderes Datumsformat in Ihrem Adreßbuch verwenden "\
      "als das Systemformat, können Sie dieses entsprechend einstellen\n\n"\
      "* Notiz auswerten\n"\
      "Geburtstage und Ereignisse werden auch aus dem Notizfeld gelesen\n\n"\
      "* Lunardatum zeigen\n"\
      "Eine gestrichelte Linie wird unter Lunarkalender-Daten gezeichnet\n\n"\
      "* Eintrag-Format\n"\
      "Hier können Sie das Aussehen der Kalender- bzw. Aufgaben-Einträge wählen\n\n"\
      "* Benutzerfeld\n"\
      "Name des Benutzerfelds im Adreßbuch, aus dem Geburtstage übernommen werden\n\n"\
      "* HappyDays ID\n"\
      "Wird beim Anlegen und Entfernen von HappyDays Einträgen benutzt, um diese "\
      "zu identifizieren"

    "long_removeConfirmString" = ""\
      "Wollen Sie wirklich alle HappyDays Einträge entfernen?"

    "long_sl2lnString" = ""\
      "-) bedeutet normaler Monat im Lunarkalender\n"\
      "#) bedeutet Schaltmonat im Lunarkalender"

    "long_cantFindAddrString" = ""\
      "Kein Benutzerfeld '%s' im Adreßbuch gefunden.\n"\
      "Bitte ein Benutzerfeld umbenennen."

    "Select Time" = "Zeit auswählen"
    "No Time" = "Keine"
    "Invalid input date" = "Ungültige Datumseingabe"
    "Export to Memo Pad is completed." = "Merkzettel Export beendet."

    "SUN"   = "SON"
    "MON"   = "MON"
    "TUE"   = "DIE"
    "WED"   = "MIT"
    "THU"   = "DON"
    "FRI"   = "FRE"
    "SAT"   = "SAM"

    "Not enough memory" = "Nicht genug Speicher"
    "%d notify entry is created.\n" = "%d Einträge erzeugt.\n"
    "%d existing entry " = "%d bestehende Einträge "
    "is kept untouched." = "belassen."
    "is modified." = "geändert."

    "Could not write prefs." = "Einstellungen konnten nicht gespeichert werden."
    "Collecting Information..." = "Daten werden eingelesen..."

    "HappyDays List" = "HappyDays Liste"
    "Look Up:" = "Gehe zu:"

	"HappyDays View" = "HappyDays Ereignis"
    "Done"  = "Fertig"
    "DB" = "Kal"
    "TD" = "Aufg"
    "Goto" = "Gehe zu"

    "Utilities" = "Eintrag"
    "Date Book Notify" = "Termine erzeugen"
    "Cleanup Date Book"  = "Termine entfernen"
    "To Do Notify" = "Aufgaben erzeugen"
    "Cleanup To Do"  = "Aufgaben entfernen"
    "Export to Memo Pad" = "Merkzettel exportieren"
    "Solar to Lunar" = "Gregor. -> Lunar"
    "Lunar to Solar" = "Lunar -> Gregor."

    "Options" = "Optionen"
    "Preferences" = "Einstellungen"
    "About HappyDays" = "Über HappyDays"

    "Edit" = "Bearb."
    "Undo" = "Rückgängig"
    "Cut" = "Ausschneiden"
    "Copy" = "Kopieren"
    "Paste" = "Einfügen"
    "Select All" = "Alles auswählen"
    "Keyboard" = "Tastatur"
    "Graffiti" = "Graffiti-Hilfe"

    "HappyDays Preferences" = "HappyDays Einstellungen"
    "Custom field:" = "Benutzerfeld:"
    "HappyDays ID:" = "HappyDays ID:"
    "Emphasize Lunar Date" = "Lunardatum zeigen"

    "OK" = "OK"
    "Cancel" = "Abbruch"

    "Solar to Lunar Convert" = "Gregor. -> Lunar"
    "Enter Solar date:" = "Gregor. Datum eingeben:"
    "Year must be in 1881-2043" = "Jahr muß zw. 1881 und 2043 liegen"
    "Result Lunar date:" = "Ergebnis Lunar-Datum:"

    "Convert" = "Rechnen"

    "Lunar to Solar Convert" = "Lunar -> Gregor."
    "Enter Lunar date:" = "Lunar-Datum eingeben:"
    "Leap" = "Schaltmon."
    "Result Solar date:" = "Ergebnis Gregor. Datum:"

    "Records:" = "Einträge:"
      "all" = "alle"
      "selected" = "Auswahl"
    "Existing:" = "Vorhandene:"
      "keep" = "lassen"
      "modify" = "ändern"
    "Priority:" = "Priorität:"
	"Category:" = "Kategorie:"
    "Private:" = "Privat:"
    "Alarm:" = "Alarm:"
    "Time:" = "Uhrzeit:"
    "More..." = "Mehr..."

    "Repeat for:" = "Wiederholung:"
    "years" = "Jahr(e)"

    "HappyDays says" = "HappyDays meldet"

    "HappyDays Export" = "HappyDays Export"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
      "Möchten Sie die HappyDays Liste als Merkzettel exportieren?"

    "Custom Field Error" = "Benutzerfeld Fehler"
    "Help" = "Hilfe"


    "HappyDays Cleanup" = "Einträge entfernen"

    "Notify warning" = "Warnung"
    "^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
      "^1: Möchten Sie wirklich Einträge für ^2 HappyDays Ereignis(se) erzeugen?"

    "Invalid event format" = "Ungültiges Ereignis-Format"

    "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
      "Der Adreßeintrag für ^1\nenthält ein ungültiges Ereignis. Was soll geschehen?"

    "Ignore" = "Ignorieren"
    "Ignore all" = "Alle Ignor."

    "Cleanup Done" = "Aufräumen beendet"

    "^1: ^2 HappyDays notify entries removed." = ""\
      "^1: ^2 HappyDays Einträge gelöscht."

    "Birthday" = "Geburtstag"
    "All" = "Alle"
    "HappyDays Export List" = "HappyDays Export Liste"
    "(not exist in this year)" = "(in diesem Jahr nicht vorhanden)"
    "Please run Date Book once first." = "Bitte vorher den Kalender einmal aufrufen."
    
    "Instead of system date format" = "Statt System-Datumsformat"
    "Use" = "Verwenden"
    "M/D/Y" = "M/T/J"
    "D/M/Y" = "T/M/J"
    "D.M.Y" = "T.M.J"
    "D-M-Y" = "T-M-J"
    "Y/M/D" = "J/M/T"
    "Y.M.D" = "J.M.T"
    "Y-M-D" = "J-M-T"

    "Date Book Icon" = "Erweiterte Einstellungen"
      "Icon Support" = "Icons verwenden"
	  "AN" = "AN"
	  "DateBk3" = "DBk3"
      "AN Icon Number:" = "AN Icon Nummer:"
      "DateBk3 Icon:" = "DateBk3 Icon:"

    "Days" = "Tage"
	"Date Book" = "Kalender"
	"To Do" = "Aufgaben"
	"Scan note field" = "Notiz auswerten"
    "%d day(s) left" = "Noch %d Tag(e)"
	"%d day(s) passed" = "Vor %d Tag(en)"
	"Notify Format:" = "Eintrag-Format:"
    "[Last, First] E(1) Year" = "[Nachn., Vorn.] E(1) Jahr"
	"[First Last] E(1) Year" = "[Vorn. Nachn.] E(1) Jahr"
	"Event - Last, First Year" = "Ereign. - Nachn., Vorn. Jahr"
	"Event - First Last Year" = "Ereign. - Vorn. Nachn. Jahr"
	"First Last Year" = "Vorn. Nachn. Jahr"
	
	"Processing" = "Arbeite"
	"Processed : " = "Bearbeitet : "

END
