TRANSLATION "KOREAN"
BEGIN
    "Translator" = "한글 버젼"
    "Translator's email" = ""

    "long_notifySettingString" = ""\
    "* 레코드\n"\
    "선택된 분류에 있는 모든 이벤트를 일정관리로 옮기고 싶은 경우에는 "\
    "'전부'를 누르세요. 선택된 레코드만을 옮기고 싶은 경우에는 "\
    "'선택'을 누르세요.\n\n"\
    "* 존재하는 레코드\n"\
    "존재하는 HappyDays 항목을 유지하고 싶은 경우에는 '유지'를, "\
    "수정하고 싶은 경우에는 '수정'을 누르세요.\n\n"\
    "* 개인용\n"\
    "알림 설정할 일정관리 항목을 '개인용'으로 만들고 싶을 때 선택.\n\n"\
    "* 알람\n"\
    "일정관리 항목에 알람을 설정. 몇 일전에 알람이 울릴지 설정.\n\n"\
	"* 시간\n"\
	"일정관리 항목의 시간을 설정.\n\n"\
    "* 몇 년간\n"\
    "몇 년에 걸쳐 알림 레코드를 만들것인가를 설정. "\
    "-1을 입력한 경우에는 양력의 경우 '영원히'를, 음력인 경우엔 "\
    "편의상 5년간 반복하여 레코드를 만든다.\n"

	"long_notifySettingMoreString" = ""\
	"AN 사용자는 Action Names 매뉴얼을 참조하여 숫자를 입력하면 됨. "\
	"DateBk3 아이콘은 메모장으로부터 읽어서 화면에 표시합니다. 메모장에 "\
	"아이콘 데이터가 없는 경우에는 아무것도 표시되지 않습니다.\n"

    "long_customErrorString" = ""\
    "'Birthday'가 초기 사용자정의 필드 이름입니다."\
    "다른 이름을 설정하고 싶은 경우 "\
    "'설정'을 누르세요.\n\n"\
    "정보: 'Birthday' 사용자정의 필드를 바꾸기 위해서는 주소록을 수행시켜 "\
    "'Options/Rename Custom Fields'을 선택한 다음 수정하면 됩니다."\
    "혹은 HappyDays의 설정 항목의 사용자정의 필드를 적절하게 수정하세요.\n"

    "long_aboutString" = ""\
    "'HappyDays'는 친구나 가족의 생일이나 기념일을 기억하는 것을 도와"\
    "줍니다. 더욱이 제사나 다른 이벤트 항목도 관리할 수 있습니다.\n\n"\
    "주소록의 사용자정의 필드중 하나를 'Birthday'로 수정하세요."\
    "\n\n예:\n"\
    " Last Name: 정\n"\
    " First name: 재목\n"\
    " ...\n"\
    " Birthday: -)12/4/70\n\n"\
    "형식:\n"\
    " [-)|#)]날짜\n"\
    " -) 음력 평달\n"\
    " #) 음력 윤달\n\n"\
    "날짜 형식은 시스템 설정화일에서 자동으로 읽어옵니다. 그러므로 "\
    "입력되는 날짜의 형식을 시스템과 일치시키세요. '년도' 부분은 생략"\
    "가능합니다. 년도가 100보다 적은 경우에는 19xx년대를 뜻합니다."\
    "확신이 들지 않는 경우 그냥 '1970'처럼 4자리로 입력하세요.\n\n"\
    "자세한 건 매뉴얼을 참조하세요.\n\n"\
	"HappyDays에서 출력하는 name1, name2는 AddressBook/Preferences의 "\
	"List by에 의해 결정됩니다.\n\n"\
	"HappyDays에서 사용되는 날짜 format은 Palm의 Global/Preferences/Format에 "\
	"의해 결정됩니다. M/D/Y 형태인 경우에는 2/12/00과 같이 출력되고 "\
	"D/M/Y의 경우 12/2/00과 같은 형태로 출력이 됩니다. 이 값은 설정메뉴에서 "\
	"수정할 수 있습니다.\n\n"\
	"그래피티 영역에 숫자를 쓴 경우 숫자에 해당하는 달의 HappyDays "\
	"레코드들이 선택되어 표시됩니다. 마찬가지로 'a'를 쓴 경우 'A'나 'a'로 "\
	"시작하는 레코드들이 선택됩니다.\n"

    "long_cleanupAlertString" = ""\
    "알림 레코드의 메모 필드에 {HD 식별자}가 있는 경우 "\
    "HappyDays 레코드로 "\
    "간주하고 삭제합니다. (주의 요망)\n"

    "long_prefFormString" = ""\
	"* 시스템 날짜 대신...\n"\
	"주소록의 Birthday 사용자 정의 필드에서 읽어오는 날짜 형식을 "\
	"어떻게 해석할지 결정합니다. 초기값은 시스템의 날짜 형식을 "\
	"사용합니다.\n\n"\
	"* 노트 필드 읽기\n"\
	"주소록의 노트 필드를 읽기 위해서, 이 옵션을 켜십시오. 노트 필드의 "\
	"입력 형식은 매뉴얼을 참조하세요.\n\n"\
    "* 음력강조\n"\
    "선택된 경우 음력생일 밑에 점선이 그어집니다.\n\n"\
	"* 알림 레코드 형식\n"\
	"알림 레코드를 만들 때 사용되는 기술형식.\n\n"\
    "* 사용자정의 필드\n"\
    "입력으로 사용되는 주소록의 사용자정의 필드 이름.\n\n"\
    "* HD 식별자\n"\
    "HappyDays 식별자. 알림과 레코드 정리에 사용.\n\n"

    "long_removeConfirmString" = ""\
    "모든 HappyDays 알림 항목을 삭제하길 원하십니까?"

    "long_sl2lnString" = ""\
        "-)는 음력 평달을 의미합니다.\n"\
        "#)은 음력 윤달을 의미합니다."

    "long_cantFindAddrString" = ""\
        "주소록에서 사용자정의 필드를 못 찾음: '%s'\n"\
        "주소록의 사용자정의 필드 항목 이름을 변경하세요."

    "Select Time" = "알람 시간"
    "No Time" = "지정안됨"
    "Invalid input date" = "날짜 입력이 잘못되었습니다."
    "Export to Memo Pad is completed." =
                "메모장으로 성공적으로 옮겨졌습니다."

    "SUN"   = "일"
    "MON"   = "월"
    "TUE"   = "화"
    "WED"   = "수"
    "THU"   = "목"
    "FRI"   = "금"
    "SAT"   = "토"

    "Not enough memory" = "메모리 부족"
    "%d notify entry is created.\n" =
        "%d 개의 알림 레코드가 생성되었습니다.\n"
    "%d existing entry " = "%d 개의 존재하는 레코드"
    "is kept untouched." = "를 그대로 유지했습니다."
    "is modified." = "가 수정되었습니다."

    "Could not write prefs." = ""\
        "설정화일 쓰기 오류"
    "Collecting Information..." = ""\
        "주소록으로부터 정보 수집중..."

    "HappyDays List" = "HappyDays 목록"
	"Look Up:" = "기준일:"

    "HappyDays View" = "HappyDays 보기"
    "Done"  = "완료"
    "DB" = "DB"
    "TD" = "TD"
    "Goto" = "이동"

    "Utilities" = "유틸리티 "
    "Date Book Notify" = "일정관리에 알림 "
    "Cleanup Date Book"  = "일정관리에서 정리 "
	"To Do Notify" = "할 일에 알림 "
	"Cleanup To Do"  = "할 일에서 정리 "
    "Export to Memo Pad" = "메모장으로 전송 "
    "Solar to Lunar" = "양력을 음력으로 "
    "Lunar to Solar" = "음력을 양력으로 "

    "Options" = "옵션 "
    "Preferences" = "설정 "
    "About HappyDays" = "HappyDays란? "

    "Edit" = "수정"
    "Undo" = "되돌리기"
    "Cut" = "자르기"
    "Copy" = "복사"
    "Paste" = "붙이기"
    "Select All" = "전체 선택"
    "Keyboard" = "키보드"
    "Graffiti" = "그래피티"

    "HappyDays Preferences" = "HappyDays 설정"
    "Custom field:" = "사용자정의 필드 :"
    "HappyDays ID:" = "HD 식별자 :"
    "Emphasize Lunar Date" = "음력강조"

    "OK" = "승인"
    "Cancel" = "취소"

    "Solar to Lunar Convert" = "양력을 음력으로 변환"
    "Enter Solar date:" = "양력 날짜는 :"
    "Year must be in 1881-2043" = "1881년에서 2043년까지만 지원"

    "Result Lunar date:" = "변환된 음력 날짜 :"

    "Convert" = "변환"

    "Lunar to Solar Convert" = "음력을 양력으로 변환"
    "Enter Lunar date:" = "음력 날짜는 :"
    "Leap" = "윤달"

    "Result Solar date:" = "변환된 양력 날짜 :"

    
    "Records:" = "레코드 :"
      "all" = "전부"
      "selected" = "선택"
    "Existing:" = "기존 레코드 :"
      "keep" = "유지"
      "modify" = "수정"
	"Priority:" = "우선순위 :"
	"Category:" = "카테고리 :"
    "Private:" = "개인용 :"
    "Alarm:" = "알람 :"
    "Time:" = "시간 :"
    "Icon" = "아이콘"

    "Repeat for:" = "몇 년간 :"
    "years" = "년"

    "HappyDays says" = "정 보"

    "HappyDays Export" = "HappyDays 전송"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
        "메모장으로 HappyDays 목록을 옮길까요?"

    "Custom Field Error" = "사용자정의 필드 에러"
    "Help" = "도움말"


    "HappyDays Cleanup" = "HappyDays 정리"

    "Notify warning" = "알림 경고"
	"^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
	"^1: ^2 개의 HappyDays에 대한 알림 레코드를 만들기 원하십니까?"

    "Invalid event format" = "잘못된 이벤트 포맷"

    "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
    "주소록 레코드 ^1\n의 포맷이 잘못되어 있습니다. 어떻게 처리할까요?"

    "Ignore" = "무시"
    "Ignore all" = "전부 무시"

    "Cleanup Done" = "정리작업 완료"

	"^1: ^2 HappyDays notify entries removed." = ""\
	"^1: ^2 개의 HappyDays 알림 레코드가 제거되었습니다."

	"(c) 1999-2001 JaeMok Jeong" = "(c) 1999-2001 정 재목"
    "GPL free software" = "GPL free software"
	"E-Mail & Web Page" = "이메일 & 웹페이지"

    "(not exist in this year)" = "(올해엔 없는 날입니다)"
    "Please run Date Book once first." = "먼저 일정관리를 한번 수행하세요."

    "Instead of system date format" = "시스템 날짜 형식 대신에"
    "Use" = "사용할 형식"
    "M/D/Y" = "M/D/Y"
    "D/M/Y" = "D/M/Y"
    "D.M.Y" = "D.M.Y"
    "D-M-Y" = "D-M-Y"
    "Y/M/D" = "Y/M/D"
    "Y.M.D" = "Y.M.D"
    "Y-M-D" = "Y-M-D"

	"Date Book Icon" = "아이콘 설정"
	"Icon Support" = "아이콘 지원"
	"AN Icon Number:" = "AN 아이콘 번호: "
	"DateBk3 Icon:" = "DateBk3 아이콘: "

    "Days" = "일전"
	"Date Book" = "일정관리"
	"To Do" = "할 일"
	"Scan note field" = "주소록의 노트 필드 읽기"
    "%d day(s) left" = "%d 일 남았습니다"
    "%d day(s) passed" = "%d 일 지났습니다"
	
	"Notify Format:" = "알림 레코드 형식: "
	"[Last, First] E(1) Year" = "[성, 이름] E(1) 나이"
	"[First Last] E(1) Year" = "[이름 성] E(1) 나이"
	"Event - Last, First Year" = "행사 - 성, 이름 나이"
	"Event - First Last Year" = "행사 - 이름 성 나이"
	"First Last Year" = "이름 성 나이"

	"Processing" = "진행중"
	"Processed : " = "처리된것 : "

	"Name" = "이름"
	"Date" = "생일"
	"Age" = "나이"

	"Address Book" = "주소록"
END
