TRANSLATION "CHINESE"
BEGIN
    "Translator" = "中文版 - 大头 ( 给 亚华 :-)"
    "Translator's email" = "daitau@hotmail.com"

    "long_notifySettingString" = ""\
      "* 纪录\n"\
      "假如要产生所有事件的提示，请选择'全部'"\
      "如只要产生被选事件的提示，请选择'已选'\n\n"\
      "* 现有的\n"\
      "假如不想修改现有的纪录，请选择'保留'，否则请选'修改'\n\n"\
      "* 响闹\n"\
      "使用 Date Book 内的响闹提示\n"\
      "可选择於多少天前提示\n\n"\
      "* 时间\n"\
      "设定事件的时间\n\n"\
      "* 重覆\n"\
      "表示要重覆多少年"\
      "假如设为 -1，阳历事件将每年重覆，阴历事件则重覆五年\n\n"

    "long_notifySettingMoreString" = ""\
      "关於 AN 图示编号，请参考 Action Names 说明书"\
      "DateBk3 图示将由 Memo Pad 处取得。"\
      "假如没有设定，则不会显示图示。\n"

    "long_customErrorString" = ""\
      "'Birthday' 为预设的自订栏目名称。你可於'喜好设定'中更改此名称\n\n"\
      "注意：你需先在 Address Book 内使用 'Options/Rename Custom Fields' "\
	  "以设定以上自订栏目名称\n"

    "long_aboutString" = ""\
      "'HappyDays' 能帮助你纪录每个重要事件的日期(例如你亲朋戚友的生日及周年纪念等)\n\n"\
      "请在 Address Book 内设定一个自订栏目为 'Birthday'。"\
      "\n\n例如:\n"\
      " 姓: 廖\n"\
      " 名: 大头\n"\
      " ...\n"\
      " Birthday: -)12/23/78\n\n"\
      "格式:\n"\
      " [-)|#)]日期\n"\
      " -) 代表阴历\n"\
      " #) 代表润月\n\n"\
      "日期格式则从系统设定中自动读取。"\
      "年份可省略。"\
      "少於 100 的年份会被当成二十世纪的日期，假如你不肯定，"\
      "请用 YYYY 的格式 (如 1970)\n\n"\
      "如要同时设定多项事件，请参考说明书。\n\n"\
      "在 HappyDays 中列出名字之姓/名次序，可在地 Address Book 内使用 "\
      "'Preferences/List By' 中更改。"\
      "至於日期格式则由 Prefs 中 Formats/Date 决定。\n\n"\
      "你可以在手写区中写要寻找名字的首个字母以快捷地搜寻。"\
      "你亦可以写月份来寻找该月之纪录。\n\n"

    "long_cleanupAlertString" = ""\
      "假如你选择清除，所有带有 HappyDays 记号 (包括你自己输入) 的日志将被清除\n"

    "long_prefFormString" = ""\
      "* 不使用系统日期格式\n"\
      "控制 HappyDays 如何读取 Address Book 内的日期格式\n\n"\
      "* Note栏目也包含事件资讯\n"\
      "使 HappyDays 读取 Note栏目\n\n"\
      "* 突显阴历事件\n"\
      "在阴历事件下加底线\n\n"\
      "* 提示格式\n"\
      "选择提示的格式\n\n"\
      "* 自订栏目\n"\
      "自订栏目的名称\n\n"\
      "* HappyDays 记号\n"\
      "用以提示及方便清理"

    "long_removeConfirmString" = ""\
      "你是否确定要清除所有 HappyDays 提示？"

    "long_sl2lnString" = ""\
      "-) 标示普通月份\n"\
      "#) 标示润月"

    "long_cantFindAddrString" = ""\
      "在 Address Book 中找不到 '%s' 栏目\n"\
      "请在 Address Book 内设定以上自订栏目名称\n"

    "Select Time" = "设定时间"
    "No Time" = "不指定时间"
    "Invalid input date" = "不正确的日期"
    "Export to Memo Pad is completed." = "完成 Memo Pad 汇出。"

    "SUN"   = "星期日"
    "MON"   = "星期一"
    "TUE"   = "星期二"
    "WED"   = "星期三"
    "THU"   = "星期四"
    "FRI"   = "星期五"
    "SAT"   = "星期六"

    "Not enough memory" = "记忆体不足"
    "%d notify entry is created.\n" = "产生了 %d 个提示。\n"
    "%d existing entry " = "%d 个提示 "
    "is kept untouched." = "被保留。"
    "is modified." = "被修改。"

    "Could not write prefs." = "不能储存设定。"
    "Collecting Information..." = "正在蒐集资讯，请稍候..."

    "HappyDays List" = "HappyDays 清单"
    "Look Up:" = "搜寻："

	"HappyDays View" = "HappyDays 检视"
    "Done"  = "完成"
    "DB" = "DateBk"
    "TD" = "Todo"
    "Goto" = "Addr"

    "Utilities" = "工具"
    "Date Book Notify" = "Date Book 提示"
    "Cleanup Date Book"  = "清理 Date Book"
    "To Do Notify" = "To Do List 提示"
    "Cleanup To Do"  = "清理 To Do List"
    "Export to Memo Pad" = "汇出到 MemoPad"
    "Solar to Lunar" = "阳历转阴历"
    "Lunar to Solar" = "阴历转阳历"

    "Options" = "选项"
    "Preferences" = "喜好设定"
    "About HappyDays" = "关於 HappyDays"

    "Edit" = "编辑"
    "Undo" = "复原"
    "Cut" = "剪下"
    "Copy" = "复制"
    "Paste" = "贴上"
    "Select All" = "全选"
    "Keyboard" = "键盘"
    "Graffiti" = "手写提示"

    "HappyDays Preferences" = "HappyDays 喜好设定"
    "Custom field:" = "自订栏目："
    "HappyDays ID:" = "HappyDays 记号："
    "Emphasize Lunar Date" = "突显阴历事件"

    "OK" = "确定"
    "Cancel" = "取消"

    "Solar to Lunar Convert" = "阳历转阴历"
    "Enter Solar date:" = "阳历："
    "Year must be in 1881-2043" = "年份须在 1881 - 2043 间"
    "Result Lunar date:" = "阴历："

    "Convert" = "转换"

    "Lunar to Solar Convert" = "阴历转阳历"
    "Enter Lunar date:" = "阴历："
    "Leap" = "润年"
    "Result Solar date:" = "阳历："

    "Records:" = "纪录："
      "all" = "全部"
      "selected" = "已选"
    "Existing:" = "现有的："
      "keep" = "保留"
      "modify" = "修改"
    "Priority:" = "重要性："
	  "Category:" = "类别："
    "Private:" = "私人的："
    "Alarm:" = "响闹："
    "Time:" = "时间："
    "More..." = "还有..."
    "Icon" = "图示"

    "Repeat for:" = "重覆："
    "years" = "年"

    "HappyDays says" = "HappyDays 说"

    "HappyDays Export" = "HappyDays 汇出"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
      "要将 HappyDays 的资料汇出 Memo Pad？"

    "Custom Field Error" = "自订栏目错误"
    "Help" = "说明"


    "HappyDays Cleanup" = "清理 HappyDays"

    "Notify warning" = "提示"
    "^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
      "^1: 你是否想建立 ^2 个 HappyDays 纪录的提示？"

    "Invalid event format" = "不正确的事件格式"

    "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
      "^1 的地址簿栏目\n 含有一个不合格式的事件，应怎处理？"

    "Ignore" = "略过"
    "Ignore all" = " 全部略过"

    "Cleanup Done" = "清理完毕"

    "^1: ^2 HappyDays notify entries removed." = ""\
      "^1: ^2 个 HappyDays 提示被清除了."

    "Birthday" = "生日"
    "All" = "所有"
    "HappyDays Export List" = "HappyDays 汇出列表"
    "(not exist in this year)" = "(本年度没有)"
    "Please run Date Book once first." = "请先执行 Date Book 一次"

    "Instead of system date format" = "不使用系统日期格式"
    "Use" = "改用"
/*
    "M/D/Y" = "月/日/年"
    "D/M/Y" = "日/月/年"
    "D.M.Y" = "日.月.年"
    "D-M-Y" = "日-月-年"
    "Y/M/D" = "年/月/日"
    "Y.M.D" = "年.月.日"
    "Y-M-D" = "年-月-日"
*/

  "Icon Support" = "图示支援"
  "AN" = "AN"
	"DateBk3" = "DBk3"
  "AN Icon Number:" = "AN 图示编号："
  "DateBk3 Icon:" = "DateBk3 图示："

  "Days" = "日"
	"Date Book" = "Date Book"
	"To Do" = "To Do"
	"Scan note field" = "Note 栏目也包含事件资讯"
  "%d day(s) left" = "尚余%d日"
  "%d day(s) passed" = "已经过了%d日"

	"Notify Format:" = "提示格式:"
  "[Last, First] E(1) Year" = "[姓, 名] E(1) 年"
	"[First Last] E(1) Year" = "[名 姓] E(1) 年"
	"Event - Last, First Year" = "事件 - 姓，名 年"
	"Event - First Last Year" = "事件 - 名 姓 年"
	"First Last Year" = "名 姓 年"

	"Processing" = "处理中"
	"Processed : " = "处理了："

/* new in 1.40 */
  "GPL free software"="GPL 自由软体"
  "E-Mail & Web Page"="电邮及网址"
  "Name"="姓名"
  "Date"="日期"
  "Age"="岁"
  "%d day(s) passed"="过了 %d 天"
END




