TRANSLATION "SPANISH"
BEGIN
    "Translator" = "Juan Fernando Calderón"
    "Translator's email" = "jfcalderon@usa.net"

    "long_notifySettingString" = ""\
    "* Registros\n"\
      "Seleccione \"Todos\" para crear notificaciones de "\
      "todos los eventos en esta categoría. "\
      "Selecione \"Marcado\" para notificar solamente el registo "\
      "actual.\n\n"\
      "* Existente\n"\
      "Seleccione \"Dejar\" si no desea alterar las notificaciones existentes. "\
      "Seleccione \"Cambiar\" para modificar las notificaciones.\n\n"\
      "* Alarma\n"\
      "Para colocar la hora de alarma en la notificación. Indique "\
      "el número de días de anticipación para la notificación.\n\n"\
      "* Hora\n"\
      "Hora del evento.\n\n"\
      "* Repetir\n"\
      "Establece el intervalo de la notificación. "\
      "Utilice -1 para repetir siempre en eventos solares y "\
      "repetir por 5 años en eventos lunares.\n\n"

	"long_notifySettingMoreString" = ""\
      "Para el número de icono de Action Names consulte su manual. "\
      "Los iconos de DateBk3 son leídos del bloc de notas. "\
      "Si no existe la entrada de DateBk3 en el bloc de notas no se muestra información.\n"

    "long_customErrorString" = ""\
    "'Nacimiento' es el nombre personalizado por omisión."\
    "Para establecer un campo personalizado diferente"\
    " seleccione 'Preferencias'.\n\n"\
    "IMPORTANTE: Necesitará utilizar Direcciones y seleccionar 'Opciones/"\
    "Nombre campos pers...' para cambiar un campo personalizado a 'Nacimiento'"\
    " o lo que desee establecer como nombre en las Preferencias de "\
    "HappyDays.\n"

    "long_aboutString" = ""\
      "'HappyDays' le ayudará a recordar los cumpleaños y aniversarios "\
      "de sus amigos y familiares, así como otros eventos.\n\n"\
      "Use uno de los campos personalizados de la Agenda y renombrelo como 'Nacimiento'."\
      "\n\nEjemplos:\n"\
      " Apellidos: Jeong\n"\
      " Nombre: JaeMok\n"\
      " ...\n"\
      " Nacimiento: -)12/4/1970\n\n"\
      "Formatos:\n"\
      " [-)|#)]Fecha\n"\
      " -) calendario lunar\n"\
      " #) calendario lunar bisiesto\n\n"\
      "Se utiliza el formato de fecha de las preferencias del sistema. "\
      "El año puede omitirse. Si escribe un año menor a 100 se asume del siglo 20. "\
      "Si no está seguro del formato de año, escribalo en la forma AAAA (como 1970).\n\n"\
      "Para entradas múltiples consulte el manual.\n"

    "long_cleanupAlertString" = ""\
    "Las notificaciones se consideran HappyDays si tienen "\
	"{Ident. HappyDays} en el campo Nota. "\ 	
    "Si usa este formato en sus propias entradas, "\
    "este registro puede ser eliminado por la Limpieza.\n"

    "long_prefFormString" = ""\
	"* Formato de fecha alternativo\n"\
	"Controla la interpretación del campo personalizado de Nacimiento. "\
	"Si se omite, es el mismo que las preferencias de fecha del sistema.\n\n"\
	"* Buscar en Notas\n"\
	"Seleccione esta opción para buscar en el campo de notas.\n\n"\
      "* Preferir Calendario Lunar \n"\
      "Si se selecciona, la linea punteada se dibuja junto a la fecha lunar.\n\n"\
	"* Formato de Notificación\n"\
	"La descripción del formato usado para la notificación.\n\n"\
      "* Campo pers:\n"\
      "El nombre del campo personalizado utilizado para los datos.\n\n"\
      "* Ident. HappyDays\n"\
      "Identificador utilizado para notificación y limpieza.\n"

    "long_removeConfirmString" = ""\
    "¿Desea eliminar todas las notificaciones "\
    "de HappyDays?"

    "long_sl2lnString" = ""\
        "-) significa mes lunar normal\n"\
        "#) significa mes lunar bisiesto"

    "long_cantFindAddrString" = ""\
    "No es posible encontrar campo personalizado: '%s'\n"\
    "Por favor renombre un campo personalizado en su Lista de Direcciones."

    "Select Time" = "Establecer hora"
    "No Time" = "Sin hora"
    "Invalid input date" = "Fecha inválida"
    "Export to Memo Pad is completed." = "Exportación a Bloc de notas lista."

    "SUN"   = "DOM"
    "MON"   = "LUN"
    "TUE"   = "MAR"
    "WED"   = "MIE"
    "THU"   = "JUE"
    "FRI"   = "VIE"
    "SAT"   = "SAB"

    "Not enough memory" = "Memoria Insuficiente"
    "%d notify entry is created.\n" = "%d notificaciones creadas.\n"
    "%d existing entry " = "%d notificaciones "
    "is kept untouched." = "sin modificar."
    "is modified." = "modificadas."

    "Could not write prefs." = "No se ha podido guardar preferencias."
    "Collecting Information..." = "Recolectando información..."

    "HappyDays List" = "Lista HappyDays"
    "Look Up" = "Buscar"
    "Today" = "Hoy"

    "HappyDays View" = "Detalles HappyDays"
    "Done"  = "Hecho"
    "DB" = "Agenda"
    "TD" = "Tareas"
    "Goto" = "Ir a"

    "Utilities" = "Utilerias"
    "Date Book Notify" = "Notificar en Agenda"
    "Cleanup Date Book"  = "Limpiar Agenda"
    "To Do Notify" = "Notificar en Tareas"
    "Cleanup To Do"  = "Limpiar Tareas"
    "Export to Memo Pad" = "Exportar a Bloc de notas"
    "Solar to Lunar" = "Solar -> Lunar"
    "Lunar to Solar" = "Lunar -> Solar"

    "Options" = "Opciones"
    "Preferences" = "Preferencias"
    "About HappyDays" = "Acerca de HappyDays"

    "Edit" = "Edición"
    "Undo" = "Deshacer"
    "Cut" = "Cortar"
    "Copy" = "Copiar"
    "Paste" = "Pegar"
    "Select All" = "Selec todo"
    "Keyboard" = "Teclado"
    "Graffiti" = "Ayuda de Graffiti"

    "HappyDays Preferences" = "Preferencias HappyDays"
    "Custom field:" = "Campo pers:"
    "HappyDays ID:" = "Ident. HappyDays:"
    "Emphasize Lunar Date" = "Preferir Calendario Lunar"

    "OK" = "Hecho"
    "Cancel" = "Cancelar"
    "Icon" = "Icono"

    "Solar to Lunar Convert" = "Solar -> Lunar"
    "Enter Solar date:" = "Indique la fecha Solar:"
    "Year must be in 1881-2043" = "El Año debe ser entre 1881 y 2043"
    "Result Lunar date:" = "Fecha Lunar resultado:"

    "Convert" = "Convertir"

    "Lunar to Solar Convert" = "Lunar -> Solar."
    "Enter Lunar date:" = "Indique la fecha Lunar:"
    "Leap" = "Bisiesto"
    "Result Solar date:" = "Fecha Solar resultado:"

    "Records:" = "Registros:"
      "all" = "Todos"
      "selected" = "Marcado"
    "Existing:" = "Existente:"
      "keep" = "Dejar"
      "modify" = "Cambiar"
    "Priority:" = "Prioridad:"
	"Category:" = "Categoría:"
    "Private:" = "Confidencial:"
    "Alarm:" = "Alarma:"
    "Time:" = "Hora:"
    "More..." = "Más..."

    "Repeat for:" = "Repetir:"
    "years" = "año(s)"

    "HappyDays says" = "HappyDays dice"

    "HappyDays Export" = "Exportar HappyDays"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
      "¿Desea exportar la lista HappyDays al Bloc de notas?"

    "Custom Field Error" = "Error en campo personalizado"
    "Help" = "Ayuda"


    "HappyDays Cleanup" = "Limpiar HappyDays"

    "Notify warning" = "Aviso"
    "^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
      "^1: ¿Está seguro que desea crear notificaciones de HappyDays para ^2 registros?"
      

    "Invalid event format" = "Formato de evento invalido."

    "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
      "El registro de agenda de ^1\n contiene un evento invalido. ¿Cómo desea proceder?"

    "Ignore" = "Ignorar"
    "Ignore all" = "Ignorar todos"

    "Cleanup Done" = "Limpieza concluida"

    "^1: ^2 HappyDays notify entries removed." = ""\
      "^1: ^2 notificaciones de HappyDays eliminadas."

    "(c) 1999-2000 JaeMok Jeong" = "(c) 1999-2000 JaeMok Jeong"
    "GPL free software" = "Software gratuito GPL"
	"E-Mail & Web Page" = "E-Mail & Página Web"

    "Birthday" = "Nacimiento"
    "All" = "Todos"
    "HappyDays Export List" = "Exportar Lista HappyDays"
    "(not exist in this year)" = "(no existe en este año)"
    "Please run Date Book once first." = "Por favor selecione la Agenda primero."
    
    "Instead of system date format" = "Formato de fecha alternativo"
    "Use" = "Usar"
    "M/D/Y" = "M/D/A"
    "D/M/Y" = "D/M/A"
    "D.M.Y" = "D.M.A"
    "D-M-Y" = "D-M-A"
    "Y/M/D" = "A/M/D"
    "Y.M.D" = "A.M.D"
    "Y-M-D" = "A-M-D"

    "Date Book Icon" = "Icono de Agenda"  
      "Icon Support" = "Soporte de Iconos"
      "AN" = "AN"  
      "DateBk3" = "DBk3"  
      "AN Icon Number:" = "Número Icono AN:"
      "DateBk3 Icon:" = "Icono DateBk3:"

    "Days" = "Días"
	"Datebook" = "Agenda"
	"To Do" = "Tareas"
	"Scan note field" = "Buscar en Notas"

    "%d day(s) left" = "%d días para el evento"  
    "%d day(s) passed" = "%d días transcurridos"


      "Notify Format:" = "Formato de Notificación:"
      "[Last, First] E(1) Year" = "[Apellido, Nombre] E(1) Año"
	"[First Last] E(1) Year" = "[Nombre Apellido] E(1) Año"
	"Event - Last, First Year" = "Evento - Apellido, Nombre Año"
	"Event - First Last Year" = "Evento - Nombre Apellido Año"
	"First Last Year" = "Nombre Apellido Año"

    
      "Processing" = "Procesando"
	"Processed : " = "Procesado : "	

      "Name" = "Nombre"
	"Date" = "Fecha"
	"Age"  = "Edad"

END
