TRANSLATION "THAI"
BEGIN
    "Translator" = "แปลโดย: กัปตัน เตียวตระกูล"
    "Translator's email" = "kteotrakool@hotmail.com"

    "long_notifySettingString" = ""\
    "* ระเบียน\n"\
    "แตะ 'ทั้งหมด' ถ้าต้องการเตือนทุกเหตุการณ์ที่อยู่ในหมวดนี้\n"\
    "แตะ 'ที่เลือก' ถ้าต้องการระเบียนที่เลือกเท่านั้น\n\n"\
    "* ที่มีอยู่\n"\
    "แตะ 'เก็บ' ถ้าไม่ต้องการแก้ไขรายการเตือนที่สร้างโดย HappyDays ที่มีอยู่แล้ว\n"\
    "แตะ 'เปลี่ยน' ถ้าต้องการแก้ไขเพิ่มเติมรายการเตือนที่สร้างโดย HappyDays ที่มีอยู่แล้ว\n\n"\
    "* เตือน\n"\
    "ตั้งเตือนใน DateBook ล่วงหน้าตามจำนวนวันที่กำหนด\n\n"\
    "* เวลา\n"\
    "เวลาเตือน\n\n"\
    "* ซํ้านาน\n"\
    "จำนวนปีที่ต้องการเตือน\n"\
    "-1 สำหรับสุริยคติจะเตือน\nตลอดไป และ"\
    "จะเตือนเป็นเวลา 5 ปีสำหรับจันทรคติ\n"

	"long_notifySettingMoreString" = ""\
	"ดูเลขไอคอน AN ในคู่มือ Action Names\n\nไอคอนของ DateBk3 อยู่ใน MemoPad "\
	"ถ้าไม่มีก็จะไม่เห็นอะไรปรากฏ\n"

    "long_customErrorString" = ""\
    "'Birthday' เป็นค่าเริ่มต้นของ custom field ที่ใช้โดย HappyDays "\
    "ถ้าต้องการเปลี่ยน ให้ไปที่ตั้งค่าตัวเลือก\n\n"\
    "สำคัญ: ถ้าต้องการแก้ไข\ncustom field ใน AddressBook "\
    "เลือก 'Options/Rename Custom Fields' แล้วแก้เป็น 'Birthday' "\
    "หรือเหมือนกับ custom field ในตัวเลือกของ HappyDays"

    "long_aboutString" = ""\
    "'HappyDays' ใช้สำหรับเตือน\nวันเกิดและวันครบรอบต่างๆ ของเพื่อนและครอบครัว "\
    "รวมถึงเหตุการณ์พิเศษอื่นๆ"\
    "\n\nแก้ custom field อันใดอันหนึ่งใน AddressBook ให้เป็น 'Birthday'"\
    "\n\nตัวอย่าง:\n"\
    " Last Name: Jeong\n"\
    " Name: JaeMok\n"\
    " ...\n"\
    " Birthday: -)12/4/70\n\n"\
    "รูปแบบ:\n"\
    " [-)|#)]วันที่\n"\
    " -) คือวันที่ตามจันทรคติใน\n\tเดือนปกติ\n"\
    " #) คือวันที่ตามจันทรคติใน\n\tเดือนอธิกมาส\n\n"\
    "รูปแบบวันที่จะใช้เหมือนกับที่ตั้งไว้ในค่าตัวเลือกของ\nระบบ สามารถละปีได้\n"\
    "ถ้าปีที่ใส่น้อยกว่า 100 จะถือเป็นปีในศตวรรษที่ 20 (19xx)"\
    "ถ้าไม่แน่ใจ ให้เขียนโดยใช้รูปแบบ YYYY (ต.ย. 1970)\n\n"\
    "ถ้าต้องการใส่หลายเหตุการณ์ โปรดอ่านคู่มือ\n"

    "long_cleanupAlertString" = ""\
    "รายการเตือนของ HappyDays จะมี "\
	"{HappyDays ID} ในโน้ต "\ 	
    "ถ้าคุณใช้รูปแบบดังกล่าวในรายการเตือนอื่น "\
    "รายการเหล่า\nนั้นอาจถูกลบด้วยเช่นกัน\n"

    "long_prefFormString" = ""\
	"* ไม่ใช้รูปแบบวันที่ตามระบบ...\n"\
	"บังคับการแปลความหมาย\nของ custom field สำหรับ Birthday ใน AddressDB\n"\
	"โดยปกติ รูปแบบวันที่ที่ใช้จะเหมือนกับที่ตั้งไว้ในค่าตัว\nเลือกของระบบ\n\n"\
	"* สแกนใน note\n"\
	"ถ้าเลือก จะสแกนหาข้อมูลใน note ของ Address Book\n\n"\
    "* ขีดเส้นเน้นจันทรคติ\n"\
    "ถ้าเลือก จะขีดเส้นประใต้วันที่ที่เป็นจันทรคติ\n\n"\
	"* รูปแบบที่ใช้เตือน\n"\
	"รูปแบบรายการเตือน\n\n"\
    "* Custom field\n"\
    "ชื่อของ custom field ใน Address Book ที่ใช้เป็นข้อมูล\n\n"\
    "* HappyDays ID\n"\
    "ใช้สร้างและลบรายการเตือน\n"

    "long_removeConfirmString" = ""\
    "ต้องการลบ\nรายการเตือนที่สร้างโดย HappyDays หรือไม่?"

    "long_sl2lnString" = ""\
        "-) คือวันที่ตามจันทรคติใน\n\tเดือนปกติ\n\n"\
        "#) คือวันที่ตามจันทรคติใน\n\tเดือนอธิกมาส"

    "long_cantFindAddrString" = ""\
    "ไม่พบ custom field ที่เรียกว่า '%s'\n"\
    "กรุณาแก้ไข custom field ใน Address Book"

    "Select Time" = "เลือกเวลา"
    "No Time" = "ไม่กำหนดเวลา"
    "Invalid input date" = "วันที่ที่ใส่ไม่ถูกต้อง"
    "Export to Memo Pad is completed." = "ส่งข้อมูลไป Memo Pad เรียบร้อย"

    "SUN"   = "SUN"
    "MON"   = "MON"
    "TUE"   = "TUE"
    "WED"   = "WED"
    "THU"   = "THU"
    "FRI"   = "FRI"
    "SAT"   = "SAT"

    "Not enough memory" = "หน่วยความจำไม่พอ"
    "%d notify entry is created.\n" = "%d รายการใหม่\n\tได้ถูกสร้างขื้น\n"
    "%d existing entry " = "%d รายการที่มีอยู่\n\t"
    "is kept untouched." = "ไม่ได้ถูกเปลี่ยน"
    "is modified." = "ได้ถูกเปลี่ยน"

    "Could not write prefs." = "ไม่สามารถจัดเก็บค่าตัวเลือกได้"
    "Collecting Information..." = "กำลังรวบรวมข้อมูล..."

    "HappyDays List" = "HappyDays List"
    "Look up" = "ค้นหา"
    "Today" = "วันนี้"

	"HappyDays View" = "HappyDays View"
    "Done"  = "เสร็จ"
    "DB" = "DB"
    "TD" = "TD"
    "Goto" = "ไปที่"

    "Utilities" = "อุปกรณ์  "
    "Date Book Notify" = "เตือนใน DateBook"
    "Cleanup Date Book"  = "ลบเตือนใน Datebook"
    "To Do Notify" = "เตือนใน To Do"
    "Cleanup To Do"  = "ลบเตือนใน To Do"
    "Export to Memo Pad" = "ส่งข้อมูลไป Memo Pad"
    "Solar to Lunar" = "สุริยคติ -> จันทรคติ"
    "Lunar to Solar" = "จันทรคติ -> สุริยคติ"

    "Options" = "ตัวเลือก"
    "Preferences" = "ตั้งค่า"
    "About HappyDays" = "เกี่ยวกับ HappyDays"

    "Edit" = "แก้ไข"
    "Undo" = "กลับคืน"
    "Cut" = "ตัด"
    "Copy" = "คัดลอก"
    "Paste" = "แปะ"
    "Select All" = "เลือกทั้งหมด"
    "Keyboard" = "แป้นพิมพ์"
    "Graffiti" = "วิธีเขียนกราฟฟิตี"

    "HappyDays Preferences" = "ตั้งค่าตัวเลือก HappyDays"
    "Custom field:" = "Custom field:"
    "HappyDays ID:" = "HappyDays ID:"
    "Emphasize Lunar Date" = "ขีดเส้นเน้นจันทรคติ"

    "OK" = "ตกลง"
    "Cancel" = "ยกเลิก"

    "Solar to Lunar" = "สุริยคติ -> จันทรคติ"
    "Lunar to Solar" = "จันทรคติ -> สุริยคติ"


    "Solar to Lunar Convert" = "สุริยคติ -> จันทรคติ"
    "Enter Solar date:" = "ใส่วันที่ตามสุริยคติ:"
    "Year must be in 1881-2043" = "ปีต้องอยู่ระหว่าง ค.ศ. 1881 - 2043"
    "Result Lunar date:" = "ผลวันที่ตามจันทรคติ:"

    "Convert" = "เปลี่ยน"

    "Lunar to Solar Convert" = "จันทรคติ -> สุริยคติ"
    "Enter Lunar date:" = "ใส่วันที่ตามจันทรคติ:"
    "Leap" = "อธิกมาส   "
    "Result Solar date:" = "ผลวันที่ตามสุริยคติ:"

    "Records:" = "ระเบียน:"
      "all" = "ทั้งหมด"
      "selected" = "ที่เลือก"
    "Existing:" = "ที่มีอยู่:"
      "keep" = "เก็บ"
      "modify" = "เปลี่ยน"
    "Priority:" = "ลำดับ:"
	"Category:" = "หมวด:"
    "Private:" = "ส่วนตัว:"
    "Alarm:" = "เตือน:"
    "Time:" = "เวลา:"
    "More..." = "ต่อ..."

    "Repeat for:" = "ซํ้านาน:"
    "years" = "ปี"

    "HappyDays says" = "HappyDays Message"

    "HappyDays Export" = "HappyDays Export"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
      "ต้องการส่งข้อมูลใน HappyDays List ไป Memo Pad หรือไม่?"

    "Custom Field Error" = "Custom Field Error"
    "Help" = "วิธีใช้"


    "HappyDays Cleanup" = "HappyDays Cleanup"

    "Notify warning" = "คำเตือน"
    "^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
      "^1: ต้องการให้ HappyDays สรัาง\nรายการเตือน\n^2 รายการหรือไม่?"

    "Invalid event format" = "รูปแบบไม่ถูกต้อง"

    "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
      "ระเบียนใน Address ของ\n^1\nมีรูปแบบไม่ถูกต้อง\nต้องการแก้ไขหรือไม่?"

    "Ignore" = "ทิ้งไว้"
    "Ignore all" = "ทิ้งไว้ทั้งหมด"

    "Cleanup Done" = "ลบเสร็จเรียบร้อย"

    "^1: ^2 HappyDays notify entries removed." = ""\
      "^1: ลบ ^2 รายการที่สร้างโดย HappyDays เสร็จเรียบร้อย"

    "Birthday" = "Birthday"
    "All" = "All"
    "HappyDays Export List" = "HappyDays Export List"
    "(not exist in this year)" = "(not exist in this year)"
    "Please run Date Book once first." = "โปรดใช้ DateBook ก่อน 1 ครั้ง"
    
    "Instead of system date format" = "ไม่ใช้รูปแบบวันที่ตามระบบ"
    "Use" = "ใช้"
    "M/D/Y" = "ด/ว/ป"
    "D/M/Y" = "ว/ด/ป"
    "D.M.Y" = "ว.ด.ป"
    "D-M-Y" = "ว-ด-ป"
    "Y/M/D" = "ป/ด/ว"
    "Y.M.D" = "ป.ด.ว"
    "Y-M-D" = "ป-ด-ว"

	"DateBook Notify More" = "เตือนใน DateBook (ต่อ)"
      "Icon Support" = "สนับสนุนไอคอน       "
	  "AN" = "AN"
	  "DateBk3" = "DBk3"
      "AN ICON Number:" = "เลขไอคอนใน AN:   "
      "DateBk3 ICON:" = "ไอคอนใน DateBk3:"

    "Days" = "วัน"
	"Date Book" = "Date Book"
	"To Do" = "To Do"
	"Scan note field" = "สแกนใน note      "
	
	"Notify Format:" = "รูปแบบที่ใช้เตือน:"
    "[Last, First] E(1) Year" = "[นามสกุล, ชื่อ] E(1) อายุ"
	"[First Last] E(1) Year" = "[ชื่อ นามสกุล] E(1) อายุ"
	"Event - Last, First Year" = "Event - นามสกุล, ชื่อ อายุ"
	"Event - First Last Year" = "Event - ชื่อ นามสกุล อายุ"
	"First Last Year" = "ชื่อ นามสกุล อายุ"
	
	"Processing" = "กำลังโปรเซสข้อมูล"
	"Processed : " = "เสร็จแล้ว: "
END
