TRANSLATION "PORTUGUESE-BR"
BEGIN
	"long_notifySettingMoreString" = ""\
	"Para o numero do ícone AN, consulte o manual do Action Names. "\
	"o ícone do DateBk3 é lido a partir do Bloco de Notas. Se você não "\
	"tem um registro DateBk3 Icon no Bloco de Notas, nada será mostrado.\n"

    "long_customErrorString" = ""\
    "'Birthday' é o campo livre padrão."\
    "Para mudar o nome do campo livre, "\
    "selecione 'Preferências'.\n\n"\
    "IMPORTANTE: Você precisa lançar Contatos e selecionar 'Options/"\
    "Rename Custom Fields' para renomear o campo livre para 'Birthday' "\
    "ou o que você ajuste como nome do campo livre nas Preferências do "\
    "HappyDays.\n"

    "long_aboutString" = ""\
    "'HappyDays' ajudará você a lembrar os aniversários e comemorações "\
    " de seus amigos e familiares, bem como outros eventos.\n\n"\
    "Veja os arquivos index.html e manual.html para informações detalhadas "\
    "de como usar o HappyDays\n\n"\
    "HappyDays é distribuído de acordo com os termos gerais do GNU"\
    "Licença Pública versão 2.0.\n"

    "long_cleanupAlertString" = ""\
    "As entradas de notificação serão consideradas do HappyDays se "\
	"elas contiverem {HappyDays ID} nos seus campos de MEMO. "\ 	
    "Se você usa este formato nas suas entradas este "\
    "registro também poderá ser removido pela Limpeza.\n"

    "long_sl2lnString" = ""\
        "-) significa mês lunar normal\n"\
        "#) significa mês lunar bissexto"

    "long_cantFindAddrString" = ""\
    "Não foi possível encontra um campo livre: '%s'\n"\
    "Por favor renomeie um campo livre no seu Contatos."

    "Select Time" = "Selecionar Horário"
    "No Time" = "Sem Horário"
    "Invalid input date" = "Data Inválida"
    "Export to Memo Pad is completed." = "Exportação para o Bloco de Notas completa."

    "SUN"   = "DOM"
    "MON"   = "SEG"
    "TUE"   = "TER"    "WED"   = "QUA"
    "THU"   = "QUI"
    "FRI"   = "SEX"
    "SAT"   = "SAB"

    "Not enough memory" = "Memória insuficiente"
    "%d notify entry is created.\n" = "%d Notificações criadas.\n" 
    "%d existing entry " = "%d notificações "
    "is kept untouched." = "sem alterar."
    "is modified." = "alteradas."

    "Collecting Information..." = "Coletando informações..."

    "HappyDays List" = "Lista do HappyDays"
    "Look Up:" = "Procurar:"

    "HappyDays View" = "Visual. do Happydays"
    "Done"  = "Feito"
    "DB" = "DB" 
    "TD" = "TD"
    "Goto" = "Ir para"

    "Utilities" = "Utilitários"
    "Date Book Notify" = "Notificar na Agenda"
    "Cleanup Date Book"  = "Limpar Agenda"
    "To Do Notify" = "Notificar em Tarefas"
    "Cleanup To Do"  = "Limpar Tarefas"
    "Export to Memo Pad" = "Exportar para Bloco de Notas"
    "Solar to Lunar" = "Solar para Lunar"
    "Lunar to Solar" = "Lunar para Solar"
	"Rescan Address Book" = "Reexaminar Contatos"

    "Options" = "Opções"
	"Font..." = "Fonte..."
    "Preferences" = "Preferências"
	"Display Preferences" = "Mostrar Preferências"
    "About HappyDays" = "Sobre o HappyDays"

    "Edit" = "Editar"
    "Undo" = "Desfazer"
    "Cut" = "Reortar"
    "Copy" = "Copiar" 
    "Paste" = "Colar" 
    "Select All" = "Selecionar todos" 
    "Keyboard" = "Teclado" 
    "Graffiti" = "Graffiti"


/* Fonte... */

/* preferences screen */
    "Custom field:" = "Campo livre:"
    "Instead of system date format" = "Ao invés do form. de data do sistema"  
    "Use" = "Usar"  
    "M/D/Y" = "M/D/A"  
    "D/M/Y" = "D/M/A"  
    "D.M.Y" = "D.M.A"  
    "D-M-Y" = "D-M-A"  
    "Y/M/D" = "A/M/D"  
    "Y.M.D" = "A.M.D"  
    "Y-M-D" = "A-M-D"  
	"Address Autoscan" = "Auto-examinar Contatos"
	"Always" = "Sempre"
	"Ask" = "Perguntar"
	"Never" = "Nunca"

    "Notify Format:" = "Formato da Notificação:"  
    "[Last, First] E(1) Year" = "[Sobrenome, Nome] E(1) Ano"  
    "[First Last] E(1) Year" = "[Nome Sobrenome] E(1) Ano"  
    "Event - Last, First Year" = "Evento - Sobrenome, Nome Ano"  
    "Event - First Last Year" = "Evento - Nome Sobrenome Ano"  
    "First Last Year" = "Nome Sobrenome Ano"  

	"Address Book" = "Contatos"
	"Bulit-in" = "Built-in"


/* Display preferences */
    "Emphasize Lunar Date" = "Enfatize a Data Lunar"


/* About HappyDays */	
	"GPL free software" = "GPL software gratuito"
	"E-Mail & Web Page" = "E-Mail & Web Page"

    "Translator" = "Mauricio Montel"
    "Translator's email" = "maumontel@hotmail.com "


    "OK" = "OK"
    "Cancel" = "Cancelar"

    "Solar to Lunar Convert" = "Conversão de Solar para Lunar"
    "Enter Solar date:" = "Entre a data Solar:"
    "Year must be in 1881-2043" = "O ano deve ser entre 1881-2043"
    "Result Lunar date:" = "Data Lunar resultante:"

    "Convert" = "Converter"

    "Lunar to Solar Convert" = "Conversão de Lunar para Solar"
    "Enter Lunar date:" = "Entre a data Lunar:"
    "Leap" = "Bissexto"
    "Result Solar date:" = "Data Solar resultante:"


/* Date Book & To Do Notify */
    "Records:" = "Registros:"
      "all" = "todos"
      "selected" = "selecionados" 
    "Existing:" = "Existentes:"
      "keep" = "manter"
      "modify" = "modificar"
    "Priority:" = "Prioridade:"
    "Category:" = "Categoria:"
    "Private:" = "Confidencial:"
    "Alarm:" = "Alarme:"
    "Time:" = "Hora:"
    "Icon" = "Ícone"

    "Repeat for:" = "Repetir por:"
    "years" = "anos"

    "Notify warning" = "Aviso" 
	"long_notifywarningString" = ""\
  		"^1: Você tem certeza que gostaria de criar notificações para "\
		"^2 HappyDays registros?"      

/* Date Book Icon */
    "Date Book Icon" = " Ícones do Date Book "  
      "Icon Support" = " Suporte a Ícones "  
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "Número do ícone AN:"  
      "DateBk3 Icon:" = "Ícone do DateBk3:"  

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "Limpar HappyDays" 

    "long_removeConfirmString" = ""\
    "Você tem certeza que quer remover "\
    "todas as notificações do HappyDays?"



    "HappyDays says" = "HappyDays diz"

    "HappyDays Export" = "Exportar HappyDays"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
    	"Você gostaria de exportar a lista do HappyDays para o Bloco de Notas?"

    "Custom Field Error" = "Erro no Campo Livre"
    "Help" = "Ajuda"


    "Invalid event format" = "Formato de evento inválido" 

	"long_invalidformatString" = ""\
      "O registro de endereço\n[^1]\n contém um evento inválido. "\
            "Como você gostaria de resolver isto?" 

    "Ignore" = "Ignorar" 
    "Ignore all" = "Ignorar todos" 

    "Cleanup Done" = "Limpeza concluída" 
  
    "^1: ^2 HappyDays notify entries removed." = ""\
    	"^1: ^2 Notificações do HappyDays removidas." 

    "HappyDays Export List" = "Exportar Lista do HappyDays" 
    "(not exist in this year)" = "(não existe neste ano)" 
    "Please run Date Book once first." = "Por favor execute a Agenda primeiro."  

    "Days" = "Dias"  
    "Date Book" = "Agenda"  
    "To Do" = "Tarefas"  
    "Scan note field" = "Procurar em NOTA"  
    "%d day(s) left" = "%d dias(s) para o evento"  
    "%d day(s) passed" = "%d dia(s) passados"  

    "Processing" = "Processando"  
    "Processed : " = "Processado : " 

	"Address Change" = "Reexaminar Contatos"
	"Address DB is changed. \nDo you want to rescan it?"= ""\
		"Contatos DB foi modificada. \nVocê deseja reexaminá-lo?"

/* HappyDays view */
	"Type:" = "Tipo:"
	"Next Date:" = "Próxima Data:"
	"Origin:" = "Origem:"
	"Age:" = "Idade:"
	"UpTo Date:" = "Até a data:"
	"%dY %dM %dD (%ld)" = "%dA %dM %dD (%ld)"

	"Yes" = "Sim"
	"No" = "Não"
END


