TRANSLATION "CATALAN"
BEGIN
	"long_notifySettingMoreString" =  ""\
	"Aquesta nota la fan servir altres programes d'Agenda como ara "\
	"Action Names o  DateBk3/4.\n\n"\
	"Amb aquesta nota, podeu triar la icona, tipus de lletra i altres opcions.\n\n"\
	"Per a més informació, consulteu el seu manual.\n"

    "long_customErrorString" = ""\
    "'Naixement' és el nom personalitzat per omisió."\
    "Per a establir un camp personalitzat diferent"\
    " trieu 'Preferències'.\n\n"\
    "IMPORTANT: Haureu de fer servir Adreçes i seleccionar 'Opcions/"\
    "Nom dels camps pers...' per a canviar un camp personalitzat a 'Naixement'"\
    " o aquell nom que volgueu triar a les Preferències de "\
    "HappyDays.\n"

    "long_aboutString" = ""\
    "'HappyDays' os ajudará a recordar les dates claus i aniverssaris "\
    "dels vostres amics i familiars.\n\n"\
    "trobareu informació detallada sobre l'ús de HappyDays als arxius"\
    "index.html i manual.html\n\n"\
    "HappyDays es distribueix sota els termes de la GNU General "\
    "Public License versió 2.0.\n"

    "long_cleanupAlertString" = ""\
    "Les notificacions es consideren de HappyDays si tenen "\
	"{Ident. HappyDays} en el camp Nota. "\ 	
    "Si feu servir el mateis format a les vostres entrades, "\
    "la Neteja també les podria eliminar.\n"

    "long_sl2lnString" = ""\
        "-) significa mes lunar normal\n"\
        "#) significa mes lunar de traspàs"

    "long_cantFindAddrString" = ""\
    "A les Adreçes no hi cap camp personalitzat: '%s'\n"\
    "Si us plau canvieu el nom d'un camp personalitzat a les vostres Adreçes."

    "Select Time" = "Establir hora"
    "No Time" = "Sense hora"
    "Invalid input date" = "Data invàlida"
    "Export to Memo Pad is completed." = "S'ha acabat l'exportació al Bloc de notes."

    "SUN" =  "DIU"
    "MON" =  "DIL"
    "TUE" =  "DIM"
    "WED" =  "DIC"
    "THU" =  "DIJ"
    "FRI" =  "DIV"
    "SAT" =  "DIS"

    "Not enough memory" = "Memòria insuficient"
    "%d notify entry is created.\n" = "%d notificacions creades.\n"
    "%d existing entry " = "%d notificacions "
    "is kept untouched." = "sense modificar."
    "is modified." = "modificades."

    "Collecting Information" = "Recollint informació"

    "Look Up:" = "Cercar:"

    "HappyDays View" = "Detalls HappyDays"
    "Done"  = "Fet"
    "DB" = "Agenda" 
    "TD" = "Tasques"
    "Goto" = "Anar a"

    "Utilities" = "Eines"
    "Date Book Notify" = "Notificar a l'Agenda"
    "Cleanup Date Book"  = "Netejar l'Agenda"
    "To Do Notify" = "Notificar a les Tasques"
    "Cleanup To Do"  = "Netejar les Tasques"
    "Export to Memo Pad" = "Exportar al Bloc de notes"
    "Solar to Lunar" = "Solar a Lunar"
    "Lunar to Solar" = "Lunar a Solar"
	"Rescan Address Book" = "Rastrejar les adreçes"

    "Options" = "Opcions"
	"Font..." = "Tipus de lletra..."
    "Preferences" =  "Preferències"
	"Display Preferences"= "Mostra preferències"
    "About HappyDays" =  "Sobre HappyDays"

    "Edit" =  "Edició"
    "Undo" =  "Desfés"
    "Cut" =  "Talla"
    "Copy" =  "Copia"
    "Paste" =  "Enganxa"
    "Select All" =  "Seleccciona-ho tot"
    "Keyboard" =  "Teclat"
    "Graffiti" =  "Ajuda de Graffiti"


/* Font... */

/* preferences screen */
    "Custom field:" = "Camp personal.:"
    "Instead of system date format" = "Format de data alternatiu"  
    "Use" = "Usa"  
    "M/D/Y" = "M/D/A"  
    "D/M/Y" = "D/M/A"  
    "D.M.Y" = "D.M.A"  
    "D-M-Y" = "D-M-A"  
    "Y/M/D" = "A/M/D"  
    "Y.M.D" = "A.M.D"  
    "Y-M-D" = "A-M-D"  
	"Address Autoscan" = "Rastrejar adreçes"
	"Always" = "Sempre"
	"Ask" = "Preguntar-ho"
	"Never" = "Mai"

    "Notify Format:" = "Format de Notificació:"  
    "[Last, First] E(1) Year" =  "[Cognoms, Nom] R(1) Any"
    "[First Last] E(1) Year" =  "[Nom Cognoms] R(1) Any"
    "Event - Last, First Year" = "Registre - Cognoms, Nom Any"  
    "Event - First Last Year" = "Registre - Nom Cognoms Any"  
    "First Last Year" = "Nom Cognoms Any"  

    
	"Address Book:" = "Adreçes"
	"Built-in" = "Programari inclòs"

/* Display preferences */
    "Emphasize Lunar Date" = "Destaca el Calendari Lunar"

/* About HappyDays */	
	"GPL free software" = "Programari gratuit GPL"
	"E-Mail & Web Page" = "Correu i Pàgina Web"

    "Translator" = "Versió Catalana"
    "Translator's email" = "Paco Rivière"


    "OK" = "D'acord"
    "Cancel" = "Cancel·la"

    "Solar to Lunar Convert" = "Conversió de Solar a Lunar"
    "Enter Solar date:" =  "Indiqueu la data Solar:"
    "Year must be in 1881-2043" =  "L'any ha d'estar entre 1881 i 2043"
    "Result Lunar date:" =  "Data Lunar resultant:"

    "Convert" =  "Convertir"

    "Lunar to Solar Convert" =  "Conversió de Lunar a Solar."
    "Enter Lunar date:" =  "Indiqueu la data Lunar:"
    "Leap" =  "De traspàs"
    "Result Solar date:" =  "Data Solar resultant:"

/* Date Book & To Do Notify */
    "Records:" =  "Registres:"
      "all" =  "tots"
      "selected" =  "marcats"
    "Existing:" =  "Actuals:"
      "keep" =  "deixar-los"
      "modify" =  "canviar-los"
    "Priority:" = "Prioritat:"
    "Category:" = "Categoria:"
    "Private:" = "Confidencial:"
   "Alarm:" = "Alarma:"
   "Time:" = "Hora:"
    "Icon" = "Icona"

    "Repeat for:" =  "Repetir:"

    "years" =  "anys"

    "Notify warning" = "Notify warning" 
	"long_notifywarningString" = ""\
  		"^1: Segur que voleu crear notificacions de HappyDays per a "\
		"^2 registres?"
      
/* Date Book Icon */
    "Date Book Icon" = "Icona d'Agenda"  
      "Icon Support" = "Suport per a icones"  
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "Número de Icona d'AN:"  
      "DateBk3 Icon:" = "Icona de DateBk3:"  

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "Netejar HappyDays" 

    "long_removeConfirmString" = ""\
    "Segur que voleu eliminar totes "\
    "les notificacions de HappyDays?"


    "HappyDays says" = "HappyDays diu"

    "HappyDays Export" = "HappyDays Export"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
 	      "Desitjeu exportar la llista HappyDays al Bloc de notes?" 

    "Custom Field Error" = "Error en el camp personalitzat"
    "Help" = "Ajuda" 


    "Invalid event format" = "Format de registre invàlid." 

	"long_invalidformatString" = ""\
    	"El registre d'agenda de\n[^1]\n conté un registre invàlid. "\
		"Què voleu fer?"

    "Ignore" =  "Ignorar-lo"
    "Ignore all" =  "Ignorar-los tots"

    "Cleanup Done" = "Neteja acabada" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    	      "^1: ^2 notificacions de HappyDays eliminades."

    "HappyDays Export List" = "Exportar Llista de HappyDays" 
    "(not exist in this year)" = "(no existeix en aquest any)" 
    "Please run Date Book once first." = "Si us plau primer trieu l'Agenda."  
    
    "Days" = "Dies"  
    "Date Book" = "Agenda"  
    "To Do" = "Tasques"  
    "Scan note field" = "Cercar en les notes"  
    "%ld days left" = "falten %ld dies"  
    "%ld days passed" = "passen %ld dies"  

    "Processing" = "Processant"  
    "Processed : " = "Processat : " 

	"Address Change"= "Adreça canviada"
    "AddressDB is changed. \nDo you want to rescan it?"= "Les adreçes han canviat, \nVoleu rastrejar-les"

/* HappyDays view */
	"Type:" = "Tipus:"
	"Next Date:" = "Nova Data:"
	"Origin:" = "Origen:"
	"Age:" = "Edat:"
	"UpTo Date:" = "Actualitzat:"
	"%dY %dM %dD (%ld)" = "%dY %dM %dD (%ld)"

	"Yes" = "Sí"
	"No" = "No"
END

