TRANSLATION "CATALAN"
BEGIN
	"long_notifySettingMoreString" = ""\
	"Nomès per a usuaris avançats\n\n"\
	"Aquesta nota la fan servir programes d'agenda de tercers"\
	"com ara Action Names, DateBk3/4.\n\n"\
	"Podeu indicar una icona, lletra, i més opcions fent servir aquesta nota.\n\n"\
	"Per a més informació, consulteu el seu manual.\n"

    "long_aboutString" = ""\
    "'HappyDays' us ajudarà a recordar les dates claus i anniversaris "\
    "dels vostres amics i familiars.\n\n"\
    "Consulteu l'arxiu index.html i el manual.html on trobareu informació detallada "\
    "sobre l'ús de HappyDays\n\n"\
    "HappyDays es distribueix sota els termes de la GNU General "\
    "Public License versió 2.0.\n"

    "long_cleanupAlertString" = ""\
    "Els registres notificats es consideren de HappyDays si tenen "\
	"{HappyDays ID} en el seu camp de Notes. "\ 	
    "Si feu servir aquest format en els vostres propis "\
    "registres, es poden esborrar en fer la Neteja de HappyDays.\n"

    "long_sl2lnString" = ""\
        "-) significa mes lunar normal\n"\
        "#) significa mes lunar de traspàs"

    "Select Time" = "Establir hora"
    "No Time" = "Sense hora"
    "Invalid input date" = "Data no vàlida"
    "Export to Memo Pad is completed." = "S'ha acabat l'exportació al Bloc de notes."

    "SUN"   = "DIU"
    "MON"   = "DIL"
    "TUE"   = "DIM"
    "WED"   = "DIM"
    "THU"   = "DIJ"
    "FRI"   = "DIV"
    "SAT"   = "DIS"

    "Not enough memory" = "Memòria Insuficient"
    "%d notify entry have been created.\n" = "%d notificacions creades.\n"
    "%d existing entries " = "%d notificacions "
    "are kept untouched." = "sense modificar."
    "have been modified." = "modificades."

 	"%dth day" = "%d  dia"                
	"(%dth)" =  "(%d )"                             

    "Collecting Information" = "Reunint informació"

    "Look Up:" = "Cerca:"

    "HappyDays View" = "Detalls HappyDays"
    "Done"  = "Fet"
    "DB" = "Agenda"
    "TD" = "Tasques"
    "Goto" = "Anar a"

    "Utilities" = "Utilitats"
    "Date Book Notify" = "Notifica a l'Agenda"
    "Cleanup Date Book"  = "Neteja l'Agenda"
    "To Do Notify" = "Notifica a les Tasques"
    "Cleanup To Do"  = "Neteja les Tasques"
    "Export to Memo Pad" = "Exporta al Bloc de notes"
    "Solar to Lunar" = "Solar -> Lunar"
    "Lunar to Solar" = "Lunar -> Solar"
	"Rescan Address Book" = "Torna a cercar Adreces"

    "Options" = "Opcions"
	"Font..." = "Lletra..."
    "Preferences" = "Preferències"
	"Display Preferences" = "Mostra les Preferències"
    "About HappyDays" = "Sobre HappyDays"

    "Edit" = "Edició"
    "Undo" = "Desfés"
    "Cut" = "Retalla"
    "Copy" = "Còpia" 
    "Paste" = "Enganxa" 
    "Select All" = "Selecciona-ho tot" 
    "Keyboard" = "Teclat" 
    "Graffiti" = "Ajuda de Graffiti"


/* Font... */

/* preferences screen */
    "Custom field:" = "Camp personal:"
    "Instead of system date format" = "Format de data alternatiu"
    "Use" = "Usa"
    "M/D/Y" = "M/D/A"
    "D/M/Y" = "D/M/A"
    "D.M.Y" = "D.M.A"
    "D-M-Y" = "D-M-A"
    "Y/M/D" = "A/M/D"
    "Y.M.D" = "A.M.D"
    "Y-M-D" = "A-M-D"
	"Address Autoscan" = "Cerca les Adreces"
	"Always" = "Sempre"
	"Ask" = "Pregunta-ho"
	"Never" = "Mai"

      "Notify Format:" = "Format de Notificació:"
      "[Last, First] E(1) Year" = "[Cognoms, Nom] E(1) Any"
      "[First Last] E(1) Year" = "[Nom Cognoms] E(1) Any"
      "Event - Last, First Year" = "Registre - Cognoms, Nom Any"
      "Event - First Last Year" = "Registre - Nom Cognoms Any"
      "First Last Year" = "Nom Cognoms Any"

	"Address Book:" = "Llibreta d'Adreces:"
	"Built-in" = "Incloses"


/* Display preferences */
    "Emphasize Lunar Date" = "Destaca Data Lunar"


/* About HappyDays */	
	"GPL free software" = "Programari gratuït GPL"
	"E-Mail & Web Page" = "E-Mail & Web Page"

    "Translator" = "PalmCAT.org"
    "Translator's email" = "www.palmcat.org"


    "OK" = "D'acord"
    "Cancel" = "Anul·la"

    "Solar to Lunar Convert" = "Solar -> Lunar"
    "Enter Solar date:" = "Indiqueu la data Solar:"
    "Year must be in 1881-2043" = "L'any ha de ser entre 1881 i 2043"
    "Result Lunar date:" = "Data Lunar resultat:"

    "Convert" = "Convertir"

    "Lunar to Solar Convert" = "Lunar -> Solar."
    "Enter Lunar date:" = "Indiqueu la data Lunar:"
    "Leap" = "De traspàs"
    "Result Solar date:" = "Data Solar resultat:"


/* Date Book & To Do Notify */
    "Records:" = "Registres:"
      "all" = "tots"
      "selected" = "marcats"
    "Existing:" = "Actuals:"
      "keep" = "deixa'ls"
      "modify" = "canvia'ls"
    "Priority:" = "Prioritat:"
    "Category:" = "Categoria:"
    "Private:" = "Confidencial:"
    "Alarm:" = "Alarma:"
    "Time:" = "Hora:"
    "Icon" = "Icona"

    "Repeat for:" = "Repeteix:"
    "years" = "any(s)"

    "Notify warning" = "Avís"
	"long_notifywarningString" = "^1: Segur que voleu crear notificacions de HappyDays per a ^2 registres?"
      
    "Date Book Icon" = "Icona d'Agenda"  
      "Icon Support" = "Suport d'Icones"
      "AN" = "AN"  
      "DateBk3" = "DBk3"  
      "AN Icon Number:" = "Número d'Icona de AN:"
      "DateBk3 Icon:" = "Icona de DateBk3:"

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "Neteja" 

    "long_removeConfirmString" = "Desitjeu eliminar totes les notificacions "\
    "de HappyDays?"

    "HappyDays says" = "HappyDays diu"

    "HappyDays Export" = "Exportar HappyDays"
    "Would you like to export HappyDays List to Memo Pad?" = "¿Voleu exportar la Llista de HappyDays al Bloc de notes?"

    "Custom Field Error" = "Error en camp personalitzat"
    "Help" = "Ajuda" 


    "Invalid event format" = "Format de registre no vàlid"

	"long_invalidformatString" = "El registre d'agenda de ^1\n contè un registre no vàlid. "\
		"Què voleu fer?"

    "Ignore" = "Ignora'l" 
    "Ignore all" = "Ignora'ls tots" 

    "Cleanup Done" = "S'ha acabat la neteja" 

    "^1: ^2 HappyDays notify entries removed." = "^1: ^2 notificacions de HappyDays eliminades."

    "HappyDays Export List" = "Exportar la Llista de HappyDays"
    "(not exist in this year)" = "(aquest any no hi és)"
    "Please run Date Book once first." = "Si us plau trieu l'Agenda primer."
    
    "Days" = "Dies"  
    "Date Book" = "Agenda"  
    "To Do" = "Tasques"  
    "Scan note field" = "Cerca de les Notes"
    "%d day(s) left" = "%d dies per al registre"  
    "%d day(s) passed" = "%d dies transcorreguts"  

    "Processing" = "Processant"  
    "Processed : " = "Processat : " 

	"Address Change" = "Cerca de la llibreta d'Adreces"
	"Address DB is changed. \nDo you want to rescan it?" = "La llibreta d'Adreces ha canviat. \nVoleu tornar a cercar a la llibreta d'Adreces?"

 	"Ignore record with prefix '!'" = "Ignora el registre amb prefix '!'"
 	"Datebook note" = "Nota a l'Agenda"
 	"Add the following note" = "Afegeix la següent nota"

/* HappyDays view */
	"Type:" = "Tipus:"
	"Next Date:" = "Propera Data:"
	"Origin:" = "Origen:"
	"Age:" = "Edat:"
	"UpTo Date:" = "Actualitzat:"
	"%dY %dM %dD (%ld)" = "%dA %dM %dD (%ld)"

	"Yes" = "Si"
	"No" = "No"
END

 


