TRANSLATION "CHINESE"
BEGIN
    "long_notifySettingMoreString" = ""\
    "關於 AN 圖示編號，請參考 Action Names 說明書"\
    "DateBk3 圖示將由記事本處取得。"\
    "假如沒有設定，則不會顯示圖示。\n"

    "long_customErrorString" = ""\
    "'Birthday' 為預設的自訂欄目名稱。你可於'喜好設定'中更改此名稱\n\n"\
    "注意：你需先在地址簿內使用 'Options/Rename Custom Fields' "\
    "以設定以上自訂欄目名稱\n"

    "long_aboutString" = ""\
    "HappyDays"\
	"能幫助你紀錄每個重要事件的日期(例如你親朋戚友的生日及週年紀念等)\n\n"\
    "詳細使用方法請參閱\ index.html 及 manual.html。\n\n"\
    "HappyDays 是根據 GNU GPL2.0 發行的軟體。\n"

    "long_cleanupAlertString" = ""\
    "假如你選擇清除，任何帶有 HappyDays 記號的日誌將被清除。\n"

    "long_sl2lnString" = ""\
    "-) 標示普通月份\n"\
    "#) 標示潤月"

    "long_cantFindAddrString" = ""\
    "在地址簿中找不到 '%s' 欄目\n"\
    "請在地址簿內設定以上自訂欄目名稱\n"

    "Select Time" = "選擇時間"
    "No Time" = "不指定時間"
    "Invalid input date" = "不正確的日期"
    "Export to Memo Pad is completed." = "完成匯出記事本。"

    "SUN"   = "星期日"
    "MON"   = "星期一"
    "TUE"   = "星期二"
    "WED"   = "星期三"
    "THU"   = "星期四"
    "FRI"   = "星期五"
    "SAT"   = "星期六"

    "Not enough memory" = "記憶體不足"
    "%d notify entry is created.\n" = "產生了 %d 個提示。\n"
    "%d existing entry " = "%d 個提示 "
    "is kept untouched." = "被保留。"
    "is modified." = "被修改。"

    "Collecting Information..." = "正在蒐集資訊，請稍候..."

    "HappyDays List" = "HappyDays 清單"
    "Look Up:" = "搜尋："

    "HappyDays View" = "HappyDays 檢視"
    "Done"  = "完成"
    "DB" = "行事"
    "TD" = "待辦"
    "Goto" = "去"

    "Utilities" = "工具"
    "Date Book Notify" = "行事曆提示"
    "Cleanup Date Book"  = "清理行事曆"
    "To Do Notify" = "待辦表提示"
    "Cleanup To Do"  = "清理待辦表"
    "Export to Memo Pad" = "匯出到記事本"
    "Solar to Lunar" = "陽曆轉陰曆"
    "Lunar to Solar" = "陰曆轉陽曆"
    "Rescan Address Book" = "重新檢查地址簿"

    "Options" = "選項"
    "Font..." = "字型"
    "Preferences" = "喜好設定"
    "Display Preferences" = "畫面喜好設定"
    "About HappyDays" = "關於 HappyDays"

    "Edit" = "編輯"
    "Undo" = "復原"
    "Cut" = "剪下"
    "Copy" = "複製"
    "Paste" = "貼上"
    "Select All" = "全選"
    "Keyboard" = "鍵盤"
    "Graffiti" = "手寫提示"

/* Font... */

/* preferences screen */

    "Custom field:" = "自訂欄目："
    "Instead of system date format" = "不使用系統日期格式"
    "Use" = "並改用"

    "M/D/Y" = "M/D/Y"
    "D/M/Y" = "D/M/Y"
    "D.M.Y" = "D.M.Y"
    "D-M-Y" = "D-M-Y"
    "Y/M/D" = "Y/M/D"
    "Y.M.D" = "Y.M.D"
    "Y-M-D" = "Y-M-D"
/*
    "M/D/Y" = "月/日/年"
    "D/M/Y" = "日/月/年"
    "D.M.Y" = "日.月.年"
    "D-M-Y" = "日-月-年"
    "Y/M/D" = "年/月/日"
    "Y.M.D" = "年.月.日"
    "Y-M-D" = "年-月-日"
*/
    "Address Autoscan" = "自動檢查地址簿"
    "Always" = "永遠"
    "Ask" = "先問我"
    "Never" = "永不"

    "Notify Format:" = "提示格式:"
    "[Last, First] E(1) Year" = "[姓, 名] E(1) 年"
    "[First Last] E(1) Year" = "[名 姓] E(1) 年"
    "Event - Last, First Year" = "事件 - 姓，名 年"
    "Event - First Last Year" = "事件 - 名 姓 年"
    "First Last Year" = "名 姓 年"

    "Address Book:" = "地址簿"
    "Built-in" = "內建"

/* Display preferences */
    "Emphasize Lunar Date" = "突顯陰曆事件"


/* About HappyDays */
    "GPL free software" = "GPL 自由軟體"
    "E-Mail & Web Page" = "電郵及網址"

    "Translator" = "中文版 - 大頭 ( 給 亞華 :)"
    "Translator's email" = "daitau@hotmail.com"

    "OK" = "確定"
    "Cancel" = "取消"

    "Solar to Lunar Convert" = "陽曆轉陰曆"
    "Enter Solar date:" = "陽曆："
    "Year must be in 1881-2043" = "年份須在 1881 - 2043 間"
    "Result Lunar date:" = "陰曆："

    "Convert" = "轉換"

    "Lunar to Solar Convert" = "陰曆轉陽曆"
    "Enter Lunar date:" = "陰曆："
    "Leap" = "潤年"
    "Result Solar date:" = "陽曆："

/* Date Book & To Do Notify */
    "Records:" = "紀錄："
    "all" = "全部"
    "selected" = "已選"
    "Existing:" = "現有的："
    "keep" = "保留"
    "modify" = "修改"
    "Priority:" = "重要性："
    "Category:" = "類別："
    "Private:" = "私人的："
    "Alarm:" = "響鬧："
    "Time:" = "時間："
    "Icon" = "圖示"

    "Repeat for:" = "重覆："
    "years" = "年"

    "Notify warning" = "提示"

    "long_notifywarningString" = "^1: 你是否想建立 ^2 個 HappyDays"\
	"紀錄的提示？"

/* Date Book Icon */
    "Date Book Icon" = "行事曆圖示"
    "Icon Support" = "圖示支援"
    "AN" = "AN"
    "DateBk3" = "DateBook3"
    "AN Icon Number:" = "AN 圖示編號："
    "DateBk3 Icon:" = "DateBook3 圖示："

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "清理 HappyDays"

    "long_removeConfirmString" = ""\
    "你是否確定要清除所有 HappyDays 提示？"

    "HappyDays says" = "HappyDays 說"

    "HappyDays Export" = "HappyDays 匯出"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
      "要將 HappyDays 的資料匯出記事本？"

    "Custom Field Error" = "自訂欄目錯誤"
    "Help" = "說明"


    "Invalid event format" = "不正確的事件格式"

    "long_invalidformatString" = ""\
    "^1 的地址簿欄目\n 含有一個不合格式的事件，應怎處理？"

    "Ignore" = "略過"
    "Ignore all" = "全部略過"

    "Cleanup Done" = "清理完畢"

    "^1: ^2 HappyDays notify entries removed." = ""\
    "^1: ^2 個 HappyDays 提示被清除了."

    "HappyDays Export List" = "HappyDays 匯出列表"
    "(not exist in this year)" = "(本年度沒有)"
    "Please run Date Book once first." = "請先執行一次行事曆"

    "Days" = "日"
    "Date Book" = "行事曆"
    "To Do" = "待辦表"
    "Scan note field" = "連備注欄目也一併檢查"

    "Processing" = "處理中"
    "Processed : " = "處理了："

    "Address Change" = "重新檢查地址簿"
    "AddressDB is changed. \nDo you want to rescan it?"= ""\
    "地址簿資料曾被更新。 \n你要讓 HappyDays 重新檢查？"

/* HappyDays view */
	"Type:" = "事件類別"
	"Next Date:" = "下一日期"
	"Origin:" = "原本日期"
	"Age:" = "週年歲數"
	"UpTo Date:" = "距下一次"
	"%dY %dM %dD (%ld)" = "%d年 %d月 %d日 (%ld)"
	/* Daitau: the following line is still not localized */
	"%ld days left" = "%ld 日"
	"%ld days passed" = "%ld days passed"
END
