TRANSLATION "CHINESE"
BEGIN
    "Translator" = "中文版 - 大頭 ( 給 亞華 :-)"
    "Translator's email" = "daitau@hotmail.com"

    "long_notifySettingString" = ""\
      "* 紀錄\n"\
      "假如要產生所有事件的提示，請選擇'全部'"\
      "如只要產生被選事件的提示，請選擇'已選'\n\n"\
      "* 現有的\n"\
      "假如不想修改現有的紀錄，請選擇'保留'，否則請選'修改'\n\n"\
      "* 響鬧\n"\
      "使用 Date Book 內的響鬧提示\n"\
      "可選擇於多少天前提示\n\n"\
      "* 時間\n"\
      "設定事件的時間\n\n"\
      "* 重覆\n"\
      "表示要重覆多少年"\
      "假如設為 -1，陽曆事件將每年重覆，陰曆事件則重覆五年\n\n"

    "long_notifySettingMoreString" = ""\
      "關於 AN 圖示編號，請參考 Action Names 說明書"\
      "DateBk3 圖示將由 Memo Pad 處取得。"\
      "假如沒有設定，則不會顯示圖示。\n"

    "long_customErrorString" = ""\
      "'Birthday' 為預設的自訂欄目名稱。你可於'喜好設定'中更改此名稱\n\n"\
      "注意：你需先在 Address Book 內使用 'Options/Rename Custom Fields' "\
	  "以設定以上自訂欄目名稱\n"

    "long_aboutString" = ""\
      "'HappyDays' 能幫助你紀錄每個重要事件的日期(例如你親朋戚友的生日及週年紀念等)\n\n"\
      "請在 Address Book 內設定一個自訂欄目為 'Birthday'。"\
      "\n\n例如:\n"\
      " 姓: 廖\n"\
      " 名: 大頭\n"\
      " ...\n"\
      " Birthday: -)12/23/78\n\n"\
      "格式:\n"\
      " [-)|#)]日期\n"\
      " -) 代表陰曆\n"\
      " #) 代表潤月\n\n"\
      "日期格式則從系統設定中自動讀取。"\
      "年份可省略。"\
      "少於 100 的年份會被當成二十世紀的日期，假如你不肯定，"\
      "請用 YYYY 的格式 (如 1970)\n\n"\
      "如要同時設定多項事件，請參考說明書。\n\n"\
      "在 HappyDays 中列出名字之姓/名次序，可在地 Address Book 內使用 "\
      "'Preferences/List By' 中更改。"\
      "至於日期格式則由 Prefs 中 Formats/Date 決定。\n\n"\
      "你可以在手寫區中寫要尋找名字的首個字母以快捷地搜尋。"\
      "你亦可以寫月份來尋找該月之紀錄。\n\n"

    "long_cleanupAlertString" = ""\
      "假如你選擇清除，所有帶有 HappyDays 記號 (包括你自己輸入) 的日誌將被清除\n"

    "long_prefFormString" = ""\
      "* 不使用系統日期格式\n"\
      "控制 HappyDays 如何讀取 Address Book 內的日期格式\n\n"\
      "* Note欄目也包含事件資訊\n"\
      "使 HappyDays 讀取 Note欄目\n\n"\
      "* 突顯陰曆事件\n"\
      "在陰曆事件下加底線\n\n"\
      "* 提示格式\n"\
      "選擇提示的格式\n\n"\
      "* 自訂欄目\n"\
      "自訂欄目的名稱\n\n"\
      "* HappyDays 記號\n"\
      "用以提示及方便清理"

    "long_removeConfirmString" = ""\
      "你是否確定要清除所有 HappyDays 提示？"

    "long_sl2lnString" = ""\
      "-) 標示普通月份\n"\
      "#) 標示潤月"

    "long_cantFindAddrString" = ""\
      "在 Address Book 中找不到 '%s' 欄目\n"\
      "請在 Address Book 內設定以上自訂欄目名稱\n"

    "Select Time" = "設定時間"
    "No Time" = "不指定時間"
    "Invalid input date" = "不正確的日期"
    "Export to Memo Pad is completed." = "完成 Memo Pad 匯出。"

    "SUN"   = "星期日"
    "MON"   = "星期一"
    "TUE"   = "星期二"
    "WED"   = "星期三"
    "THU"   = "星期四"
    "FRI"   = "星期五"
    "SAT"   = "星期六"

    "Not enough memory" = "記憶體不足"
    "%d notify entry is created.\n" = "產生了 %d 個提示。\n"
    "%d existing entry " = "%d 個提示 "
    "is kept untouched." = "被保留。"
    "is modified." = "被修改。"

    "Could not write prefs." = "不能儲存設定。"
    "Collecting Information..." = "正在蒐集資訊，請稍候..."

    "HappyDays List" = "HappyDays 清單"
    "Look Up:" = "搜尋："

	"HappyDays View" = "HappyDays 檢視"
    "Done"  = "完成"
    "DB" = "DateBk"
    "TD" = "Todo"
    "Goto" = "Addr"

    "Utilities" = "工具"
    "Date Book Notify" = "Date Book 提示"
    "Cleanup Date Book"  = "清理 Date Book"
    "To Do Notify" = "To Do List 提示"
    "Cleanup To Do"  = "清理 To Do List"
    "Export to Memo Pad" = "匯出到 MemoPad"
    "Solar to Lunar" = "陽曆轉陰曆"
    "Lunar to Solar" = "陰曆轉陽曆"

    "Options" = "選項"
    "Preferences" = "喜好設定"
    "About HappyDays" = "關於 HappyDays"

    "Edit" = "編輯"
    "Undo" = "復原"
    "Cut" = "剪下"
    "Copy" = "複製"
    "Paste" = "貼上"
    "Select All" = "全選"
    "Keyboard" = "鍵盤"
    "Graffiti" = "手寫提示"

    "HappyDays Preferences" = "HappyDays 喜好設定"
    "Custom field:" = "自訂欄目："
    "HappyDays ID:" = "HappyDays 記號："
    "Emphasize Lunar Date" = "突顯陰曆事件"

    "OK" = "確定"
    "Cancel" = "取消"

    "Solar to Lunar Convert" = "陽曆轉陰曆"
    "Enter Solar date:" = "陽曆："
    "Year must be in 1881-2043" = "年份須在 1881 - 2043 間"
    "Result Lunar date:" = "陰曆："

    "Convert" = "轉換"

    "Lunar to Solar Convert" = "陰曆轉陽曆"
    "Enter Lunar date:" = "陰曆："
    "Leap" = "潤年"
    "Result Solar date:" = "陽曆："

    "Records:" = "紀錄："
      "all" = "全部"
      "selected" = "已選"
    "Existing:" = "現有的："
      "keep" = "保留"
      "modify" = "修改"
    "Priority:" = "重要性："
	  "Category:" = "類別："
    "Private:" = "私人的："
    "Alarm:" = "響鬧："
    "Time:" = "時間："
    "More..." = "還有..."
    "Icon" = "圖示"

    "Repeat for:" = "重覆："
    "years" = "年"

    "HappyDays says" = "HappyDays 說"

    "HappyDays Export" = "HappyDays 匯出"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
      "要將 HappyDays 的資料匯出 Memo Pad？"

    "Custom Field Error" = "自訂欄目錯誤"
    "Help" = "說明"


    "HappyDays Cleanup" = "清理 HappyDays"

    "Notify warning" = "提示"
    "^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
      "^1: 你是否想建立 ^2 個 HappyDays 紀錄的提示？"

    "Invalid event format" = "不正確的事件格式"

    "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
      "^1 的地址簿欄目\n 含有一個不合格式的事件，應怎處理？"

    "Ignore" = "略過"
    "Ignore all" = " 全部略過"

    "Cleanup Done" = "清理完畢"

    "^1: ^2 HappyDays notify entries removed." = ""\
      "^1: ^2 個 HappyDays 提示被清除了."

    "Birthday" = "生日"
    "All" = "所有"
    "HappyDays Export List" = "HappyDays 匯出列表"
    "(not exist in this year)" = "(本年度沒有)"
    "Please run Date Book once first." = "請先執行 Date Book 一次"

    "Instead of system date format" = "不使用系統日期格式"
    "Use" = "改用"
/*
    "M/D/Y" = "月/日/年"
    "D/M/Y" = "日/月/年"
    "D.M.Y" = "日.月.年"
    "D-M-Y" = "日-月-年"
    "Y/M/D" = "年/月/日"
    "Y.M.D" = "年.月.日"
    "Y-M-D" = "年-月-日"
*/

  "Icon Support" = "圖示支援"
  "AN" = "AN"
	"DateBk3" = "DBk3"
  "AN Icon Number:" = "AN 圖示編號："
  "DateBk3 Icon:" = "DateBk3 圖示："

  "Days" = "日"
	"Date Book" = "Date Book"
	"To Do" = "To Do"
	"Scan note field" = "Note 欄目也包含事件資訊"
  "%d day(s) left" = "尚餘%d日"
  "%d day(s) passed" = "已經過了%d日"

	"Notify Format:" = "提示格式:"
  "[Last, First] E(1) Year" = "[姓, 名] E(1) 年"
	"[First Last] E(1) Year" = "[名 姓] E(1) 年"
	"Event - Last, First Year" = "事件 - 姓，名 年"
	"Event - First Last Year" = "事件 - 名 姓 年"
	"First Last Year" = "名 姓 年"

	"Processing" = "處理中"
	"Processed : " = "處理了："

/* new in 1.40 */
  "GPL free software"="GPL 自由軟體"
  "E-Mail & Web Page"="電郵及網址"
  "Name"="姓名"
  "Date"="日期"
  "Age"="歲"
  "%d day(s) passed"="過了 %d 天"
END




