TRANSLATION "CZECH"
BEGIN
    "long_notifySettingMoreString" = ""\
    "Nápovìdu k ikonám pro Action Names (AN) najdeš v jeho manuálu. "\
    "Ikony pro DateBk3/4 jsou uloeny v Memo Padu. "\
    "Pokud je tam nemáš, nic se nezobrazí.\n"

    "long_customErrorString" = ""\
    "Název uivatelské poloky Address Booku, "\
    "ze které ète HappyDays datum narozenin a svátkù, je defaultnì 'Birthday'. "\
    "Pokud chceš pouívat jinou, zvol 'Nastavení'.\n\n"\
    "POZOR: Potøebuješ-li zmìnit názvy uivatelskıch poloek Address Booku, "\
    "spus jej a v menu 'Options' zvol monost 'Rename Custom Fields'. "\
    "Název aspoò jedné takové poloky musí odpovídat názvu, kterı jsi "\
    "zadal v HappyDays.\n"

    "long_aboutString" = ""\
    "'HappyDays' ti pomùe pamatovat na narozeniny a svátky tvıch pøátel "\
    "a èlenù rodiny.\n\n"\
    "Detailní informace o pouití HappyDays najdeš v souborech "\
    "index.html a manual.html.\n\n"\
    "Šíøení HappyDays se øídí podmínkami uvedenımi v GNU General "\
    "Public License verze 2.0.\n"

    "long_cleanupAlertString" = ""\
    "Události Date Booku a To Do vytvoøené programem HappyDays "\
    "mají v poznámce øetìzec {HappyDays ID}. "\
    "Pokud jej vloíš do poznámky nìkteré události ruènì, mùe se stát, "\
    "e ji HappyDays pøi èištìní smae také.\n"

    "long_sl2lnString" = ""\
        "-) pro bìnı mìsíc lunárního kalendáøe\n"\
        "#) pro pøestupnı mìsíc lunárního kalendáøe"

    "long_cantFindAddrString" = ""\
    "V Address Booku chybí uivatelská poloka '%s'. "\
    "Vytvoø ji nebo zmìò její název pomocí 'Nastavení'."

    "Select Time" = "Zvol èas"
    "No Time" = "ádnı"
    "Invalid input date" = "Neplatné datum"
    "Export to Memo Pad is completed." = "Export do Memo Padu dokonèen."

    "SUN" = "Ne"
    "MON" = "Po"
    "TUE" = "Út"
    "WED" = "St"
    "THU" = "Èt"
    "FRI" = "Pá"
    "SAT" = "So"

    "Not enough memory" = "Nedostatek pamìti"
    "%d notify entry is created.\n" = "Vytvoøeno %d upozornìní.\n" 
    "%d existing entry " = "%d existujících upozornìní "
    "is kept untouched." = "ponecháno beze zmìny."
    "is modified." = "zmìnìno."

    "Collecting Information" = "Sbírám informace"

    "HappyDays List" = "Seznam"
    "Look Up:" = "Hledej"

    "HappyDays View" = "Detaily"
    "Done" = "OK"
    "DB" = "DB" 
    "TD" = "TD"
    "Goto" = "Address Book"

    "Utilities" = "Akce"
    "Date Book Notify" = "Upozornìní Date Booku"
    "Cleanup Date Book" = "Vyèištìní Date Booku"
    "To Do Notify" = "Upozornìní To Do"
    "Cleanup To Do" = "Vyèištìní To Do"
    "Export to Memo Pad" = "Export do Memo Padu"
    "Solar to Lunar" = "Solarní na lunární"
    "Lunar to Solar" = "Lunární na solární"
    "Rescan Address Book" = "Prohledání Address Booku"

    "Options" = "Monosti"
    "Font..." = "Písmo"
    "Preferences" = "Nastavení"
    "Display Preferences" = "Monosti zobrazení"
    "About HappyDays" = "O aplikaci HappyDays"

    "Edit" = "Úpravy"
    "Undo" = "Zpìt"
    "Cut" = "Vyjmout"
    "Copy" = "Kopírovat" 
    "Paste" = "Vloit" 
    "Select All" = "Oznaèit vše" 
    "Keyboard" = "Klávesnice" 
    "Graffiti" = "Graffiti"


/* Font... */

/* preferences screen */
    "Custom field:" = "Název poloky:"
    "Instead of system date format" = "Místo systémového formátu"
    "Use" = "pouij"
    "M/D/Y" = "M/D/R"
    "D/M/Y" = "D/M/R"
    "D.M.Y" = "D.M.R"
    "D-M-Y" = "D-M-R"
    "Y/M/D" = "R/M/D"
    "Y.M.D" = "R.M.D"
    "Y-M-D" = "R-M-D"
    "Address Autoscan" = "Sleduj zmìny"
    "Always" = "vdy"
    "Ask" = "zeptej se"
    "Never" = "nikdy"

    "Notify Format:" = "Formát upozornìní:"
    "[Last, First] E(1) Year" = "[pøíjm., køest.] u (rok)"
    "[First Last] E(1) Year" = "[køest. pøíjm.] u (rok)"
    "Event - Last, First Year" = "událost - pøíjm., køest. rok"
    "Event - First Last Year" = "událost - køest. pøíjm. rok"
    "First Last Year" = "køest. pøíjm. rok"
   
    "Address Book:" = "Address Book:"
    "Built-in" = "standardní"


/* Display preferences */
    "Emphasize Lunar Date" = "Zvırazni lunární datum"


/* About HappyDays */  
    "GPL free software" = "GPL free software"
    "E-Mail & Web Page" = "e-mail & webová stránka"

    "Translator" = "Petr 'PePa' Pavel"
    "Translator's email" = "petr.pavel@centrum.cz"


    "OK" = "OK"
    "Cancel" = "Storno"

    "Solar to Lunar Convert" = "Solární na lunární"
    "Enter Solar date:" = "Zadej solární datum:"
    "Year must be in 1881-2043" = "Rok musí bıt mezi 1881 a 2043."
    "Result Lunar date:" = "Vısledné lunární datum:"

    "Convert" = "Pøevod"

    "Lunar to Solar Convert" = "Lunární na solární"
    "Enter Lunar date:" = "Zadej lunární datum:"
    "Leap" = "pøestupnı"
    "Result Solar date:" = "Vısledné solární datum:"


/* Date Book & To Do Notify */
    "Records:" = "Záznamy:"
      "all" = "vše"
      "selected" = "zvolenı" 
    "Existing:" = "Existující:"
      "keep" = "nech bıt"
      "modify" = "zmìò"
    "Priority:" = "Priorita:"
    "Category:" = "Kategorie:"
    "Private:" = "Soukromé:"
    "Alarm:" = "Alarm:"
    "Time:" = "Èas:"
    "Icon" = "Ikona"

    "Repeat for:" = "Opakuj:"
    "years" = "rok(y)/let"

    "Notify warning" = "Upozornìní"
    "long_notifywarningString" = ""\
    "^1: Urèitì chceš vytvoøit upozornìní pro ^2 poloek?" 


/* Date Book Icon */
    "Date Book Icon" = "Ikony"
    "Icon Support" = "Ikony pro"
    "AN" = "AN"
    "DateBk3" = "DateBk3/4"
    "AN Icon Number:" = "Èíslo ikony pro AN:"
    "DateBk3 Icon:" = "Ikona pro DateBk3/4:"

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "Vyèisti" 

    "long_removeConfirmString" = ""\
    "Urèitì chceš odstranit všechna "\
    "upozornìní vytvoøená programem HappyDays?"

    "HappyDays says" = "HappyDays"

    "HappyDays Export" = "Export"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
    "Skuteènì chceš exportovat seznam událostí z HappyDays do Memo Padu?" 

    "Custom Field Error" = "Chybnı název poloky"
    "Help" = "Nápovìda"

    "Invalid event format" = "Neplatnı formát události" 

    "long_invalidformatString" = ""\
    "Záznam pro ^1\n má neplatnı formát. Co s tím mám dìlat?"


    "Ignore" = "Ignoruj" 
    "Ignore all" = "Ignoruj vše"

    "Cleanup Done" = "Vyèištìní dokonèeno" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    "^1: Odstranìno ^2 záznamù." 

    "HappyDays Export List" = "Export" 
    "(not exist in this year)" = "(v tomto roce se nevyskytuje)" 
    "Please run Date Book once first." = "Nejdøív spuste aspoò jednou Date Book."
    
    "Days" = "dny"
    "Date Book" = "Date Book"
    "To Do" = "To Do"
    "Scan note field" = "Prohledej i poznámky"
    "%ld days left" = "Zbıvá %ld dní."
    "%ld days passed" = "%ld dní uplynulo."

    "Processing" = "Vytváøím"
    "Processed : " = "Vytvoøeno: " 

    "Address Change" = "Zmìna v adresáøi"
    "AddressDB is changed. \nDo you want to rescan it?"= ""\
    "Databáze Address Booku se zmìnila. \nMám ji znovu prohledat?"

/* HappyDays view */
    "Type:" = "Typ:"
    "Next Date:" = "Nejbliší:"
    "Origin:" = "Poèátek:"
    "Age:" = "Vìk:"
    "UpTo Date:" = "A do:"
    "%dY %dM %dD (%ld)" = "%dR %dM %dD (%ld)"

    "Yes" = "Ano"
    "No" = "Ne"

	"N" = "J"
	"D" = "D"
	"A" = "U"
END
