TRANSLATION "DUTCH"
BEGIN
    "Translator" = "Roy Huijts"
    "Translator's email" = ""

    "long_notifySettingString" = ""\
        "* Verjaardagen\n"\
        "Kies 'alle' als u alle gegevens in de gekozen categorie "\
        "wilt aanpassen"\
        "."\
        "Kies 'selecteerd' als u 1 verjaardag wilt aanpassen "\
        ".\n\n"\
        "* Aanwezig\n"\
        "Kies 'bewaar' als de aanwezige HappyDays invoer "\
        "ongewijzigd moet blijven. Kies 'wijzig' als u wilt dat de "\
        "invoer wordt aangepast.\n\n"\
        "* Alarm\n"\
        "Stelt het aantal dagen in dat u gewaarschuwd wordt voor een bepaalde verjaardag"\
        ".\n\n"\
        "* Tijd\n"\
        "Tijd van de melding.\n\n"\
        "* Herhaal voor\n"\
        "is de interval van de melding. "\
        "-1 betekend voor een zonne kalender herhaling voor altijd, en "\
        "voor de maan kalender betekent dit dat het voor het gemak 5 jaar herhaald wordt.\n"

    "long_notifySettingMoreString" = ""\
        "Lees de ActionNames handleiding om de AN Icoon nummers te achterhalen. "\
        "Wanneer u DateBk3 gebruikt en geen icoon opgeeft dan zal er geen "\
        "verjaardag in DateBk3 worden getoond.\n"

    "long_customErrorString" = ""\
        "'Verjaardag' is de standaard gebruikersgedefinieerde veldnaam."\
        "Wanneer u een ander veld wilt gebruikern, start dan de eigenschappen uit het menu.\n\n"\
        "BELANGRIJK: U moet het adresboek openen en met 'Options/"\
        "Rename Custom Fields' een gebruikers veld hernoemen naar 'Verjaardag' "\
        "of een andere veldnaam afhankelijk wat u in HappyDays heeft gespecificeerd.\n"

    "long_aboutString" = ""\
        "'HappyDays' zorgt ervoor dat u belangrijke gebeurtenissen en verjaardagen "\
        "van familie en vrienden niet meer zult vergeten."\
        "\n\nGebruik een van de velden in het adresboek programma "\
        "en wijzig de naam van het veld in 'Verjaardag'."\
        "\n\nVoorbeeld:\n"\
        " Achternaam: Jeong\n"\
        " Voornaam: JaeMok\n"\
        " ...\n"\
        " Verjaardag: -)12-4-70\n\n"\
        "Formats:\n"\
        " [-)|#)]Date\n"\
        " -) betekend maan kalender\n"\
        " #) betekend maan wissel maand\n\n"\
        "Datum formaat wordt uit het systeem gehaald. "\
        "U kunt het jaar-veld aanpassen. Jaar invoer lager dan 100 wordt beschouwd als "\
        "een jaar in de 20st eeuw, bent u niet zeker van het juiste jaar, "\
        "gebruik voor jaar JJJJ (b.v. 1970).\n\n"\
        "Lees de handleiding wanneer men meerdere gegevens tegelijkertijd wil invoeren.\n"

    "long_cleanupAlertString" = ""\
        "Notificatie regels worden als HappyDays regels beschouwd wanneer "\
        "ze {HappyDays ID} identificatie in het veld hebben staan. "\ 	
        "Als dit formaat gebruikt wordt in de eigen regels "\
        ", dan kunnen deze regels verwijderd worden door CleanUp.\n"

    "long_prefFormString" = ""\
        "* Inplaats van de systeemdatum\n"\
        "Controleer of de naam van uw eigen veld hetzelfde is dan die in het adresboek. "\
        "Normaal moeten deze hetzelfde zijn.\n\n"\
        "* Scan notities\n"\
        "Om notities te lezen, moet deze optie aangevinkt worden.\n\n"\
        "* Emphasize Lunar Date\n"\
        "Als de checkbox aangevinkt is dan wordt een onderbroken lijn getoond onder de maan kalender datum.\n\n"\
        "* Overzicht formaat\n"\
        "De wijze waarop u de lijst kan bekijken\n\n"\
        "* Eigen veld\n"\
        "De naam van het eigen veld in het adresboek voor INVOER\n\n"\
        "* HappyDays ID\n"\
        "Te gebruiken voor meldingen en opschonen\n"

    "long_removeConfirmString" = ""\
        "Weet u zeker dat u alle HappyDays "\
        "verjaardagen wilt verwijderen?"

    "long_sl2lnString" = ""\
        "-) betekend normale maand in maan kalender\n"\
        "#) betekend wissel maand in maan kalender"

    "long_cantFindAddrString" = ""\
        "Kan eigen veld niet vinden in het adresboek: '%s'\n"\
        "Wijzig naam van eigen veld in Verjaardag in uw adresboek."

        "Select Time" = "Selecteer tijd"
        "No Time" = "Geen tijd"
        "Invalid input date" = "Onjuiste datum"
        "Export to Memo Pad is completed." = "Export naar Memo is voltooid."

        "SUN"   = "ZON"
        "MON"   = "MAA"
        "TUE"   = "DIN"
        "WED"   = "WOE"
        "THU"   = "DON"
        "FRI"   = "VRY"
        "SAT"   = "ZAT"

        "Not enough memory" = "Niet genoeg geheugen"
        "%d notify entry is created.\n" = "%d melding is aangemaakt.\n" 
        "%d existing entry " = "%d bestaande invoer "
        "is kept untouched." = "is ongewijzigd bewaard."
        "is modified." = "is aangepast."

        "Could not write prefs." = ""\
        "Kan niet worden aangepast."
        "Collecting Information" = "Verzamel informatie"

        "HappyDays List" = "HappyDays Overzicht"
        "Look up" = "Ga naar datum..."
        "Today" = "Vandaag"

        "HappyDays View" = "HappyDays View"
        "Done"  = "Klaar"
        "DB" = "DB" 
        "TD" = "TD"
        "Goto" = "Ga naar"

        "Utilities" = "Utilities"
        "Date Book Notify" = "Agenda afspraak"
        "Cleanup Date Book"  = "Opschonen agenda"
        "To Do Notify" = "To Do melding"
        "Cleanup To Do"  = "Opschonen To Do"
        "Export to Memo Pad" = "Export naar Memo"
        "Solar to Lunar" = "Zon naar maand"
        "Lunar to Solar" = "Maan naar zon"
        "Options" = "Opties"
        "Preferences" = "Eigenschappen"
        "About HappyDays" = "Over HappyDays"

        "Edit" = "Wijzigen"
        "Undo" = "Ongedaan maken"
        "Cut" = "Knippen"
        "Copy" = "Kopieren" 
        "Paste" = "Plakken" 
        "Select All" = "Selecteer alles" 
        "Keyboard" = "Toetsenbord" 
        "Graffiti" = "Graffiti"

        "HappyDays Preferences" = "HappyDays Eigenschappen"
        "Custom field:" = "Verjaardag:"
        "HappyDays ID:" = "HappyDays ID:"
        "Emphasize Lunar Date" = "Benadruk maan datums"

        "OK" = "OK"
        "Cancel" = "Annuleer"
    
        "Solar to Lunar Convert" = "Omzetten Zon naar Maan"
        "Enter Solar date:" = "Voer Zonne Datum in:"
        "Year must be in 1881-2043" = "Jaar moet tussen 1881-2043 liggen"
        "Result Lunar date:" = "Resultaat Maan datum:"

        "Convert" = "Zet om"

        "Lunar to Solar Convert" = "Converteer Maan naar Zon"
        "Enter Lunar date:" = "Voer Maan datum in:"
        "Leap" = "Wissel"
        "Result Solar date:" = "Resultaat Zonne datum:"

        "Records:" = "Records:"
        "all" = "alle"
        "selected" = "selecteerd" 
        "Existing:" = "Aanwezig:"
        "keep" = "bewaar"
        "modify" = "wijzig"
        "Priority:" = "Prioriteit:"
        "Category:" = "Categorie:"
        "Private:" = "Prive:"
        "Alarm:" = "Alarm:"
        "Time:" = "Tijd:"
        "More..." = "Meer..."

        "Repeat for:" = "Herhaal voor:"
        "years" = "jaren"

        "HappyDays says" = "HappyDays zegt"

        "HappyDays Export" = "HappyDays Exporteren"
        "Would you like to export HappyDays List to Memo Pad?" = ""\
        	" Wilt u de verjaardagen exporteren naar Memo?" 

        "Custom Field Error" = "Eigen veld fout"
        "Help" = "Help" 


        "HappyDays Cleanup" = "HappyDays Opschonen" 

        "Notify warning" = "Notify warning" 
        "^1: Are you sure you want to create notify entries for ^2 HappyDays records?" = ""\
      	"^1: Weet u zeker dat u nieuwe gegevens wilt invoeren voor ^2 HappyDays record(s)?" 
      

        "Invalid event format" = "Onjuist formaat" 

        "The address record for ^1\n contains an invalid event. How would you like to handle it?" = ""\
        "Het adresveld ^1\n bevat een onjuist gegeven. Hoe wilt u dit oplossen?" 

        "Ignore" = "Afbreken" 
        "Ignore all" = "Alles afbreken" 

        "Cleanup Done" = "Opschonen voltooid" 

        "^1: ^2 HappyDays notify entries removed." = ""\
        	"^1: ^2 HappyDays invoer is verwijderd." 

        "Birthday" = "Verjaardag" 
        "All" = "Alle" 
        "HappyDays Export List" = "HappyDays Export Lijst" 
        "(not exist in this year)" = "(bestaat niet in dit jaar)" 
        "Please run Date Book once first." = "Open eerst uw agenda."  
    
        "Instead of system date format" = "In plaats van systeem datum"  
        "Use" = "formaat gebruik"  
        "M/D/Y" = "M/D/Y"  
        "D/M/Y" = "D/M/Y"  
        "D.M.Y" = "D.M.Y"  
        "D-M-Y" = "D-M-Y"  
        "Y/M/D" = "Y/M/D"  
        "Y.M.D" = "Y.M.D"  
        "Y-M-D" = "Y-M-D"  

        "Date Book Icon" = "Date Book Icoon"  
          "Icon Support" = "Icoon voor"  
          "AN" = "AN"  
          "DateBk3" = "DateBk3"  
          "AN Icon Number:" = "AN Icoon Nummer:"  
          "DateBk3 Icon:" = "DateBk3 Icoon:"  

        "Days" = "Dagen"  
        "Date Book" = "Agenda"  
        "To Do" = "To Do"  
        "Scan note field" = "Scan notitievelden"  
        "%d day(s) left" = "%d dag(en) te gaan"  
        "Notify Format:" = "Waarschuwings formaat:"  
        "[Last, First] E(1) Year" = "[Achter, Voor] L(1) Jaar"  
        "[First Last] E(1) Year" = "[Voor Achter] L(1) Jaar"  
        "Event - Last, First Year" = "Event - Achter, Voor Jaar"  
        "Event - First Last Year" = "Event - Voor Achter Jaar"  
        "First Last Year" = "Voor Achter Jaar"  
        
        "Processing" = "Verwerken"  
        "Processed : " = "Verwerkt : " 
END
