TRANSLATION "ENGLISH"
BEGIN
	"long_notifySettingMoreString" = ""\
	"For advanced user only\n\n"\
	"This note is used for third-party datebook replacement program "\
	"such as Action Names, DateBk3/4.\n\n"\
	"You can set a icon, font, and more using this note.\n\n"\
	"For more information, check their manual.\n"

    "long_aboutString" = ""\
    "'HappyDays' will help you remember the birthdays and anniversaries "\
    "of your friends and family members, as well as other events.\n\n"\
    "Visit http://jmjeong.com/?HappyDays for the detailed information "\
    "on how to use HappyDays.\n\n"\
    "HappyDays is distributed under the terms of the GNU General "\
    "Public License version 2.0.\n\n"\
	"= Input Format\n\n"\
	"[*[{EventType}]\\ws{Description}\\ws{Date}[[nth day list]]\n"

    "long_cleanupAlertString" = ""\
    "Notification entries are considered HappyDays if they have "\
	"{HappyDays ID} in their memo field. "\ 	
    "If you use this format in your own "\
    "entries, this record might also be removed by CleanUp.\n"

    "long_sl2lnString" = ""\
        "-) means plain month in lunar\n"\
        "#) means leap month in lunar"

    "Select Time" = "Select Time"
    "No Time" = "No Time"
    "Invalid input date" = "Invalid input date"
    "Export to Memo Pad is completed." = "Export to Memo Pad is completed."

    "SUN"   = "SUN"
    "MON"   = "MON"
    "TUE"   = "TUE"
    "WED"   = "WED"
    "THU"   = "THU"
    "FRI"   = "FRI"
    "SAT"   = "SAT"

    "Not enough memory" = "Not enough memory"
    "%d notify entries have been created.\n" = "%d notify entries have been created.\n" 
    "%d existing entries " = "%d existing entries "
    "are kept untouched." = "are kept untouched."
    "have been modified." = "have been modified."

    "Collecting Information" = "Collecting Information"

    "Look Up:" = "Look Up:"

    "HappyDays View" = "HappyDays View"
    "Done"  = "Done"
    "DB" = "DB" 
    "TD" = "TD"
    "Goto" = "Goto"

    "Utilities" = "Utilities"
    "Date Book Notify" = "Date Book Notify"
    "Cleanup Date Book"  = "Cleanup Date Book"
    "To Do Notify" = "To Do Notify"
    "Cleanup To Do"  = "Cleanup To Do"
    "Export to Memo Pad" = "Export to Memo Pad"
    "Solar to Lunar" = "Solar to Lunar"
    "Lunar to Solar" = "Lunar to Solar"
	"Rescan Address Book" = "Rescan Address Book"

    "Options" = "Options"
	"Font..." = "Font..."
    "Preferences" = "Preferences"
	"Display Preferences" = "Display Preferences"
    "About HappyDays" = "About HappyDays"

    "Edit" = "Edit"
    "Undo" = "Undo"
    "Cut" = "Cut"
    "Copy" = "Copy" 
    "Paste" = "Paste" 
    "Select All" = "Select All" 
    "Keyboard" = "Keyboard" 
    "Graffiti" = "Graffiti"


/* Font... */

/* preferences screen */
    "Custom field:" = "Custom field:"
    "Instead of system date format" = "Instead of system date format"  
    "Use" = "Use"  
    "M/D/Y" = "M/D/Y"  
    "D/M/Y" = "D/M/Y"  
    "D.M.Y" = "D.M.Y"  
    "D-M-Y" = "D-M-Y"  
    "Y/M/D" = "Y/M/D"  
    "Y.M.D" = "Y.M.D"  
    "Y-M-D" = "Y-M-D"  
	"Address Autoscan" = "Address Autoscan"
	"Always" = "Always"
	"Ask" = "Ask"
	"Never" = "Never"

    "Notify Format:" = "Notify Format:"  
    "[Last, First] E(1) Year" = "[Last, First] E(1) Year"  
    "[First Last] E(1) Year" = "[First Last] E(1) Year"  
  	"[First] E(1) Year" = "[First] E(1) Year" 
    "Event - Last, First Year" = "Event - Last, First Year"  
    "Event - First Last Year" = "Event - First Last Year"  
    "First Last Year" = "First Last Year"  
    
	"Address Book:" = "Address Book:"
	"Built-in" = "Built-in"

    "long_prefString" = "Notify format\n"\
        "+L = Last, First\n"\
        "+F = First Last\n"\
        "+f = First\n"\
        "+e = Event Type(1)\n"\
        "+E = Event Type(f)\n"\
        "+y = Year age\n"

/* Display preferences */
    "Emphasize Lunar Date" = "Emphasize Lunar Date"


/* About HappyDays */	
	"GPL free software" = "GPL free software"
	"E-Mail & Web Page" = "E-Mail & Web Page"

    "Translator" = "English version"
    "Translator's email" = "Jaemok Jeong"

    "OK" = "OK"
    "Cancel" = "Cancel"

    "Solar to Lunar Convert" = "Solar to Lunar Convert"
    "Enter Solar date:" = "Enter Solar date:"
    "Year must be in 1881-2043" = "Year must be in 1881-2043"
    "Result Lunar date:" = "Result Lunar date:"

    "Convert" = "Convert"

    "Lunar to Solar Convert" = "Lunar to Solar Convert"
    "Enter Lunar date:" = "Enter Lunar date:"
    "Leap" = "Leap"
    "Result Solar date:" = "Result Solar date:"


/* Date Book & To Do Notify */
    "Records:" = "Records:"
      "all" = "all"
      "selected" = "selected" 
    "Existing:" = "Existing:"
      "keep" = "keep"
      "modify" = "modify"
    "Priority:" = "Priority:"
    "Category:" = "Category:"
    "Private:" = "Private:"
    "Alarm:" = "Alarm:"
    "Time:" = "Time:"
    "Icon" = "Icon"

    "Repeat for:" = "Repeat for:"
    "years" = "years"

    "Notify warning" = "Notify warning" 
	"long_notifywarningString" = ""\
  		"^1: Are you sure you want to create notify entries for "\
		"^2 HappyDays records?" 
      
/* Date Book Icon */
    "Date Book Icon" = "Date Book Icon"  
      "Icon Support" = "Icon Support"  
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "AN Icon Number:"  
      "DateBk3 Icon:" = "DateBk3 Icon:"  

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "HappyDays Cleanup" 

    "long_removeConfirmString" = ""\
    "Are you sure you want to remove all "\
    "HappyDays notify entries?"

    "HappyDays says" = "HappyDays says"

    "HappyDays Export" = "HappyDays Export"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
    	"Would you like to export HappyDays List to Memo Pad?" 

    "Custom Field Error" = "Custom Field Error"
    "Help" = "Help" 


    "Invalid event format" = "Invalid event format" 

	"long_invalidformatString" = ""\
    	"The address record for\n[^1]\n contains an invalid event. "\
		"How would you like to handle it?" 

    "Ignore" = "Ignore" 
    "Ignore all" = "Ignore all" 

    "Cleanup Done" = "Cleanup Done" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    	"^1: ^2 HappyDays notify entries removed." 

    "HappyDays Export List" = "HappyDays Export List" 
    "(not exist in this year)" = "(not exist in this year)" 
    "Please run Date Book once first." = "Please run Date Book once first."  
    
    "Days" = "Days"  
    "Date Book" = "Date Book"  
    "To Do" = "To Do"  
    "Scan note field" = "Scan note field"  
    "%ld days left" = "%ld days left"  
    "%ld days passed" = "%ld days passed"  

    "Processing" = "Processing"  
    "Processed : " = "Processed : " 

	"Address Change" = "Address Rescan"
	"AddressDB is changed. \nDo you want to rescan it?"= ""\
		"Address DB is changed. \nDo you want to rescan it?"

 	"Ignore record with prefix '!'" = "Ignore record with prefix '!'"
 	"Datebook note" = "Datebook note"
 	"Add the following note" = "Add the following note"

/* HappyDays view */
	"Type:" = "Type:"
	"Next Date:" = "Next Date:"
	"Origin:" = "Origin:"
	"Age:" = "Age:"
	"UpTo Date:" = "UpTo Date:"
	"%dY %dM %dD (%ld)" = "%dY %dM %dD (%ld)"

	"Yes" = "Yes"
	"No" = "No"
END

