TRANSLATION "FRENCH"
BEGIN
    "sKst"= "sKst"

    "long_notifySettingMoreString" =  ""\
	"Réservé aux utilisateurs avancés.\n\n"\
	"Cette note est utilisée pour des applications tierces de remplacement de l'Agenda "\
	"telles que Action Names, DateBk3/4.\n\n"\
	"Vous pouvez définir une icône, une police et d'autres paramètres en utilisant cette note.\n\n"\
	"Pour plus d'informations, reportez-vous au manuel.\n"
    "HappyDays"= "HappyDays"
    "long_customErrorString" =  ""\
    "'Birthday' est le nom par défaut du champ personnalisé."\
    "Pour définir un autre nom de champ par défaut,"\
    " tapez 'Préférences'.\n\n"\
    " IMPORTANT : vous devez lancer le Carnet d'adresses et sélectionner 'Options/"\
    "Renommer champs personnalisés' pour renommer l'un des champs personnalisés en 'Birthday'"\
    " ou tout autre chaîne que vous avez saisie dans les Préférences de "\
    "HappyDays.\n"
    "long_aboutString" =  ""\
    "'HappyDays' vous évite d'oublier les anniversaires et les fêtes "\
    "de vos amis et des membres de votre famille, ainsi que d'autres événements.\n\n"\
    "Reportez-vous aux fichiers index.html et manual.html pour des informations détaillées "\
    "sur le façon d'utiliser HappyDays\n\n"\
    "HappyDays est distribué selon les conditions générales GNU "\
    "Public License version 2.0.\n"
    "long_cleanupAlertString" =  ""\
    "Les enregistrements de notification (événements, notes ou tâches) de HappyDays sont reconnus s'ils comportent l'identifiant HappyDays "\
	"{ID HappyDays} dans le champ Note. "
    "long_removeConfirmString" =  ""\
    "Etes-vous sûr de vouloir supprimer tous "\
    "les enregistrements de notification HappyDays ?"
    "Invalid input date" =  "Date non valide"
    "Select Time" =  "Choix heure"
    "No Time" =  "Sans heure"
    "Export to Memo Pad is completed." =  "L'export vers le Bloc-notes est terminé."
    "long_sl2lnString" =  ""\
        "-) signifie mois lunaire plein\n"\
        "#) signifie mois lunaire intercalaire"

    "SUN" =  "Dim"
    "MON" =  "Lun"
    "TUE" =  "Mar"
    "WED" =  "Mer"
    "THU" =  "Jeu"
    "FRI" =  "Ven"
    "SAT" =  "Sam"

    "SMTWTFS"= "DLMMJVS"

    "January"= "Janvier"
    "February"= "Février"
    "March"= "Mars"
    "April"= "Avril"
    "May"= "Mai"
    "June"= "Juin"
    "July"= "Juillet"
    "August"= "Août"
    "September"= "Septembre"
    "October"= "Octobre"
    "November"= "Novembre"
    "December"= "Décembre"

    "Not enough memory" =  "Mémoire insuffisante"
    "%d notify entries have been created.\n"= "%d enregistrements de notification ont été créés.\n"
    "%d existing entries "= "%d enregistrements existants "
    "are kept untouched."= "ont été conservés."
    "have been modified."= "ont été modifiés."
    "HappyDays Export List" =  "Liste exportée par HappyDays" 
    "(not exist in this year)" =  "(n'existe pas cette année)" 
    "Please run Date Book once first." =  "Veuillez d'abord ouvrir l'Agenda."  
    "Please run Todo once first."= "Veuillez d'abord ouvrir les Tâches"
    "Days" =  "jour(s)"  
    "%dY %dM %dD (%ld)" =  "%da %dm %dj (%ldj)"

    "Date Book" =  "Agenda"  
    "To Do" =  "Tâches"  
    "%ld days left" =  "%ld jour(s) restant(s)"  
    "%ld days passed" =  "échu depuis %ld jour(s)"  

    "Type:" =  "Type:"
    "Next Date:" =  "Prochain:"
    "Origin:" =  "Origine:"
    "Age:" =  "Age:"
    "UpTo Date:" =  "A ce jour:"
    "BioRhythm:"= "BioRythme"
    "P(%s) E(%s) I(%s)"= "P(%s) E(%s) I(%s)"

    "Datebook Note"= "Note agenda"
    "ToDo Note"= "Note tâches"

    "Collecting Information" =  "Recherche d'informations"

    "HappyDays "= "HappyDays "

    "Look Up:" =  "Aller à:"
    "N"= "N"
    "D"= "D"
    "A"= "A"

    "HappyDays View" =  "Vue HappyDays"

    "Done" =  "Terminé"
    "DB" =  "Ag" 
    "TD" =  "Tâ"
    "Goto" =  "Aller à"

    "Utilities" =  "Utilitaires"
    "Date Book Notify" =  "Exporter vers Agenda"
    "Cleanup Date Book" =  "Nettoyer Agenda"
    "C"= "N"
    "To Do Notify" =  "Exporter vers Tâches"
    "T"= "T"
    "Cleanup To Do" =  "Nettoyer Tâches"
    "O"= "A"
    "Export to Memo Pad" =  "Exporter vers Bloc-notes"
    "E"= "B"
    "Solar to Lunar" =  "Solaire -> Lunaire"
    "S"= "S"
    "Lunar to Solar" =  "Lunaire -> Solaire"
    "L"= "L"
    "Rescan Address Book" =  "Relire le Carnet d'adresses"

    "Options" =  "Options"
    "Font..." =  "Police de caractères..."
    "F"= "P"
    "Preferences" =  "Préférences"
    "R"= "R"
    "Display Preferences" =  "Préférences d'affichage"
    "About HappyDays" =  "A propos de HappyDays"

    "Edit" =  "Edition"
    "Undo" =  "Annuler"
    "U"= "U"
    "Cut" =  "Couper"
    "X"= "X"
    "Copy" =  "Copier" 
    "Paste" =  "Coller" 
    "P"= "P"
    "Select All" =  "Sélectionner tout" 
    "Keyboard" =  "Clavier" 
    "K"= "C"
    "Graffiti" =  "Aide Graffiti"
    "G"= "G"

    "Emphasize Lunar Date" =  "Souligner les dates lunaires"
    "Display solar/lunar info in View"= "Afficher info solaire/lunaire dans la vue"
    "OK" =  "OK"
    "Cancel" =  "Annuler"

    "Custom field:" =  "Champ perso:"

    "Instead of system date format" =  "Remplacer format date syst."  
    "Use" =  "Par"  
    "M/D/Y" =  "M/J/A"  
    "D/M/Y" =  "J/M/A"  
    "D.M.Y" =  "J.M.A"  
    "D-M-Y" =  "J-M-A"  
    "Y/M/D" =  "A/M/J"  
    "Y.M.D" =  "A.M.J"  
    "Y-M-D" =  "A-M-J"  

    "Scan note field" =  "Scruter champ Note"  
    "Ignore record with prefix '!'" =  "Ignorer enreg. avec préfixe '!'"

    "Address Autoscan" =  "Lect. auto. adresses"
    "Always" =  "Toujours"
    "Ask" =  "Demander"
    "Never" =  "Jamais"

    "Notify Format:" =  "Format de notification:"  
    "[Last, First] E(1) Year" =  "[Nom, Prénom] E(1) An"  
    "[First Last] E(1) Year" =  "[Prénom Nom] E(1) An"  
    "Event - Last, First Year" =  "Evénement - Nom, Prénom An"  
    "Event - First Last Year" =  "Evénement - Prénom Nom An"  
    "First Last Year" =  "Prénom Nom An"  

    "Address Book:" =  "Carnet d'adresses:"
    "Built-in" =  "Standard"
    "Address Album"= "Address Album"
    "AddressBkR"= "AddressBkR"
    "Address Plus(+)"= "Address Plus(+)"
    "Super Names"= "Super Names"
    "TealPhone"= "TealPhone"

    "HappyDays ID:"= "ID HappyDays :"

    "Solar to Lunar Convert" =  "Solaire -> Lunaire"
    "Enter Solar date:" =  "Entrez la date solaire:"
    "Year must be in 1881-2043" =  "Année comprise entre 1881 et 2043"

    "Result Lunar date:" =  "Résultat date lunaire:"

    "Convert" =  "Convertir"

    "Lunar to Solar Convert" =  "Lunaire -> Solaire"
    "Enter Lunar date:" =  "Entrez la date lunaire:"
    "Leap" =  "Intercalaire"

    "Result Solar date:" =  "Résultat date solaire:"

    "Records:" =  "Enreg.:"
    "all" =  "tout"
    "selected" =  "sélectionné" 

    "Existing:" =  "Existants:"
    "keep" =  "garder"
    "modify" =  "modifier"

    "Private:" =  "Personnel:"
    " "= " "

    "Alarm:" =  "Alarme:"

    "Time:" =  "Heure:"

    "Repeat for:" =  "Répéter pdt:"
    "years" =  "an(s)"

    "Note"= "Note"

    "Add the following note" =  "Ajouter la note suivante"

    "Priority:" =  "Priorité:"
    "1"= "1"
    "2"= "2"
    "3"= "3"
    "4"= "4"
    "5"= "5"

    "Category:" =  "Catégorie:"

    "HappyDays says" =  "HappyDays"
    "^1"= "^1"

    "Address Change" =  "Relire le Carnet d'adresses"
    "AddressDB is changed. \nDo you want to rescan it?" =  ""\
		"Le Carnet d'adresses a été modifié. \nVoulez-vous le relire ?"
    "Yes" =  "Oui"
    "No" =  "Non"

    "HappyDays Export" =  "HappyDays Export"
    "Would you like to export HappyDays List to Memo Pad?" =  ""\
    	"Voulez-vous exporter les données Happydays vers le Bloc-notes ?" 

    "HappyDays Cleanup" =  "Nettoyage HappyDays" 
    "^1: ^2"= "^1: ^2"

    "Notify warning" =  "Avertissement" 
    "long_notifywarningString" =  ""\
  		"^1: Etes-vous sûr de vouloir créer des enregistrements de notification "\
		"à partir de ^2 données HappyDays ?" 

    "Invalid event format" =  "Format d'événemenent non valide" 
    "long_invalidformatString" =  ""\
    	"Les données Happydays du Carnet d'adresses pour \n[^1]\n contiennent un événement non valide. "\
		"Comment voulez-vous le traiter ?" 
    "Ignore" =  "Ignorer" 
    "Ignore all" =  "Ignorer tout" 

    "Cleanup Done" =  "Nettoyage terminé" 
    "^1: ^2 HappyDays notify entries removed." =  ""\
    	"^1: ^2 enregistrements de notification HappyDays supprimé(s)." 

    "HappyDays 2.21"= "Happydays 2.21"
    "GPL free software" =  "Logiciel gratuit GPL"
    "(c) 1999-2002 Jaemok Jeong"= "(c) 1999-2002 Jaemok Jeong"

    "E-Mail & Web Page" =  "Email & page web"
    "happydays@jmjeong.com"= "happydays@jmjeong.com"
    "jmjeong.com/?HappyDays"= "jmjeong.com/?HappyDays"

    "Translator" =  "Traduction : Antoine"
    "Translator's email" =  "antoine@freewarefrance.com"

    "Help" =  "Aide" 

    "Processing" =  "Traitement"  
    "Processed : " =  "Traité(s) : " 

    "bitmap/largeIconBW.bmp"= "bitmap/largeIconBW.bmp"

    "bitmap/mediumIconBW.bmp"= "bitmap/mediumIconBW.bmp"

    "bitmap/largeInvertedIconBW.bmp"= "bitmap/largeInvertedIconBW.bmp"

    "bitmap/HD large.bmp"= "bitmap/HD large.bmp"
    "bitmap/HD large color.bmp"= "bitmap/HD large color.bmp"

    "bitmap/HD small.bmp"= "bitmap/HD small.bmp"
    "bitmap/HD small color.bmp"= "bitmap/HD small color.bmp"

    "2.21"= "2.21"
END


