TRANSLATION "FRENCH"
BEGIN
	"long_notifySettingMoreString" = ""\
	"Réservé aux utilisateurs avancés\n\n"\
	"Cette note est utilisée pour des applications tierces de remplacement de l'Agenda "\
	"telles que Action Names, DateBk3/4.\n\n"\
	"Vous pouvez définir une icône, une police et d'autres paramètres en utilisant cette note.\n\n"\
	"Pour plus d'informations, reportez-vous au manuel.\n"

    "long_customErrorString" = ""\
    "'Birthday' est le nom par défaut du champ personnalisé."\
    "Pour définir un autre nom de champ par défaut,"\
    " tapez 'Préférences'.\n\n"\
    " IMPORTANT : vous devez lancer le Carnet d'adresses et sélectionner 'Options/"\
    "Renommer champs personnalisés' pour renommer l'un des champs personnalisés en 'Birthday'"\
    " ou tout autre chaîne que vous avez saisie dans les Préférences de "\
    "HappyDays.\n"

    "long_aboutString" = ""\
    "'HappyDays' vous évite d'oublier les anniversaires et les fêtes "\
    "de vos amis et des membres de votre famille, ainsi que d'autres événements.\n\n"\
    "Reportez-vous aux fichiers index.html et manual.html pour des informations détaillées "\
    "sur le façon d'utiliser HappyDays\n\n"\
    "HappyDays est distribué selon les conditions générales GNU "\
    "Public License version 2.0.\n"

    "long_cleanupAlertString" = ""\
    "Les enregistrements de notification (événements, notes ou tâches) de HappyDays sont reconnus s'ils comportent l'identifiant HappyDays "\
	"{HappyDays ID} dans le champ Note. "\ 	
    "Si vous utilisez également ce format pour vos propres "\
    "enregistrements, ceux-ci sont susceptibles d'être effacés lors d'un nettoyage sous HappyDays.\n"

    "long_sl2lnString" = ""\
        "-) signifie mois lunaire plein\n"\
        "#) signifie mois lunaire intercalaire"

    "long_cantFindAddrString" = ""\
    "Impossible de trouver un champ personnalisé: '%s'\n"\
    "Veuillez renommer un champ personnalisé du Carnet d'adresses."

    "Select Time" = "Choix heure"
    "No Time" = "Sans heure"
    "Invalid input date" = "Date non valide"
    "Export to Memo Pad is completed." = "L'export vers le Bloc-notes est terminé."

    "SUN"   = "DIM"
    "MON"   = "LUN"
    "TUE"   = "MAR"
    "WED"   = "MER"
    "THU"   = "JEU"
    "FRI"   = "VEN"
    "SAT"   = "SAM"

    "Not enough memory" = "Mémoire insuffisante"
    "%d notify entry is created.\n" = "%d enregistrements de notification ont été créés.\n" 
    "%d existing entry " = "%d événements existants "
    "is kept untouched." = "n'ont pas été modifiés."
    "is modified." = "ont été modifiés."

    "Collecting Information" = "Recherche d'informations"

    "Look Up:" = "Aller à:"

    "HappyDays View" = "Vue HappyDays"
    "Done"  = "Terminé"
    "DB" = "Ag" 
    "TD" = "Tâ"
    "Goto" = "Aller"

    "Utilities" = "Utilitaires"
    "Date Book Notify" = "Export vers Agenda"
    "Cleanup Date Book"  = "Nettoyer Agenda"
    "To Do Notify" = "Export vers Tâches"
    "Cleanup To Do"  = "Nettoyer Tâches"
    "Export to Memo Pad" = "Export vers Bloc-notes"
    "Solar to Lunar" = "Solaire -> Lunaire"
    "Lunar to Solar" = "Lunaire -> Solaire"
	"Rescan Address Book" = "Relire le Carnet d'adresses"

    "Options" = "Options"
	"Font..." = "Police de caractères..."
    "Preferences" = "Préférences"
	"Display Preferences" = "Préférences d'affichage"
    "About HappyDays" = "A propos de HappyDays"

    "Edit" = "Edition"
    "Undo" = "Annuler"
    "Cut" = "Couper"
    "Copy" = "Copier" 
    "Paste" = "Coller" 
    "Select All" = "Sélectionner tout" 
    "Keyboard" = "Keyboard" 
    "Graffiti" = "Aide Graffiti"


/* Font... */

/* preferences screen */
    "Custom field:" = "Champ perso:"
    "Instead of system date format" = "Remplacer format date système"  
    "Use" = "Par"  
    "M/D/Y" = "M/J/A"  
    "D/M/Y" = "J/M/A"  
    "D.M.Y" = "J.M.A"  
    "D-M-Y" = "J-M-A"  
    "Y/M/D" = "A/M/J"  
    "Y.M.D" = "A.M.J"  
    "Y-M-D" = "A-M-J"  
	"Address Autoscan" = "Lect. auto. adresses"
	"Always" = "Toujours"
	"Ask" = "Demander"
	"Never" = "Jamais"

    "Notify Format:" = "Format de notification:"  
    "[Last, First] E(1) Year" = "[Nom, Prénom] E(1) An"  
    "[First Last] E(1) Year" = "[Prénom Nom] E(1) An"  
    "Event - Last, First Year" = "Evénement - Nom, Prénom An"  
    "Event - First Last Year" = "Evénement - Prénom Nom An"  
    "First Last Year" = "Prénom Nom An"  
    
	"Address Book:" = "Carnet d'adresses:"
	"Built-in" = "Standard"


/* Display preferences */
    "Emphasize Lunar Date" = "Souligner les dates lunaires"


/* About HappyDays */	
	"GPL free software" = "Logiciel gratuit GPL"
	"E-Mail & Web Page" = "Email & page web"

    "Translator" = "Traduction : Antoine"
    "Translator's email" = "websearch@wanadoo.fr"


    "OK" = "OK"
    "Cancel" = "Annuler"

    "Solar to Lunar Convert" = "Solaire -> Lunaire"
    "Enter Solar date:" = "Entrez la date solaire:"
    "Year must be in 1881-2043" = "Année comprise entre 1881 et 2043"
    "Result Lunar date:" = "Résultat date lunaire:"

    "Convert" = "Convertir"

    "Lunar to Solar Convert" = "Lunaire -> Solaire"
    "Enter Lunar date:" = "Entrez la date lunaire:"
    "Leap" = "Intercalaire"
    "Result Solar date:" = "Résultat date solaire:"


/* Date Book & To Do Notify */
    "Records:" = "Enregistrements:"
      "all" = "tout"
      "selected" = "sélectionné" 
    "Existing:" = "Existants:"
      "keep" = "garder"
      "modify" = "modifier"
    "Priority:" = "Priorité:"
    "Category:" = "Categorie:"
    "Private:" = "Personnel:"
    "Alarm:" = "Alarme:"
    "Time:" = "Heure:"
    "Icon" = "Icône"

    "Repeat for:" = "Répéter pendant:"
    "years" = "an(s)"

    "Notify warning" = "Avertissement" 
	"long_notifywarningString" = ""\
  		"^1: Etes-vous sûr de vouloir créer des enregistrements de notification "\
		"^2 à partir des données HappyDays ?" 
      
/* Date Book Icon */
    "Date Book Icon" = "Icône Agenda"  
      "Icon Support" = "Gestion des icônes"  
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "N° icône AN:"  
      "DateBk3 Icon:" = "Icône DateBk3:"  

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "Nettoyage HappyDays" 

    "long_removeConfirmString" = ""\
    "Etes-vous sûr de vouloir supprimer tous "\
    "les enregistrements de notification HappyDays ?"



    "HappyDays says" = "HappyDays"

    "HappyDays Export" = "HappyDays Export"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
    	"Voulez-vous exporter les données Happydays vers le Bloc-notes ?" 

    "Custom Field Error" = "Erreur de champ personnalisé"
    "Help" = "Aide" 


    "Invalid event format" = "Format d'événemenent non valide" 

	"long_invalidformatString" = ""\
    	"Les données Happydays du Carnet d'adresses pour \n[^1]\n contiennent un événement non valide. "\
		"Comment voulez-vous le traiter ?" 

    "Ignore" = "Ignorer" 
    "Ignore all" = "Ignorer tout" 

    "Cleanup Done" = "Nettoyage terminé" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    	"^1: ^2 enregistrements de notification HappyDays supprimé(s)." 

    "HappyDays Export List" = "Liste exportée par HappyDays" 
    "(not exist in this year)" = "(n'existe pas cette année)" 
    "Please run Date Book once first." = "Veuillez d'abord ouvrir l'Agenda."  
    
    "Days" = "Jour"  
    "Date Book" = "Agenda"  
    "To Do" = "Tâches"  
    "Scan note field" = "Scruter champ Note"  
    "%ld days left" = "%ld jour(s) restant(s)"  
    "%ld days passed" = "échu depuis %ld jour(s)"  

    "Processing" = "Traitement"  
    "Processed : " = "Traité(s) : " 

	"Address Change" = "Relire le Carnet d'adresses"
	"AddressDB is changed. \nDo you want to rescan it?"= ""\
		"Le Carnet d'adresses a été modifié. \nVoulez-vous le relire ?"

/* HappyDays view */
	"Type:" = "Type:"
	"Next Date:" = "Prochain:"
	"Origin:" = "Origine:"
	"Age:" = "Age:"
	"UpTo Date:" = "A ce jour:"
	"%dY %dM %dD (%ld)" = "%dA %dM %dJ (%ld)"

	"Yes" = "Oui"
	"No" = "Non"
END

