TRANSLATION "GERMAN"
BEGIN
    "long_notifySettingMoreString" = ""\
      "Die AN Icon Nummer schlagen Sie bitte im ActionNames Handbuch nach. "\
      "DateBk3 Icons werden aus dem entsprechenden Merkzettel gelesen. "\
      "Wenn Sie keinen DATEBK3 Merkzettel haben, werden auch keine Icons angezeigt.\n"

    "long_customErrorString" = ""\
      "'Geburtstag' ist der Default Benutzerfeld-Name."\
      "Wenn Sie diesen ändern wollen, tippen Sie 'Einstellungen'.\n\n"\
      "WICHTIG: Sie müssen den Kalender aufrufen und mit 'Optionen/"\
      "Benutzerfelder...' ein Benutzerfeld in 'Geburtstag' umbenennen"\
      " oder einen anderen Namen entsprechend Ihren Einstellungen für HappyDays.\n"

    "long_aboutString" = ""\
      "'HappyDays' hilft Ihnen, Geburtstage und ähnliche Ereignisse Ihrer Freunde "\
      "und Verwandten im Überblick zu behalten.\n\n"\
      "Lesen Sie index.html und manual.html um detaillierte Informationen "\
      "zum Gebrauch von HappyDays zu erhalten.\n\n"\
      "HappyDays wird nach den Bedingungen der GNU General "\
      "Public License version 2.0 vertrieben.\n"

    "long_cleanupAlertString" = ""\
      "Einträge werden als HappyDays Ereignis angenommen, wenn sie in der Notiz "\
      "die HappyDays ID im Notizfeld enthalten. Wenn Sie diese auch in Ihren eigenen Einträgen "\
      "verwenden, werden diese ebenfalls entfernt.\n"

    "long_sl2lnString" = ""\
      "-) bedeutet normaler Monat im Lunarkalender\n"\
      "#) bedeutet Schaltmonat im Lunarkalender"

    "long_cantFindAddrString" = ""\
      "Kein Benutzerfeld '%s' im Adressbuch gefunden.\n"\
      "Bitte ein Benutzerfeld umbenennen."

    "Select Time" = "Zeit auswählen"
    "No Time" = "Keine"
    "Invalid input date" = "Ungültige Datumseingabe"
    "Export to Memo Pad is completed." = "Merkzettel Export beendet."

    "SUN" = "SON"
    "MON" = "MON"
    "TUE" = "DIE"
    "WED" = "MIT"
    "THU" = "DON"
    "FRI" = "FRE"
    "SAT" = "SAM"

    "Not enough memory" = "Nicht genug Speicher"
    "%d notify entry is created.\n" = "%d Einträge erzeugt.\n"
    "%d existing entry " = "%d bestehende Einträge "
    "is kept untouched." = "belassen."
    "is modified." = "geändert."

    "Collecting Information" = "Daten werden eingelesen"

    "HappyDays List" = "HappyDays Liste"
    "Look Up:" = "Gehe zu:"

    "HappyDays View" = "HappyDays Tag"
    "Done" = "Fertig"
    "DB" = "Kal"
    "TD" = "Aufg"
    "Goto" = "Gehe zu"

    "Utilities" = "Eintrag"
    "Date Book Notify" = "Termine erzeugen"
    "Cleanup Date Book" = "Termine entfernen"
    "To Do Notify" = "Aufgaben erzeugen"
    "Cleanup To Do" = "Aufgaben entfernen"
    "Export to Memo Pad" = "Merkzettel exportieren"
    "Solar to Lunar" = "Gregor. -> Lunar"
    "Lunar to Solar" = "Lunar -> Gregor."
    "Rescan Address Book" = "Adressbuch neu lesen"

    "Options" = "Optionen"
    "Font..." = "Font..."
    "Preferences" = "Einstellungen"
    "Display Preferences" = "Anzeige Einstellung"
    "About HappyDays" = "Über HappyDays"

    "Edit" = "Bearb."
    "Undo" = "Rückgängig"
    "Cut" = "Ausschneiden"
    "Copy" = "Kopieren"
    "Paste" = "Einfügen"
    "Select All" = "Alles auswählen"
    "Keyboard" = "Tastatur"
    "Graffiti" = "Graffiti-Hilfe"

/* Font... */

/* preferences screen */
    "Custom field:" = "Benutzerfeld:"
    "Instead of system date format" = "Statt System-Datumsformat"
    "Use" = "Verwenden"
    "M/D/Y" = "M/T/J"
    "D/M/Y" = "T/M/J"
    "D.M.Y" = "T.M.J"
    "D-M-Y" = "T-M-J"
    "Y/M/D" = "J/M/T"
    "Y.M.D" = "J.M.T"
    "Y-M-D" = "J-M-T"
    "Address Autoscan" = "Adressbuch Autoscan"
    "Always" = "immer"
    "Ask" = "fragen"
    "Never" = "nie"

    "Notify Format:" = "Eintrag-Format:"
    "[Last, First] E(1) Year" = "[Nachn., Vorn.] E(1) Jahr"
    "[First Last] E(1) Year" = "[Vorn. Nachn.] E(1) Jahr"
    "Event - Last, First Year" = "Ereign. - Nachn., Vorn. Jahr"
    "Event - First Last Year" = "Ereign. - Vorn. Nachn. Jahr"
    "First Last Year" = "Vorn. Nachn. Jahr"

    "Address Book:" = "Adressbuch:"
    "Built-in" = "intern"

    "HappyDays ID:" = "HappyDays ID:"

    "Could not write prefs." = "Einstellungen konnten nicht gespeichert werden."

/* Display preferences */
    "Emphasize Lunar Date" = "Lunardatum hervorheben"

    "Translator" = "Übersetzung: Gunther Zagatta"
    "Translator's email" = "zagatta@web.de"

    "OK" = "OK"
    "Cancel" = "Abbruch"

    "Solar to Lunar Convert" = "Gregor. -> Lunar"
    "Enter Solar date:" = "Gregor. Datum eingeben:"
    "Year must be in 1881-2043" = "Jahr muß zw. 1881 und 2043 liegen"
    "Result Lunar date:" = "Ergebnis Lunar-Datum:"

    "Convert" = "Rechnen"

    "Lunar to Solar Convert" = "Lunar -> Gregor."
    "Enter Lunar date:" = "Lunar-Datum eingeben:"
    "Leap" = "Schaltmon."
    "Result Solar date:" = "Ergebnis Gregor. Datum:"

/* Date Book & To Do Notify */
    "Records:" = "Einträge:"
    "all" = "alle"
    "selected" = "Auswahl"
    "Existing:" = "Vorhandene:"
    "keep" = "lassen"
    "modify" = "ändern"
    "Priority:" = "Priorität:"
    "Category:" = "Kategorie:"
    "Private:" = "Privat:"
    "Alarm:" = "Alarm:"
    "Time:" = "Uhrzeit:"
    "Icon" = "Icon"

    "Repeat for:" = "Wiederholung:"
    "years" = "Jahr(e)"

    "Notify warning" = "Warnung"
    "long_notifywarningString" = ""\
      "^1: Möchten Sie wirklich Einträge für ^2 HappyDays Ereignis(se) erzeugen?"

/* Date Book Icon */
    "Date Book Icon" = "Erweiterte Einstellungen"
    "Icon Support" = "Icons verwenden"
    "AN" = "AN"
    "DateBk3" = "DBk3"
    "AN Icon Number:" = "AN Icon Nummer:"
    "DateBk3 Icon:" = "DateBk3 Icon:"

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "Einträge entfernen"

    "long_removeConfirmString" = ""\
      "Wollen Sie wirklich alle HappyDays Einträge entfernen?"

    "HappyDays says" = "HappyDays meldet"

    "HappyDays Export" = "HappyDays Export"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
      "Möchten Sie die HappyDays Liste als Merkzettel exportieren?"

    "Custom Field Error" = "Benutzerfeld Fehler"
    "Help" = "Hilfe"

    "Invalid event format" = "Ungültiges Ereignis-Format"

    "long_invalidformatString" = ""\
      "Der Adresseintrag für ^1\nenthält ein ungültiges Ereignis. Was soll geschehen?"

    "Ignore" = "Ignorieren"
    "Ignore all" = "Alle Ignor."

    "Cleanup Done" = "Aufräumen beendet"

    "^1: ^2 HappyDays notify entries removed." = ""\
      "^1: ^2 HappyDays Einträge gelöscht."

    "HappyDays Export List" = "HappyDays Export Liste"
    "(not exist in this year)" = "(in diesem Jahr nicht vorhanden)"
    "Please run Date Book once first." = "Bitte vorher den Kalender einmal aufrufen."

    "Days" = "Tage"
    "Date Book" = "Kalender"
    "To Do" = "Aufgaben"
    "Scan note field" = "Notiz auswerten"
    "%ld days left" = "Noch %ld Tag(e)"
    "%ld days passed" = "Vor %ld Tag(en)"

    "Processing" = "Arbeite"
    "Processed : " = "Bearbeitet : "

    "Address Change" = "Adressänderung"
    "AddressDB is changed. \nDo you want to rescan it?" = "Die Adressdatenbank wurde geändert.\nSoll sie neu gelesen werden?"
    "Yes" = "Ja"
    "No" = "Nein"

/* HappyDays view */
    "Type:" = "Typ:"
    "Next Date:" = "Nächster:"
    "Origin:" = "Erster:"
    "Age:" = "Alter:"
    "UpTo Date:" = "Zeit:"
    "%dY %dM %dD (%ld)" = "%dJ %dM %dT (%ld)"

END
