TRANSLATION "GERMAN"
BEGIN
    "long_notifySettingMoreString" =  ""\
      "Diese Notiz kann für Adressbuch Programme von Drittanbietern "\
      "verwendet werden, z.B. Action Names, DateBk3/4.\n"\
      "Sie können damit Icons, Fonts, etc. einstellen. Bitte entnehmen "\
      "Sie weitere Informationen den entsprechenden Programmhandbüchern.\n"
    "long_customErrorString" =  ""\
      "'Geburtstag' ist der Default Benutzerfeld-Name."\
      "Wenn Sie diesen ändern wollen, tippen Sie 'Einstellungen'.\n\n"\
      "WICHTIG: Sie müssen den Kalender aufrufen und mit 'Optionen/"\
      "Benutzerfelder...' ein Benutzerfeld in 'Geburtstag' umbenennen"\
      " oder einen anderen Namen entsprechend Ihren Einstellungen für HappyDays.\n"
    "long_aboutString" =  ""\
      "'HappyDays' hilft Ihnen, Geburtstage und ähnliche Ereignisse Ihrer Freunde "\
      "und Verwandten im Überblick zu behalten.\n\n"\
      "Lesen Sie index.html und manual.html um detaillierte Informationen "\
      "zum Gebrauch von HappyDays zu erhalten.\n\n"\
      "HappyDays wird nach den Bedingungen der GNU General "\
      "Public License version 2.0 vertrieben.\n"
    "long_cleanupAlertString" =  ""\
      "Einträge werden als HappyDays Ereignis angenommen, wenn sie in der Notiz "\
      "die HappyDays ID im Notizfeld enthalten. Wenn Sie diese auch in Ihren eigenen Einträgen "\
      "verwenden, werden diese ebenfalls entfernt.\n"
    "long_removeConfirmString" =  ""\
      "Wollen Sie wirklich alle HappyDays Einträge entfernen?"
    "Invalid input date" =  "Ungültige Datumseingabe"
    "Select Time" =  "Zeit auswählen"
    "No Time" =  "Keine"
    "Export to Memo Pad is completed." =  "Merkzettel Export beendet."
    "long_sl2lnString" =  ""\
      "-) bedeutet normaler Monat im Lunarkalender\n"\
      "#) bedeutet Schaltmonat im Lunarkalender"

    "SUN" =  "SO"
    "MON" =  "MO"
    "TUE" =  "DI"
    "WED" =  "MI"
    "THU" =  "DO"
    "FRI" =  "FR"
    "SAT" =  "SA"

    "SMTWTFS" =  "SMDMDFS"

    "Janunary" =  "Januar"
    "February" =  "Februar"
    "March" =  "März"
    "April" =  "April"
    "May" =  "Mai"
    "June" =  "Juni"
    "July" =  "Juli"
    "August" =  "August"
    "September" =  "September"
    "October" =  "Oktober"
    "November" =  "November"
    "December" =  "Dezember"

    "Not enough memory" =  "Nicht genug Speicher"
    "%d notify entry is created.\n" =  "%d Einträge erzeugt.\n"
    "%d existing entry " =  "%d bestehende Einträge "
    "is kept untouched." =  "belassen."
    "is modified." =  "geändert."
    "HappyDays Export List" =  "HappyDays Export Liste"
    "(not exist in this year)" =  "(in diesem Jahr nicht vorhanden)"
    "Please run Date Book once first." =  "Bitte vorher den Kalender einmal aufrufen."
    "Please run Todo once first."= "Bitte vorher die Aufgaben einmal aufrufen"
    "Days" =  "Tage"
    "%dY %dM %dD (%ld)" =  "%dJ %dM %dT (%ld)"

    "Date Book" =  "Kalender"
    "To Do" =  "Aufgaben"
    "%ld days left" =  "Noch %ld Tag(e)"
    "%ld days passed" =  "Vor %ld Tag(en)"

    "Type:" =  "Typ:"
    "Next Date:" =  "Nächster:"
    "Origin:" =  "Erster:"
    "Age:" =  "Alter:"
    "UpTo Date:" =  "Zeit:"
    "BioRhythm:"= "Biorythmus:"
    "P(%s) E(%s) I(%s)"= "P(%s) E(%s) I(%s)"

    "Datebook Note" =  "Kalender-Notiz"
    "ToDo Note" =  "Aufgaben-Notiz"

    "Collecting Information" =  "Daten werden eingelesen"

    "Look Up:" =  "Gehe zu:"

    "HappyDays View" =  "HappyDays Tag"

    "Done" =  "Fertig"
    "DB" =  "Kal"
    "TD" =  "Aufg"
    "Goto" =  "Gehe zu"

    "Utilities" =  "Eintrag"
    "Date Book Notify" =  "Termine erzeugen"
    "Cleanup Date Book" =  "Termine entfernen"
    "To Do Notify" =  "Aufgaben erzeugen"
    "Cleanup To Do" =  "Aufgaben entfernen"
    "Export to Memo Pad" =  "Merkzettel exportieren"
    "Solar to Lunar" =  "Gregor. -> Lunar"
    "Lunar to Solar" =  "Lunar -> Gregor."
    "Rescan Address Book" =  "Adressbuch neu lesen"

    "Options" =  "Optionen"
    "Font..." =  "Font..."
    "Preferences" =  "Einstellungen"
    "Display Preferences" =  "Anzeige Einstellung"
    "About HappyDays" =  "Über HappyDays"

    "Edit" =  "Bearb."
    "Undo" =  "Rückgängig"
    "Cut" =  "Ausschneiden"
    "Copy" =  "Kopieren"
    "Paste" =  "Einfügen"
    "Select All" =  "Alles auswählen"
    "Keyboard" =  "Tastatur"
    "Graffiti" =  "Graffiti-Hilfe"

    "Emphasize Lunar Date" =  "Lunardatum hervorheben"
    "Display solar/lunar info in View" =  "Kalenderinfo zeigen"
    "OK" =  "OK"
    "Cancel" =  "Abbruch"

    "Custom field:" =  "Benutzerfeld:"

    "Instead of system date format" =  "Statt System-Datumsformat"
    "Use" =  "Verwenden"
    "M/D/Y" =  "M/T/J"
    "D/M/Y" =  "T/M/J"
    "D.M.Y" =  "T.M.J"
    "D-M-Y" =  "T-M-J"
    "Y/M/D" =  "J/M/T"
    "Y.M.D" =  "J.M.T"
    "Y-M-D" =  "J-M-T"

    "Scan note field" =  "Notiz auswerten"
    "Ignore record with prefix '!'" =  "Einträge mit '!' ignorieren"

    "Address Autoscan" =  "Adressbuch Autoscan"
    "Always" =  "immer"
    "Ask" =  "fragen"
    "Never" =  "nie"

    "Notify Format:" =  "Eintrag-Format:"
    "[Last, First] E(1) Year" =  "[Nachn., Vorn.] E(1) Jahr"
    "[First Last] E(1) Year" =  "[Vorn. Nachn.] E(1) Jahr"
    "Event - Last, First Year" =  "Ereign. - Nachn., Vorn. Jahr"
    "Event - First Last Year" =  "Ereign. - Vorn. Nachn. Jahr"
    "First Last Year" =  "Vorn. Nachn. Jahr"

    "Address Book:" =  "Adressbuch:"
    "Built-in" =  "intern"

    "HappyDays ID:" =  "HappyDays ID:"

    "Solar to Lunar Convert" =  "Gregor. -> Lunar"
    "Enter Solar date:" =  "Gregor. Datum eingeben:"
    "Year must be in 1881-2043" =  "Jahr muß zw. 1881 und 2043 liegen"

    "Result Lunar date:" =  "Ergebnis Lunar-Datum:"

    "Convert" =  "Rechnen"

    "Lunar to Solar Convert" =  "Lunar -> Gregor."
    "Enter Lunar date:" =  "Lunar-Datum eingeben:"
    "Leap" =  "Schaltmon."

    "Result Solar date:" =  "Ergebnis Gregor. Datum:"

    "Records:" =  "Einträge:"
    "all" =  "alle"
    "selected" =  "Auswahl"

    "Existing:" =  "Vorhandene:"
    "keep" =  "lassen"
    "modify" =  "ändern"

    "Private:" =  "Privat:"

    "Alarm:" =  "Alarm:"

    "Time:" =  "Uhrzeit:"

    "Repeat for:" =  "Wiederholung:"
    "years" =  "Jahr(e)"

    "Note" =  "Notiz"

    "Add the following note" =  "Folgende Notiz hinzufügen"

    "Priority:" =  "Priorität:"

    "Category:" =  "Kategorie:"

    "HappyDays says" =  "HappyDays meldet"

    "Address Change" =  "Adressänderung"
    "AddressDB is changed. \nDo you want to rescan it?" =  "Die Adressdatenbank wurde geändert.\nSoll sie neu gelesen werden?"
    "Yes" =  "Ja"
    "No" =  "Nein"

    "HappyDays Export" =  "HappyDays Export"
    "Would you like to export HappyDays List to Memo Pad?" =  ""\
      "Möchten Sie die HappyDays Liste als Merkzettel exportieren?"

    "HappyDays Cleanup" =  "Einträge entfernen"

    "Notify warning" =  "Warnung"
    "long_notifywarningString" =  ""\
      "^1: Möchten Sie wirklich Einträge für ^2 HappyDays Ereignis(se) erzeugen?"

    "Invalid event format" =  "Ungültiges Ereignis-Format"
    "long_invalidformatString" =  ""\
      "Der Adresseintrag für ^1\nenthält ein ungültiges Ereignis. Was soll geschehen?"
    "Ignore" =  "Ignorieren"
    "Ignore all" =  "Alle Ignor."

    "Cleanup Done" =  "Aufräumen beendet"
    "^1: ^2 HappyDays notify entries removed." =  ""\
      "^1: ^2 HappyDays Einträge gelöscht."

    "Translator" =  "Übersetzung: Gunther Zagatta"
    "Translator's email" =  "zagatta@web.de"

    "Help" =  "Hilfe"

    "Processing" =  "Arbeite"
    "Processed : " =  "Bearbeitet : "
END

