TRANSLATION "ITALIAN"
BEGIN
	"long_notifySettingMoreString" = ""\
        "Solo per utenti esperti\n\n"\
        "Questa nota è usata per programmi di agende di terze parti "\
        "come Action Names, DateBk3/4.\n\n"\
        "E' possibile settare una icona, il font e altro usando questa nota.\n\n"\
        "Per ulteriori informazioni, riferirsi al manuale dei programmi.\n"

    "long_aboutString" = ""\
    "'HappyDays' ti aiuterà a ricordare i compleanni e gli anniversari "\
    "dei tuoi amici e familiari, ma anche altri eventi.\n\n"\
    "Visita il sito http://jmjeong.com/?HappyDays per informazioni dettagliate "\
    "su come usare HappyDays.\n\n"\
    "HappyDays è distribuito sotto i termini della GNU General "\
    "Public License version 2.0.\n\n"\
	"= Input Format\n\n"\
	"[*[{EventType}]\\ws{Description}\\ws{Date}[[nth day list]]\n"

    "long_cleanupAlertString" = ""\
    "Le Notifiche inserite sono processate da HappyDays se hanno "\
	"{HappyDays ID} nel loro campo Nota. "\ 	
    "Se utilizzi questo formato per i tuoi "\
    "inserimenti, anche questo record sarà eliminato da Ripulisci.\n"

    "long_sl2lnString" = ""\
        "-) significa mese lunare normale\n"\
        "#) significa mese lunare bisestile"

    "Select Time" = "Seleziona Orario"
    "No Time" = "Nessun Orario"
    "Invalid input date" = "Data Immessa Non Valida"
    "Export to Memo Pad is completed." = "Esportazione al Blocco note completata."

    "SUN"   = "DOM"
    "MON"   = "LUN"
    "TUE"   = "MAR"
    "WED"   = "MER"
    "THU"   = "GIO"
    "FRI"   = "VEN"
    "SAT"   = "SAB"

    "Not enough memory" = "Memoria Insufficiente"
    "%d notify entries have been created.\n" = "%d notifiche create.\n" 
    "%d existing entries " = "%d notifiche già esistenti "
    "are kept untouched." = "non modificate."
    "have been modified." = "modificate."

    "Collecting Information..." = "Raccolta Informazioni..."

    "Look Up:" = "Cerca:"

    "HappyDays View" = "HappyDays Vista"
    "Done"  = "Fatto"
    "DB" = "Agenda" 
    "TD" = "Impegni"
    "Goto" = "Vai"

    "Utilities" = "Utilità"
    "Date Book Notify" = "Notifica su Agenda"
    "Cleanup Date Book"  = "Ripulisci Agenda"
    "To Do Notify" = "Notifica su Impegni"
    "Cleanup To Do"  = "Ripulisci Impegni"
    "Export to Memo Pad" = "Esporta al Blocco note"
    "Solar to Lunar" = "Da Solare a Lunare"
    "Lunar to Solar" = "Da Lunare a Solare"
	"Rescan Address Book" = "Riesamina Rubrica"

    "Options" = "Opzioni"
	"Font..." = "Font..."
    "Preferences" = "Preferenze"
	"Display Preferences" = "Opzioni visualizzazione"
    "About HappyDays" = "Info su HappyDays"

    "Edit" = "Modifica"
    "Undo" = "Annulla"
    "Cut" = "Taglia"
    "Copy" = "Copia" 
    "Paste" = "Incolla" 
    "Select All" = "Seleziona Tutto" 
    "Keyboard" = "Tastiera" 
    "Graffiti" = "Graffiti"


/* Font... */

/* preferences screen */
    "Custom field:" = "Campo personale:"
    "Instead of system date format" = "Come Formato Data"  
    "Use" = "Usa"  
    "M/D/Y" = "M/G/A"  
    "D/M/Y" = "G/M/A"  
    "D.M.Y" = "G.M.A"  
    "D-M-Y" = "G-M-A"  
    "Y/M/D" = "A/M/G"  
    "Y.M.D" = "A.M.G"  
    "Y-M-D" = "A-M-G"  
	"Address Autoscan" = "Esamina Rubrica"
	"Always" = "Sempre"
	"Ask" = "Domanda"
	"Never" = "Mai"

    "Notify Format:" = "Formato di Notifica:"  
    "[Last, First] E(1) Year" = "[Cognome, Nome] E(1) Età"  
    "[First Last] E(1) Year" = "[Nome Cognome] E(1) Età"  
        "[First] E(1) Year" = "[Nome] E(1) Età" 
    "Event - Last, First Year" = "Evento - Cognome, Nome Età"  
    "Event - First Last Year" = "Evento - Nome Cognome Età"  
    "First Last Year" = "Nome Cognome Età"  
    
	"Address Book:" = "Rubrica:"
	"Built-in" = "Interna"


/* Display preferences */
    "Emphasize Lunar Date" = "Enfatizza Calendario Lunare"


/* About HappyDays */	
	"GPL free software" = "GPL software gratuito"
	"E-Mail & Web Page" = "E-Mail & Pagina Web"

    "Translator" = "Versione Italiana Andrea Monteriù"
    "Translator's email" = "monteriu@tin.it"


    "OK" = "OK"
    "Cancel" = "Annulla"

    "Solar to Lunar Convert" = "Da Solare a Lunare"
    "Enter Solar date:" = "Immetti la data Solare:"
    "Year must be in 1881-2043" = "Anno incluso in 1881-2043"
    "Result Lunar date:" = "Data Lunare Risultante:"

    "Convert" = "Converti"

    "Lunar to Solar Convert" = "Da Lunare a Solare"
    "Enter Lunar date:" = "Immetti la data Lunare:"
    "Leap" = "Bisestile"
    "Result Solar date:" = "Data Solare Risultante:"


/* Date Book & To Do Notify */
    "Records:" = "Registri:"
      "all" = "tutti"
      "selected" = "scelti" 
    "Existing:" = "Esistente:"
      "keep" = "tieni"
      "modify" = "modifica"
    "Priority:" = "Priorità:"
    "Category:" = "Categoria:"
    "Private:" = "Privato:"
    "Alarm:" = "Sveglia:"
    "Time:" = "Ora:"
    "Icon" = "Icona"

    "Repeat for:" = "Ripeti ogni:"
    "years" = "anno/i"

    "Notify warning" = "Avviso di notifica" 
	"long_notifywarningString" = ""\
  		"^1: Sei sicuro di voler creare le notifiche dei "\
		"^2 record di HappyDays?" 
      
/* Date Book Icon */
    "Date Book Icon" = "Icona Agenda"  
      "Icon Support" = "Supporto Icona"  
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "Numero Icona AN:"  
      "DateBk3 Icon:" = "Icona DateBk3:"  

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "Ripulisci HappyDays" 

    "long_removeConfirmString" = ""\
    "Sei sicuro di voler cancellare tutte "\
    "le notifiche HappyDays?"



    "HappyDays Export" = "Esporta HappyDays"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
    	"Vorresti esportare la Lista HappyDays al Blocco note?" 

    "Custom Field Error" = "Campo Personale Errato"
    "Help" = "Aiuto" 


    "Invalid event format" = "Formato evento non valido" 

	"long_invalidformatString" = ""\
    	"Il registro indirizzi \n[^1]\n contiene un evento non valido. "\
		"Come vorresti modificarlo?" 

    "Ignore" = "Ignora" 
    "Ignore all" = "Ignora tutto" 

    "Cleanup Done" = "Pulizia Eseguita" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    	"^1: ^2 notifiche HappyDays sono state eliminate." 

    "HappyDays Export List" = "Lista HappyDays da Esportare" 
    "(not exist in this year)" = "(non esiste in questo anno)" 
    "Please run Date Book once first." = "Per favore avvia l'Agenda una prima volta."  
    
    "Days" = "Giorni"  
    "Date Book" = "Agenda"  
    "To Do" = "Impegni"  
    "Scan note field" = "Esamina il campo nota"  
    "%ld days left" = "%ld giorni mancanti"  
    "%ld days passed" = "%ld giorni trascorsi"  

    "Processing" = "Elaborazione"  
    "Processed : " = "Elaborato : " 

	"Address Change" = "Indirizzi Modificati"
	"AddressDB is changed. \nDo you want to rescan it?"= ""\
		"La Rubrica è stata modificata. \nVoui riesaminarla?"

        "Ignore record with prefix '!'" = "Ignora record con prefisso '!'"
 	"Datebook note" = "Nota per Agenda"
 	"Add the following note" = "Aggiungi la seguente nota"

/* HappyDays view */
	"Type:" = "Tipo:"
	"Next Date:" = "Prossimo:"
	"Origin:" = "Origine:"
	"Age:" = "Età:"
	"UpTo Date:" = "Scadenza:"
	"%dY %dM %dD (%ld)" = "%dA %dM %dG (%ld)"

	"Yes" = "Si"
	"No" = "No"
END


