TRANSLATION "KOREAN"
BEGIN
	"long_notifySettingMoreString" = ""\
	"AN 사용자는 Action Names 매뉴얼을 참조하여 숫자를 입력하면 됨. "\
	"DateBk3 아이콘은 메모장으로부터 읽어서 화면에 표시합니다. 메모장에 "\
	"아이콘 데이터가 없는 경우에는 아무것도 표시되지 않습니다.\n"

    "long_customErrorString" = ""\
    "'Birthday'가 초기 사용자정의 필드 이름입니다."\
    "다른 이름을 설정하고 싶은 경우 "\
    "'설정'을 누르세요.\n\n"\
    "정보: 'Birthday' 사용자정의 필드를 바꾸기 위해서는 주소록을 수행시켜 "\
    "'Options/Rename Custom Fields'을 선택한 다음 수정하면 됩니다."\
    "혹은 HappyDays의 설정 항목의 사용자정의 필드를 적절하게 수정하세요.\n"

    "long_aboutString" = ""\
    "'HappyDays'는 친구나 가족의 생일이나 기념일을 기억하는 것을 도와"\
    "줍니다. 더욱이 제사나 다른 이벤트 항목도 관리할 수 있습니다.\n\n"\
    "주소록의 사용자정의 필드중 하나를 'Birthday'로 수정하세요."\
	"\n\nHappyDays를 사용하는 법에 대한 자세한 정보는 index.html과 "\
	"manual.html 파일을 참고하세요."\
	"\n\nHappyDays는 GNU GPL을 따릅니다.\n"

    "long_cleanupAlertString" = ""\
    "알림 레코드의 메모 필드에 {HD 식별자}가 있는 경우 "\
    "HappyDays 레코드로 "\
    "간주하고 삭제합니다. (주의 요망)\n"

    "long_sl2lnString" = ""\
        "-)는 음력 평달을 의미합니다.\n"\
        "#)은 음력 윤달을 의미합니다."

    "long_cantFindAddrString" = ""\
        "주소록에서 사용자정의 필드를 못 찾음: '%s'\n"\
        "주소록의 사용자정의 필드 항목 이름을 변경하세요."

    "Select Time" = "알람 시간"
    "No Time" = "지정안됨"
    "Invalid input date" = "날짜 입력이 잘못되었습니다."
    "Export to Memo Pad is completed." =
                "메모장으로 성공적으로 옮겨졌습니다."

    "SUN"   = "일"
    "MON"   = "월"
    "TUE"   = "화"
    "WED"   = "수"
    "THU"   = "목"
    "FRI"   = "금"
    "SAT"   = "토"

    "Not enough memory" = "메모리 부족"
    "%d notify entry is created.\n" =
        "%d 개의 알림 레코드가 생성되었습니다.\n"
    "%d existing entry " = "%d 개의 존재하는 레코드"
    "is kept untouched." = "를 그대로 유지했습니다."
    "is modified." = "가 수정되었습니다."

    "Collecting Information..." = ""\
        "주소록으로부터 정보 수집중..."

    "HappyDays List" = "HappyDays 목록"
	"Look Up:" = "기준일:"

    "HappyDays View" = "HappyDays 보기"
    "Done"  = "완료"
    "DB" = "DB"
    "TD" = "TD"
    "Goto" = "이동"

    "Utilities" = "유틸리티 "
    "Date Book Notify" = "일정관리에 알림 "
    "Cleanup Date Book"  = "일정관리에서 정리 "
	"To Do Notify" = "할 일에 알림 "
	"Cleanup To Do"  = "할 일에서 정리 "
    "Export to Memo Pad" = "메모장으로 전송 "
    "Solar to Lunar" = "양력을 음력으로 "
    "Lunar to Solar" = "음력을 양력으로 "
	"Rescan Address Book" = "주소록 재검색 "

    "Options" = "옵션 "
	"Font..." = "글꼴..."
    "Preferences" = "설정 "
	"Display Preferences" = "화면 설정 "
    "About HappyDays" = "HappyDays란? "

    "Edit" = "수정"
    "Undo" = "되돌리기"
    "Cut" = "자르기"
    "Copy" = "복사"
    "Paste" = "붙이기"
    "Select All" = "전체 선택"
    "Keyboard" = "키보드"
    "Graffiti" = "그래피티"

/* Font... */

/* preferences screen */
    "Custom field:" = "사용자정의 필드 :"
    "Instead of system date format" = "시스템 날짜 형식 대신에"
    "Use" = "사용할 형식"
    "M/D/Y" = "M/D/Y"
    "D/M/Y" = "D/M/Y"
    "D.M.Y" = "D.M.Y"
    "D-M-Y" = "D-M-Y"
    "Y/M/D" = "Y/M/D"
    "Y.M.D" = "Y.M.D"
    "Y-M-D" = "Y-M-D"
	"Scan note field" = "주소록의 노트 필드 읽기"
	"Address Autoscan" = "주소록 자동읽기"
	"Always" = "항상"
	"Ask" = "묻기"
	"Never" = "안함"

	"Notify Format:" = "알림 레코드 형식: "
	"[Last, First] E(1) Year" = "[성, 이름] E(1) 나이"
	"[First Last] E(1) Year" = "[이름 성] E(1) 나이"
	"Event - Last, First Year" = "행사 - 성, 이름 나이"
	"Event - First Last Year" = "행사 - 이름 성 나이"
	"First Last Year" = "이름 성 나이"

	"Address Book" = "주소록"
	"Built-in" = "주소록"

/* Display preferences */
    "Emphasize Lunar Date" = "음력강조"

/* About Happydays */
    "GPL free software" = "GPL free software"
	"E-Mail & Web Page" = "이메일 & 웹페이지"

    "Translator" = "한글 버젼"
    "Translator's email" = "정재목"

    "OK" = "승인"
    "Cancel" = "취소"

    "Solar to Lunar Convert" = "양력을 음력으로 변환"
    "Enter Solar date:" = "양력 날짜는 :"
    "Year must be in 1881-2043" = "1881년에서 2043년까지만 지원"

    "Result Lunar date:" = "변환된 음력 날짜 :"

    "Convert" = "변환"

    "Lunar to Solar Convert" = "음력을 양력으로 변환"
    "Enter Lunar date:" = "음력 날짜는 :"
    "Leap" = "윤달"

    "Result Solar date:" = "변환된 양력 날짜 :"

/* Date Book & To Do Notify */
    "Records:" = "레코드 :"
      "all" = "전부"
      "selected" = "선택"
    "Existing:" = "기존 레코드 :"
      "keep" = "유지"
      "modify" = "수정"
	"Priority:" = "우선순위 :"
	"Category:" = "카테고리 :"
    "Private:" = "개인용 :"
    "Alarm:" = "알람 :"
    "Time:" = "시간 :"
    "Icon" = "아이콘"

    "Repeat for:" = "몇 년간 :"
    "years" = "년"

    "Notify warning" = "알림 경고"
	"long_notifywarningString" = ""\
		"^1: ^2 개의 HappyDays에 대한 알림 레코드를 만들기 원하십니까?"

/* Date Book Icon */
	"Date Book Icon" = "아이콘 설정"
		"Icon Support" = "아이콘 지원"
		"AN" = "AN"
		"DateBk3" = "DateBk3"
		"AN Icon Number:" = "AN 아이콘 번호: "
		"DateBk3 Icon:" = "DateBk3 아이콘: "

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "HappyDays 정리"

    "long_removeConfirmString" = ""\
    "모든 HappyDays 알림 항목을 삭제하길 원하십니까?"

    "HappyDays says" = "정 보"

    "HappyDays Export" = "HappyDays 전송"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
        "메모장으로 HappyDays 목록을 옮길까요?"


    "Custom Field Error" = "사용자정의 필드 에러"
    "Help" = "도움말"


    "Invalid event format" = "잘못된 이벤트 포맷"
	"long_invalidformatSTring" = ""\
    	"주소록 레코드 ^1\n의 포맷이 잘못되어 있습니다. 어떻게 처리할까요?"

    "Ignore" = "무시"
    "Ignore all" = "전부 무시"

    "Cleanup Done" = "정리작업 완료"

	"^1: ^2 HappyDays notify entries removed." = ""\
	"^1: ^2 개의 HappyDays 알림 레코드가 제거되었습니다."

	"HappyDays Export List" = "HappyDays 목록"

    "(not exist in this year)" = "(올해엔 없는 날입니다)"
    "Please run Date Book once first." = "먼저 일정관리를 한번 수행하세요."

    "Days" = "일전"
	"Date Book" = "일정관리"
	"To Do" = "할 일"
    "%d day(s) left" = "%d 일 남았습니다"
    "%d day(s) passed" = "%d 일 지났습니다"
	
	"Processing" = "진행중"
	"Processed : " = "처리된것 : "

	"Address Change" = "주소록 변경"
	"AddressDB is changed. \nDo you want to rescan it?" = ""\
		"주소록이 변경되었습니다.\n다시 읽을까요?"

/* HappyDays view */
	"Type:" = "종류:"
	"Next Date:" = "다음 기념일:"
	"Origin:" = "기념일:"
	"Age:" = "연령:"
	"UpTo Date:" = "남은 기간:"
	"%dY %dM %dD (%d)" = "%d년 %d월 %d일 (총 %d일)"
END
