TRANSLATION "NORWEGIAN"
BEGIN
	"long_notifySettingMoreString" = ""\
	"For å finne nummeret til et AN-ikon, må du slå opp i bruks-"\
	"anvisningen for Action Names. DateBk3 ikonene hentes fra memoblokka."\ 
	"Hvis du ikke har en DateBk3-ikon innføring i memoblokka, "\
	"vil ikke HappyDays kunne bruke ikoner.\n"

    "long_customErrorString" = ""\
    "'Fødselsdag' er standard navn for brukerfelt."\
    "For å sette et annet standardnavn på brukerfeltet,"\
    " velg 'Preferanser'.\n\n"\
    "VIKTIG: Du må også starte Adresseboka og velge 'Options/"\
    "Rename Custom Fields' for å døpe om et brukerfelt til 'Fødselsdag'"\
    " eller det du evt. valgte i Preferansene til HappyDays.\n"

    "long_aboutString" = ""\
    "'HappyDays' hjelper deg å huske fødsels- og bryllupsdagene "\
    "til familie og venner, så vel som andre hendelser.\n\n"\
    "Se index.html og manual.html filene for detaljert informasjon "\
    "om bruken av HappyDays\n\n"\
    "HappyDays distribueres under vilkårene satt i GNU General "\
    "Public License versjon 2.0.\n"

    "long_cleanupAlertString" = ""\
    "Påminnelser regnes for å tilhøre HappyDays hvis de har "\
	"{HappyDays ID} i memo-feltet. "\ 	
    "Hvis du bruker dette formatet i egne innføringer "\
    "kan de bli slettet.\n"

    "long_sl2lnString" = ""\
        "-) bet.  normal måned i lunar\n"\
        "#) bet. skuddmåned i lunar"

    "long_cantFindAddrString" = ""\
    "Finner ikke brukervalgt felt i adresseboka: '%s'\n"\
    "Vennligst døp om et brukervalgt felt i adresseboka di."

    "Select Time" = "Velg tidspunkt"
    "No Time" = "No Time"
    "Invalid input date" = "Du har oppgitt en gyldig dato"
    "Export to Memo Pad is completed." = "Eksport til memoblokk er fullført."

    "SUN"   = "søn"
    "MON"   = "man"
    "TUE"   = "tir"
    "WED"   = "ons"
    "THU"   = "tor"
    "FRI"   = "fre"
    "SAT"   = "lør"

    "Not enough memory" = "Ikke nok minne"
    "%d notify entry is created.\n" = "%d oppføringer ble opprettet.\n" 
    "%d existing entry " = "%d eksisterende oppføringer "
    "is kept untouched." = "er beholdt."
    "is modified." = "er forandret."

    "Collecting Information..." = "Samler Informasjon..."

    "HappyDays List" = "HappyDays liste"
    "Look Up:" = "Finn:"

    "HappyDays View" = "HappyDays dag"
    "Done"  = "Ferdig"
    "DB" = "DB" 
    "TD" = "TD"
    "Goto" = "Gå til"

    "Utilities" = "Utilities"
    "Date Book Notify" = "Påminn i dagboken"
    "Cleanup Date Book"  = "Rydd i dagboken"
    "To Do Notify" = "Påminn i Huskelista"
    "Cleanup To Do"  = "Rydd i huskelista"
    "Export to Memo Pad" = "Eksportér til notisblokk"
    "Solar to Lunar" = "Gregor. til lunar"
    "Lunar to Solar" = "Lunar til gregor."
	"Rescan Address Book" = "Skann adresseboka på nytt"

    "Options" = "Valg"
	"Font..." = "Font..."
    "Preferences" = "Preferanser"
	"Display Preferences" = "Visningspreferanser"
    "About HappyDays" = "Om HappyDays"

    "Edit" = "Redigér"
    "Undo" = "Gjør om"
    "Cut" = "Klipp"
    "Copy" = "Kopiér" 
    "Paste" = "Lim inn" 
    "Select All" = "Velg alle" 
    "Keyboard" = "Tastatur" 
    "Graffiti" = "Graffiti"


/* Font... */

/* preferences screen */
    "Custom field:" = "Custom field:"
    "Instead of system date format" = "Bruk istedenfor datoformat"  
    "Use" = "Bruk"  
    "M/D/Y" = "M/D/Å"  
    "D/M/Y" = "D/M/Å"  
    "D.M.Y" = "D.M.Å"  
    "D-M-Y" = "D-M-Å"  
    "Y/M/D" = "Å/M/D"  
    "Y.M.D" = "Å.M.D"  
    "Y-M-D" = "Å-M-D"  
	"Address Autoscan" = "Automatisk adressesøk"
	"Always" = "Alltid"
	"Ask" = "Spør"
	"Never" = "Aldri"

    "Notify Format:" = "Format for oppføringen:"  
    "[Last, First] E(1) Year" = "[Fnavn, Enavn] H(1) år"  
    "[First Last] E(1) Year" = "[Fnavn Enavn] H(1) år"  
    "Event - Last, First Year" = "Hendelse - Enavn, Fnavn år"  
    "Event - First Last Year" = "Hendelse - Fnavn Enavn år"  
    "First Last Year" = "Fnavn Enavn år"  
    
	"Address Book:" = "Adressebok:"
	"Built-in" = "Innebygd"


/* Display preferences */
    "Emphasize Lunar Date" = "Uthev lunar dato"


/* About HappyDays */	
	"GPL free software" = "GPL fri programvare"
	"E-Mail & Web Page" = "E-post og Webside"

    "Translator" = "Norsk utgave: Knut Zakariassen"
    "Translator's email" = "knut@zakariassen.net"


    "OK" = "OK"
    "Cancel" = "Avbryt"

    "Solar to Lunar Convert" = "Konvertér gregor. -> lunar kal."
    "Enter Solar date:" = "Oppgi gregor.  dato:"
    "Year must be in 1881-2043" = "Årstall må være mellom  1881-2043"
    "Result Lunar date:" = "Korresp. lunar dato:"

    "Convert" = "Konvertér"

    "Lunar to Solar Convert" = "Lunar til gregor. kalender"
    "Enter Lunar date:" = "Oppgi lunar dato:"
    "Leap" = "Skudd"
    "Result Solar date:" = "Korresp. Solar dato:"


/* Date Book & To Do Notify */
    "Records:" = "Opptegnelse:"
      "all" = "alle"
      "selected" = "valgte" 
    "Existing:" = "Eksisterende:"
      "keep" = "behold"
      "modify" = "endre"
    "Priority:" = "Prioritet:"
    "Category:" = "Kategori:"
    "Private:" = "Privat:"
    "Alarm:" = "Alarm:"
    "Time:" = "Tid:"
    "Icon" = "Ikon"

    "Repeat for:" = "Repeter i:"
    "years" = "år"

    "Notify warning" = "OBS!" 
	"long_notifywarningString" = ""\
  		"^1:Vil du lage påminnelser for "\
		"^2 HappyDays oppføringer?" 
      
/* Date Book Icon */
    "Date Book Icon" = "Ikoner i dagboken"  
      "Icon Support" = "Støtte for ikoner"  
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "AN ikonnummer:"  
      "DateBk3 Icon:" = "DateBk3 ikon:"  

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "HappyDays opprydding" 

    "long_removeConfirmString" = ""\
    "Ønsker du å fjerne alle påminnelser "\
    "laget av HappyDays?"



    "HappyDays says" = "HappyDays sier"

    "HappyDays Export" = "HappyDays eksport"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
    	"Ønsker du å eksportere lista fra HappyDays til memoblokka?" 

    "Custom Field Error" = "Feil i brukervalgt felt"
    "Help" = "Hjelp" 


    "Invalid event format" = "Ugyldig hendelsesformat" 

	"long_invalidformatString" = ""\
    	"Adresseoppføringen for\n[^1]\n inneholder ugyldige data. "\
		"Hva ønsker du å gjøre med det?" 

    "Ignore" = "Ignorér" 
    "Ignore all" = "Ignorér alle" 

    "Cleanup Done" = "Opprydding utført" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    	"^1: ^2 HappyDays påminnelser fjernet." 

    "HappyDays Export List" = "Eksportert fra HappyDays " 
    "(not exist in this year)" = "(finnes ikke i dette året)" 
    "Please run Date Book once first." = "Kjør dagboka en gang først."  
    
    "Days" = "Dager"  
    "Date Book" = "Dagbok"  
    "To Do" = "Huskeliste"  
    "Scan note field" = "Skann notisfeltet"  
    "%ld days left" = "%ld dager igjen"  
    "%ld days passed" = "%ld dager siden"  

    "Processing" = "Arbeider"  
    "Processed : " = "Ferdig : " 

	"Address Change" = "Omscanning av Adresser"
	"AddressDB is changed. \nDo you want to rescan it?"= ""\
		"AdresseDBasen er endret. \nØnsker du å laste den på nytt?"

/* HappyDays view */
	"Type:" = "Type:"
	"Next Date:" = "Neste Dato:"
	"Origin:" = "Opphav:"
	"Age:" = "Alder:"
	"UpTo Date:" = "Frem til dato:"
	"%dY %dM %dD (%ld)" = "%dD %dM %dY (%ld)"

	"Yes" = "Ja"
	"No" = "Nei"
END










