TRANSLATION "RUSSIAN"
BEGIN
	"long_notifySettingMoreString" = ""\
	"Номера значков AN см. в документации на Action Names. Значки DateBk3 "\
	"считываются из Блокнота. Если у Вас нет записи DateBk3 Icon в блокноте, "\
	"то не отображается ничего.\n"

    "long_customErrorString" = ""\
    "По умолчанию используется дополнительное поле 'Birthday'."\
    "Чтобы использовать поле с другим названием, "\
    "выберите 'Установки' из меню 'Опции'.\n\n"\
    "ВАЖНО: Вы должны открыть Адреса и выбрать 'Переименовать поля' "\
    "из меню 'Опции', чтобы переименовать одно из дополнительных полей "\
    "в 'Birthday' или в то, что вы выбрали в Установках этой программы.\n"

    "long_aboutString" = ""\
    "Программа 'Даты' поможет Вам не забыть о днях рождения Ваших друзей "\
    "и членов семьи, годовщинах и других событиях.\n\n"\
    "См. файлы index.html и manual.html из комплекта программы для более "\
    "детальной информации об использовании программы 'Даты'\n\n"\
    "Программа 'Даты' распространяется на условиях лицензии GNU General "\
    "Public License версии 2.0.\n"

    "long_cleanupAlertString" = ""\
    "Уведомительные записи считаются 'Датами' если у них в заметке "\
    "содержится специальный идентификатор. "\ 	
    "Если Вы используете подобный формат в своих собственных записях, "\
    "то Вы рискуете, что они будут удалены по команде 'Очистка'.\n"

    "long_sl2lnString" = ""\
        "-) means plain month in lunar\n"\
        "#) means leap month in lunar"

    "long_cantFindAddrString" = ""\
    "Не могу найти дополнительное поле '%s' в Адресах\n"\
    "Пожалуйста переименуйте одно из дополнительных полей."

    "Select Time" = "Выбор времени"
    "No Time" = "Без времени"
    "Invalid input date" = "Не верная дата"
    "Export to Memo Pad is completed." = "Экспорт в Блокнот завершен"

    "SUN"   = "Вс"
    "MON"   = "Пн"
    "TUE"   = "Вт"
    "WED"   = "Ср"
    "THU"   = "Чт"
    "FRI"   = "Пт"
    "SAT"   = "Сб"

    "Not enough memory" = "Недостаточно памяти"
    "%d notify entry is created.\n" = "Уведомлений создано: %d\n" 
    "%d existing entry " = "Старых записей: %d "
    "is kept untouched." = "(оставлено)"
    "is modified." = "(обновлено)"

    "Collecting Information..." = "Собираю информацию..."

    "Look Up:" = "Искать:"

    "HappyDays View" = "Просмотр Даты"
    "Done"  = "Выход"
    "DB" = "Р" 
    "TD" = "Д"
    "Goto" = "Адреса"

    "Utilities" = "Команды"
    "Date Book Notify" = "Уведомлять в Расписании"
    "Cleanup Date Book"  = "Подчистить Расписание"
    "To Do Notify" = "Уведомлять в Делах"
    "Cleanup To Do"  = "Подчистить Дела"
    "Export to Memo Pad" = "Экспортировать в Блокнот"
    "Solar to Lunar" = "Перевод в лунный календ."
    "Lunar to Solar" = "Перевод из лунного календ."
	"Rescan Address Book" = "Пересканировать Адреса"

    "Options" = "Опции"
	"Font..." = "Шрифт..."
    "Preferences" = "Установки"
	"Display Preferences" = "Отображение"
    "About HappyDays" = "О программе"

    "Edit" = "Правка"
    "Undo" = "Отмена"
    "Cut" = "Вырезать"
    "Copy" = "Копировать" 
    "Paste" = "Вставить" 
    "Select All" = "Выбрать всё" 
    "Keyboard" = "Клавиатура" 
    "Graffiti" = "Graffiti"


/* Font... */

/* preferences screen */
    "Custom field:" = "Название поля:"
    "Instead of system date format" =
    "Использовать этот формат"  
    "Use" = "даты"  
    "M/D/Y" = "М/Д/Г"  
    "D/M/Y" = "Д/М/Г"  
    "D.M.Y" = "Д.М.Г"  
    "D-M-Y" = "Д-М-Г"  
    "Y/M/D" = "Г/М/Д"  
    "Y.M.D" = "Г.М.Д"  
    "Y-M-D" = "Г-М-Д"  
	"Address Autoscan" = "Автоскан Адресов"
	"Always" = "Всегда"
	"Ask" = "Запрос"
	"Never" = "Никогда"

    "Notify Format:" = "Формат уведомления:"  
    "[Last, First] E(1) Year" = "[Фамилия, Имя] С(1) Год"  
    "[First Last] E(1) Year" = "[Имя Фамилия] С(1) Год"  
    "Event - Last, First Year" = "Событие - Фамилия, Имя Год"  
    "Event - First Last Year" = "Событие - Имя Фамилия Год"  
    "First Last Year" = "Имя Фамилия Год"  
    
	"Address Book:" = "Адресная книга:"
	"Built-in" = "Адреса (встр)"


/* Display preferences */
    "Emphasize Lunar Date" = "Выделять лунные даты"


/* About HappyDays */	
	"GPL free software" = "GPL free software"
	"E-Mail & Web Page" = "E-Mail & Web Page"

    "Translator" = "Русский перевод"
    "Translator's email" = "Александр Амелькин"


    "OK" = "OK"
    "Cancel" = "Отмена"

    "Solar to Lunar Convert" = "Лунный календарь"
    "Enter Solar date:" = "Введите солнечную дату:"
    "Year must be in 1881-2043" = "Год должен быть 1881-2043"
    "Result Lunar date:" = "Лунная дата:"

    "Convert" = "Перевод"

    "Lunar to Solar Convert" = "Лунный календарь"
    "Enter Lunar date:" = "Введите лунную дату:"
    "Leap" = "Leap"
    "Result Solar date:" = "Солнечная дата:"


/* Date Book & To Do Notify */
    "Records:" = "Записи:"
      "all" = "все"
      "selected" = "данная" 
    "Existing:" = "Старые:"
      "keep" = "сохр"
      "modify" = "замен"
    "Priority:" = "Приоритет:"
    "Category:" = "Категория:"
    "Private:" = "Личная:"
    "Alarm:" = "Сигнал:"
    "Time:" = "Время:"
    "Icon" = "Значок"

    "Repeat for:" = "Повторять:"
    "years" = "лет"

    "Notify warning" = "Запрос на уведомление" 
	"long_notifywarningString" = ""\
  		"^1: Вы уверены, что хотите создать уведомительные записи для "\
		"^2 Дат(ы)?" 
      
/* Date Book Icon */
    "Date Book Icon" = "Значок Расписания"  
      "Icon Support" = "Поддержка значков"  
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "Номер значка AN:"  
      "DateBk3 Icon:" = "Значок DateBk3:"  

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "Очистка Дат" 

    "long_removeConfirmString" = ""\
    "Вы уверены, что хотите удалить все уведомительные записи, "\
    "созданные Датами?"



    "HappyDays says" = "Даты сообщают"

    "HappyDays Export" = "Экспорт Дат"

    "Would you like to export HappyDays List to Memo Pad?" = ""\
    	"Вы хотите экспортировать список Дат в Блокнот?"

    "Custom Field Error" = "Ошибка в доп. поле"
    "Help" = "Помощь" 


    "Invalid event format" = "Неверный формат события" 

	"long_invalidformatString" = ""\
    	"Адресная запись для\n"\
    	"[^1]\n"\
    	"содержит неверное событие. Что будем делать?" 

    "Ignore" = "Пропуск" 
    "Ignore all" = "Пропуск всех" 

    "Cleanup Done" = "Очистка окочена" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    	"[^1] Уведомлений удалено: ^2" 

    "HappyDays Export List" = "Список Дат" 
    "(not exist in this year)" = "(нет в этом году)" 
    "Please run Date Book once first." = "Пожалуйста сперва запустите Расписание"  
    
    "Days" = "Дней"  
    "Date Book" = "Расписание"  
    "To Do" = "Дела"  
    "Scan note field" = "Сканировать заметки"  
    "%ld days left" = "осталось дней: %ld"  
    "%ld days passed" = "прошло дней: %ld"  

    "Processing" = "Обработка"  
    "Processed : " = "Обработано : " 

	"Address Change" = "Сканирование Адресов"
	"AddressDB is changed. \nDo you want to rescan it?"= ""\
		"БД Адресов изменилась.\nПересканировать?"

/* HappyDays view */
	"Type:" = "Тип:"
	"Next Date:" = "След. Дата:"
	"Origin:" = "Рождение:"
	"Age:" = "Возраст:"
	"UpTo Date:" = "До даты"
	"%dY %dM %dD (%ld)" = "%dг %dм %dд (%ld)"

	"Yes" = "Да"
	"No" = "Нет"
END

