TRANSLATION "CHINESE"
BEGIN
    "long_notifySettingMoreString" = ""\
    "关于 AN 图标编号，请参考 Action Names 说明书"\
    "DateBk3 图标将由 Memo Pad 处取得。"\
    "假如没有设定，则不会显示图标。\n"

    "long_customErrorString" = ""\
    "'Birthday' 为预设的自订栏目名称。你可于'喜好设定'中更改此名称\n\n"\
    "注意：你需先在 Address Book 内使用 'Options/Rename Custom Fields' "\
    "以设定以上自订栏目名称\n"

    "long_aboutString" = ""\
    "'HappyDays' 能帮助你纪录每个重要事件的日期(例如你亲朋戚友的生日及周年纪念等)\n\n"\
    "详细使用方法请参阅 index.html 及 manual.html。\n\n"\
    "HappyDays 是根据 GNU GPL2.0 发行的软件。\n"

    "long_cleanupAlertString" = ""\
    "假如你选择清除，任何带有 HappyDays 记号 (即 ' {HappyDays ID} ') "\
    "的日志将被清除。\n"

    "long_sl2lnString" = ""\
    "-) 标示普通月份\n"\
    "#) 标示润月"

    "long_cantFindAddrString" = ""\
    "在 Address Book 中找不到 '%s' 栏目\n"\
    "请在 Address Book 内设定以上自订栏目名称\n"

    "Select Time" = "Select Time"
    "No Time" = "不指定时间"
    "Invalid input date" = "不正确的日期"
    "Export to Memo Pad is completed." = "完成 Memo Pad 汇出。"

    "SUN"   = "星期日"
    "MON"   = "星期一"
    "TUE"   = "星期二"
    "WED"   = "星期三"
    "THU"   = "星期四"
    "FRI"   = "星期五"
    "SAT"   = "星期六"

    "Not enough memory" = "内存不足"
    "%d notify entry is created.\n" = "产生了 %d 个提示。\n"
    "%d existing entry " = "%d 个提示 "
    "is kept untouched." = "被保留。"
    "is modified." = "被修改。"

    "Collecting Information..." = "正在搜集信息，请稍候..."

    "HappyDays List" = "HappyDays 清单"
    "Look Up:" = "搜寻："

    "HappyDays View" = "HappyDays 检视"
    "Done"  = "完成"
    "DB" = "DateBk"
    "TD" = "Todo"
    "Goto" = "Addr"

    "Utilities" = "工具"
    "Date Book Notify" = "Date Book 提示"
    "Cleanup Date Book"  = "清理 Date Book"
    "To Do Notify" = "To Do List 提示"
    "Cleanup To Do"  = "清理 To Do List"
    "Export to Memo Pad" = "汇出到 MemoPad"
    "Solar to Lunar" = "阳历转阴历"
    "Lunar to Solar" = "阴历转阳历"
    "Rescan Address Book" = "重新检查 Address Book"

    "Options" = "选项"
    "Font..." = "字型"
    "Preferences" = "喜好设定"
    "Display Preferences" = "画面喜好设定"
    "About HappyDays" = "关于 HappyDays"

    "Edit" = "编辑"
    "Undo" = "复原"
    "Cut" = "剪下"
    "Copy" = "复制"
    "Paste" = "贴上"
    "Select All" = "全选"
    "Keyboard" = "键盘"
    "Graffiti" = "手写提示"

/* Font... */

/* preferences screen */

    "Custom field:" = "自订栏目："
    "Instead of system date format" = "不使用系统日期格式"
    "Use" = "并改用"
/*
    "M/D/Y" = "M/D/Y"
    "D/M/Y" = "D/M/Y"
    "D.M.Y" = "D.M.Y"
    "D-M-Y" = "D-M-Y"
    "Y/M/D" = "Y/M/D"
    "Y.M.D" = "Y.M.D"
    "Y-M-D" = "Y-M-D"
*/
    "M/D/Y" = "月/日/年"
    "D/M/Y" = "日/月/年"
    "D.M.Y" = "日.月.年"
    "D-M-Y" = "日-月-年"
    "Y/M/D" = "年/月/日"
    "Y.M.D" = "年.月.日"
    "Y-M-D" = "年-月-日"

    "Address Autoscan" = "Address 自动检查"
    "Always" = "永远"
    "Ask" = "先问我"
    "Never" = "永不"

    "Notify Format:" = "提示格式:"
    "[Last, First] E(1) Year" = "[姓, 名] E(1) 年"
    "[First Last] E(1) Year" = "[名 姓] E(1) 年"
    "Event - Last, First Year" = "事件 - 姓，名 年"
    "Event - First Last Year" = "事件 - 名 姓 年"
    "First Last Year" = "名 姓 年"

    "Address Book" = "Address Book"
    "Bulit-in" = "内建"


/* Display preferences */
    "Emphasize Lunar Date" = "突显阴历事件"


/* About HappyDays */
    "GPL free software" = "GPL 自由软件"
    "E-Mail & Web Page" = "电邮及网址"

    "Translator" = "中文版 - 大头 ( 给 亚华 :)"
    "Translator's email" = "daitau@hotmail.com"

    "OK" = "确定"
    "Cancel" = "取消"

    "Solar to Lunar Convert" = "阳历转阴历"
    "Enter Solar date:" = "阳历："
    "Year must be in 1881-2043" = "年份须在 1881 - 2043 间"
    "Result Lunar date:" = "阴历："

    "Convert" = "转换"

    "Lunar to Solar Convert" = "阴历转阳历"
    "Enter Lunar date:" = "阴历："
    "Leap" = "润年"
    "Result Solar date:" = "阳历："

/* Date Book & To Do Notify */
    "Records:" = "纪录："
    "all" = "全部"
    "selected" = "已选"
    "Existing:" = "现有的："
    "keep" = "保留"
    "modify" = "修改"
    "Priority:" = "重要性："
    "Category:" = "类别："
    "Private:" = "私人的："
    "Alarm:" = "响闹："
    "Time:" = "时间："
    "Icon" = "图标"

    "Repeat for:" = "重复："
    "years" = "年"

    "Notify warning" = "提示"

    "long_notifywarningString" = "^1: 你是否想建立 ^2 个 HappyDays 纪录的提示？"

/* Date Book Icon */
    "Date Book Icon" = "Date Book 图标"
    "Icon Support" = "图标支持"
    "AN" = "AN"
    "DateBk3" = "DateBook3"
    "AN Icon Number:" = "AN 图标编号："
    "DateBk3 Icon:" = "DateBook3 图标："

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "清理 HappyDays"

    "long_removeConfirmString" = ""\
    "你是否确定要清除所有 HappyDays 提示？"

    "HappyDays says" = "HappyDays 说"

    "HappyDays Export" = "HappyDays 汇出"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
      "要将 HappyDays 的资料汇出 Memo Pad？"

    "Custom Field Error" = "自订栏目错误"
    "Help" = "说明"


    "Invalid event format" = "不正确的事件格式"

    "long_invalidformatString" = ""\
    "^1 的地址簿栏目\n 含有一个不合格式的事件，应怎处理？"

    "Ignore" = "略过"
    "Ignore all" = "全部略过"

    "Cleanup Done" = "清理完毕"

    "^1: ^2 HappyDays notify entries removed." = ""\
    "^1: ^2 个 HappyDays 提示被清除了."

    "HappyDays Export List" = "HappyDays 汇出列表"
    "(not exist in this year)" = "(本年度没有)"
    "Please run Date Book once first." = "请先执行 Date Book 一次"

    "Days" = "日"
    "Date Book" = "Date Book"
    "To Do" = "To Do"
    "Scan note field" = "连 Note 栏目也一并检查"
    "%d day(s) left" = "尚余%d日"
    "%d day(s) passed" = "已经过了%d日"

    "Processing" = "处理中"
    "Processed : " = "处理了："

    "Address Change" = "Address 重新检查"
    "AddressDB is changed. \nDo you want to rescan it?"= ""\
    "Address Book 资料曾被更新。 \n你要 HappyDays 重新检查？"

/* HappyDays view */
	"Type:" = "事件类别："
	"Next Date:" = "下一日期："
	"Origin:" = "原本日期："
	"Age:" = "周年岁数："
	"UpTo Date:" = "距下一次："
	"%dY %dM %dD (%d)" = "%d年 %d月 %d日 (%d)"
END


