TRANSLATION "SPANISH"
BEGIN
	"long_notifySettingMoreString" = ""\
	"Para usuarios avanzados sólamente\n\n"\
	"Esta nota es usada por programas externos de reemplazo de la Agenda "\
	"como Action Names, DateBk3/4.\n\n"\
	"Usted puede asignar iconos, fuentes y más utilizando esta nota.\n\n"\
	"Para más información, consulte sus manuales.\n"

    "long_aboutString" = ""\
    "'HappyDays' le ayudará a recordar los cumpleaños y aniversarios "\
    "de sus amigos y familiares, así como muchos otros eventos.\n\n"\
    "Visite http://jmjeong.com/?HappyDays para información detallada "\
    "sobre cómo utilizar HappyDays\n\n"\
    "HappyDays es distribuído bajo los términos de la GNU General "\
    "Public License versión 2.0.\n"\
	"= Input Format\n\n"\
	"[*[{EventType}]\\ws{Description}\\ws{Date}[[nth day list]]\n"

    "long_cleanupAlertString" = ""\
    "Las entradas de recordatorio son consideradas HappyDays si tienen "\
	"{HappyDays ID} en su campo de nota. "\ 	
    "Si utiliza este formato en sus propias "\
    "entradas, dicho registro podría ser también removido por la Limpieza.\n"

    "long_sl2lnString" = ""\
        "-) significa mes ordinario en lunar\n"\
        "#) significa mes bisiesto en lunar"

    "Select Time" = "Elegir Hora"
    "No Time" = "Sin Hora"
    "Invalid input date" = "Fecha no válida"
    "Export to Memo Pad is completed." = "Exportar al Memo Pad ha finalizado."

    "SUN"   = "DOM"
    "MON"   = "LUN"
    "TUE"   = "MAR"
    "WED"   = "MIE"
    "THU"   = "JUE"
    "FRI"   = "VIE"
    "SAT"   = "SAB"

    "Not enough memory" = "No hay suficiente memoria"
    "%d notify entries have been created.\n" = "%d entradas de recordatorio creadas.\n" 
    "%d existing entries " = "%d entradas existentes "
    "are kept untouched." = "han sido conservadas."
    "have been modified." = "han sido modificadas."

    "Collecting Information" = "Recopilando Información"

    "Look Up:" = "Buscar:"

    "HappyDays View" = "Vista HappyDays"
    "Done"  = "Listo"
    "DB" = "Agenda" 
    "TD" = "Tareas"
    "Goto" = "Ir a"

    "Utilities" = "Utilidades"
    "Date Book Notify" = "Recordar en Agenda"
    "Cleanup Date Book"  = "Limpiar Agenda"
    "To Do Notify" = "Recordar en Tareas"
    "Cleanup To Do"  = "Limpiar Tareas"
    "Export to Memo Pad" = "Exportar al Memo Pad"
    "Solar to Lunar" = "Conv. Solar a Lunar"
    "Lunar to Solar" = "Conv. Lunar a Solar"
	"Rescan Address Book" = "Recopilar información"

    "Options" = "Opciones"
	"Font..." = "Fuente..."
    "Preferences" = "Preferencias"
	"Display Preferences" = "Pref. de presentación"
    "About HappyDays" = "Acerca de HappyDays"

    "Edit" = "Edición"
    "Undo" = "Deshacer"
    "Cut" = "Cortar"
    "Copy" = "Copiar" 
    "Paste" = "Pegar" 
    "Select All" = "Seleccionar todo" 
    "Keyboard" = "Teclado" 
    "Graffiti" = "Graffiti"


/* Font... */

/* preferences screen */
    "Custom field:" = "Campo personalizado:"
    "Instead of system date format" = "En lugar del formato de fecha"  
    "Use" = "Usar"  
    "M/D/Y" = "M/D/A"  
    "D/M/Y" = "D/M/A"  
    "D.M.Y" = "D.M.A"  
    "D-M-Y" = "D-M-A"  
    "Y/M/D" = "A/M/D"  
    "Y.M.D" = "A.M.D"  
    "Y-M-D" = "A-M-D"  
	"Address Autoscan" = "Recopilar inform."
	"Always" = "Siempre"
	"Ask" = "Preguntar"
	"Never" = "Nunca"

    "Notify Format:" = "Formato de recordatorio:"  
    "[Last, First] E(1) Year" = "[Apell, Nombre] E(1) Años"  
    "[First Last] E(1) Year" = "[Nombre Apell] E(1) Años"  
  	"[First] E(1) Year" = "[Nombre] E(1) Años" 
    "Event - Last, First Year" = "Evento - Apell, Nombre Años"  
    "Event - First Last Year" = "Evento - Nombre Apell Años"  
    "First Last Year" = "Nombre Apell Años"  
    
	"Address Book:" = "Direcciones:"
	"Built-in" = "Built-in"


/* Display preferences */
    "Emphasize Lunar Date" = "Enfatizar Fecha Lunar"


/* About HappyDays */	
	"GPL free software" = "GPL software gratuito"
	"E-Mail & Web Page" = "E-Mail & Web Page"

    "Translator" = "Alejandro Lizarraga"
    "Translator's email" = "bow2axel@hotmail.com"

    "OK" = "Aceptar"
    "Cancel" = "Cancelar"

    "Solar to Lunar Convert" = "Convertir Solar a Lunar"
    "Enter Solar date:" = "Introduzca fecha solar:"
    "Year must be in 1881-2043" = "El año debe estar entre 1881-2043"
    "Result Lunar date:" = "Resultado fecha lunar:"

    "Convert" = "Convertir"

    "Lunar to Solar Convert" = "Convertir Solar a Lunar"
    "Enter Lunar date:" = "Introduzca fecha lunar:"
    "Leap" = "Bisiesto"
    "Result Solar date:" = "Resultado fecha solar:"


/* Date Book & To Do Notify */
    "Records:" = "Registros:"
      "all" = "todos"
      "selected" = "selecc." 
    "Existing:" = "Existentes:"
      "keep" = "conserv."
      "modify" = "modif."
    "Priority:" = "Prioridad:"
    "Category:" = "Categoría:"
    "Private:" = "Privados:"
    "Alarm:" = "Alarma:"
    "Time:" = "Hora:"
    "Icon" = "Icono"

    "Repeat for:" = "Repetir por:"
    "years" = "años"

    "Notify warning" = "Aviso de recordatorios" 
	"long_notifywarningString" = ""\
  		"^1: Está seguro de que desea crear entradas de recordatorio para "\
		"^2 registros de HappyDays?" 
      
/* Date Book Icon */
    "Date Book Icon" = "Icono de Agenda" 
      "Icon Support" = "Soporte de Iconos"  
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "AN Núm. de Icono:"  
      "DateBk3 Icon:" = "DateBk3 Icono:"  

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "Limpiar HappyDays" 

    "long_removeConfirmString" = ""\
    "Are you sure you want to remove all "\
    "HappyDays notify entries?"

    "HappyDays says" = "HappyDays dice"

    "HappyDays Export" = "Exportar HappyDays"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
    	"¿Desea exportar la lista de HappyDays al Memo Pad?" 

    "Custom Field Error" = "Error de campo personalizado"
    "Help" = "Ayuda" 


    "Invalid event format" = "Formato de evento no válido" 

	"long_invalidformatString" = ""\
    	"El registro de Direcciones para\n[^1]\n contiene un evento no válido. "\
		"¿Cómo desea manejarlo?" 

    "Ignore" = "Ignorar" 
    "Ignore all" = "Ignorar todos" 

    "Cleanup Done" = "Limpieza finalizada" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    	"^1: ^2 entradas de recordatorio fueron removidas." 

    "HappyDays Export List" = "Lista para exportar de HappyDays" 
    "(not exist in this year)" = "(no existe en este año)" 
    "Please run Date Book once first." = "Por favor primero ejecute la Agenda una vez."  
    
    "Days" = "Días"  
    "Date Book" = "Agenda"  
    "To Do" = "Tareas"  
    "Scan note field" = "Inspeccionar campo de nota"  
    "%ld days left" = "%ld días faltantes"  
    "%ld days passed" = "%ld días pasados"  

    "Processing" = "Procesando"  
    "Processed : " = "Procesados : " 

	"Address Change" = "Cambios en Direcciones"
	"AddressDB is changed. \nDo you want to rescan it?"= ""\
		"La BD de Direcciones ha cambiado. \nDesea recopilar nuevamente?"

 	"Ignore record with prefix '!'" = "Ignorar registros con prefijo '!'"
 	"Databook note" = "Nota de Agenda"
 	"Add the following note" = "Agregar la siguiente nota"

/* HappyDays view */
	"Type:" = "Tipo:"
	"Next Date:" = "Próximo:"
	"Origin:" = "Origen:"
	"Age:" = "Edad:"
	"UpTo Date:" = "Para hoy:"
	"%dY %dM %dD (%ld)" = "%dA %dM %dD (%ld)"

	"Yes" = "Sí"
	"No" = "No"
END

