TRANSLATION "SPANISH"
BEGIN
        
"long_notifySettingMoreString" = ""\
        "Sólo para usuarios avanzados\n\n"\
        "Esta nota se dirige a programas sustitutivos de la "\
        "Agenda como Action Names, DateBk3/4.\n\n"\
        "Puede seleccionar un icono, fuente, o más opciones usando esta sección.\n\n"\
        "Para obtener más información, consulte su manual.\n"

"HappyDays"= "HappyDays"
        
"long_customErrorString" = ""\
        "'Birthday' es el nombre del campo personalizado por omisión."\
        "Para usar un campo personalizado diferente"\
        "seleccione el menú 'Preferencias'.\n\n"\
        "IMPORTANTE: Necesita utilizar la Lista de Direcciones y seleccionar 'Opciones/"\
        "Nombre campos pers...' para cambiar un campo personalizado a 'Nacimiento'"\
        " o el de su elección en las preferencias de HappyDays.\n"
        
"long_aboutString" =  ""\
        "'HappyDays' le ayudará a recordar los cumpleaños y aniversarios "\
        "de sus amigos y familiares, así como otros eventos.\n\n"\
        "Por favor consulte el archivo index.html y manual.html para información "\
        "detallada sobre el uso de HappyDays\n\n"\
        "HappyDays se distribuye bajo los términos de la Licencia GNU General "\
        "Public License version 2.0.\n"

"long_cleanupAlertString" = ""\
        "Las notificaciones se consideran HappyDays si tienen "\
        "{Ident. HappyDays} en el campo Nota. "\ 	
        "Si usa este formato en sus propias entradas, "\
        "este registro puede ser eliminado por el proceso de Limpieza.\n"

"long_removeConfirmString" =  ""\
        "¿Desea eliminar todas las notificaciones "\
        "de HappyDays?"

    "Invalid input date" =  "Fecha inválida"
    "Select Time" =  "Establecer hora"
    "No Time" =  "Sin hora"
    "Export to Memo Pad is completed." =  "Exportación a Bloc de notas lista."
    "long_sl2lnString" =  ""\
        "-) significa mes lunar normal\n"\
        "#) significa mes lunar bisiesto"

    "SUN" =  "DOM"
    "MON" =  "LUN"
    "TUE" =  "MAR"
    "WED" =  "MIE"
    "THU" =  "JUE"
    "FRI" =  "VIE"
    "SAT" =  "SAB"

    "SMTWTFS"= "DLMXJVS"

    "Janunary"= "Enero"
    "February"= "Febrero"
    "March"= "Marzo"
    "April"= "Abril"
    "May"= "Mayo"
    "June"= "Junio"
    "July"= "Julio"
    "August"= "Agosto"
    "September"= "Septiembre"
    "October"= "Octubre"
    "November"= "Noviembre"
    "December"= "Diciembre"

    "Not enough memory" =  "Memoria Insuficiente"
    "%d notify entry is created.\n" =  "%d notificaciones creadas.\n"
    "%d existing entry " =  "%d notificaciones "
    "is kept untouched." =  "sin modificar."
    "is modified." =  "modificadas."

    "long_cantFindAddrString" =  ""\
    "No es posible encontrar el campo personalizado: '%s'\n"\
    "Por favor renombre un campo personalizado en su Lista de Direcciones."

    "HappyDays Export List" =  "Exportar Lista HappyDays"
    "(not exist in this year)" =  "(no existe en este año)"
    "Please run Date Book once first." =  "Por favor selecione la Agenda primero."
    "Days" =  "Días"
    "%dY %dM %dD (%ld)"= "%dA %dM %dD (%ld)"

    "Date Book" =  "Agenda"
    "To Do" =  "Tareas"
    "%ld days left" =  "%ld días para el evento"  
    "%ld days passed" =  "%ld días transcurridos"  

    "Type:" =  "Tipo:"
    "Next Date:" =  "Fecha:"
    "Origin:" =  "Origen:"
    "Age:" =  "Edad:"
    "UpTo Date:" =  "A la fecha:"

    "Collecting Information" =  "Recogiendo información"

    "HappyDays "= "HappyDays"

    "Look Up:" =  "Buscar:"
    "N"= "N"
    "D"= "D"
    "A"= "A"

    "HappyDays View" =  "Detalle del Evento"

    "Done" =  "Hecho"
    "DB" =  "Agenda"
    "TD" =  "Tareas"
    "Goto" =  "Ir a"

    "Utilities" =  "Herramientas"
    "Date Book Notify" =  "Notificar en Agenda"
    "Cleanup Date Book" =  "Limpiar Agenda"
    "C"= "L"
    "To Do Notify" =  "Notificar en Tareas"
    "T"= "T"
    "Cleanup To Do" =  "Limpiar Tareas"
    "O"= "I"
    "Export to Memo Pad" =  "Exportar a Bloc de notas"
    "E"= "E"
    "Solar to Lunar" =  "Solar -> Lunar"
    "S"= "S"
    "Lunar to Solar" =  "Lunar -> Solar"
    "L"= "L"
    "Rescan Address Book" =  "Actualizar Eventos"

    "Options" =  "Opciones"
    "Font..." =  "Fuente..."
    "F"= "F"
    "Preferences" =  "Preferencias"
    "R"= "R"
    "Display Preferences" =  "Preferencias de Pantalla"
    "About HappyDays" =  "Acerca de HappyDays"

    "Edit" =  "Edición"
    "Undo" =  "Deshacer"
    "U"= "D"
    "Cut" =  "Cortar"
    "X"= "X"
    "Copy" =  "Copiar"
    "Paste" =  "Pegar"
    "P"= "P"
    "Select All" =  "Selec todo"
    "Keyboard" =  "Teclado"
    "K"= "T"
    "Graffiti" =  "Ayuda de Graffiti"
    "G"= "G"

    "Emphasize Lunar Date" =  "Preferir Calendario Lunar"
    "Display solar/lunar info in View"= "Mostrar información solar/lunar en Vista"
    "OK" =  "Hecho"
    "Cancel" =  "Cancelar"

    "Custom field:" =  "Campo pers:"

    "Instead of system date format" =  "Formato de fecha alternativo"
    "Use" =  "Usar"
    "M/D/Y" =  "M/D/A"
    "D/M/Y" =  "D/M/A"
    "D.M.Y" =  "D.M.A"
    "D-M-Y" =  "D-M-A"
    "Y/M/D" =  "A/M/D"
    "Y.M.D" =  "A.M.D"
    "Y-M-D" =  "A-M-D"

    "Scan note field" =  "Buscar en Notas"
    "Ignore record with prefix '!'"= "Ignorar registro con prefijo '!'"

    "Address Autoscan" =  "Actualizar Eventos"
    "Always" =  "Siempre"
    "Ask" =  "Preguntar"
    "Never" =  "Nunca"

    "Notify Format:" =  "Formato de Notificación:"
    "[Last, First] E(1) Year" =  "[Apellido, Nombre] E(1) Año"
    "[First Last] E(1) Year" =  "[Nombre Apellido] E(1) Año"
    "Event - Last, First Year" =  "Evento - Apellido, Nombre Año"
    "Event - First Last Year" =  "Evento - Nombre Apellido Año"
    "First Last Year" =  "Nombre Apellido Año"

    "Address Book:" =  "Direcciones:"
    "Built-in" =  "Internas"
    "Address.kr"= "Address.kr"
    "Address Album"= "Address Album"
    "AddressBkR"= "AddressBkR"
    "Address Plus(+)"= "Address Plus(+)"
    "Super Names"= "Super Names"
    "TealPhone"= "TealPhone"

    "HappyDays ID:"= "Ident. de HappyDays:"

    "Solar to Lunar Convert" =  "Solar -> Lunar"
    "Enter Solar date:" =  "Indique la fecha Solar:"
    "Year must be in 1881-2043" =  "El Año debe estar entre 1881 y 2043"

    "Result Lunar date:" =  "Fecha Lunar resultado:"

    "Convert" =  "Convertir"

    "Lunar to Solar Convert" =  "Lunar -> Solar."
    "Enter Lunar date:" =  "Indique la fecha Lunar:"
    "Leap" =  "Bisiesto"

    "Result Solar date:" =  "Fecha Solar resultado:"

    "Records:" =  "Registros:"
    "all" =  "Todos"
    "selected" =  "Marcado"

    "Existing:" =  "Existente:"
    "keep" =  "Dejar"
    "modify" =  "Cambiar"

    "Private:" =  "Confidencial:"

    "Alarm:" =  "Alarma:"

    "Time:" =  "Hora:"

    "Repeat for:" =  "Repetir:"
    "years" =  "año(s)"

    "Note"= "Nota"

    "Datebook Note"= "Nota en Agenda"

    "Add the following note"= "Añadir la siguiente nota"

    "Priority:" =  "Prioridad:"
    "1"= "1"
    "2"= "2"
    "3"= "3"
    "4"= "4"
    "5"= "5"

    "Category:" =  "Categoría:"

    "HappyDays says" =  "HappyDays dice"
    "^1"= "^1"

    "Address Change" =  "Cambio en Direcciones"

"AddressDB is changed. \nDo you want to rescan it?" =  ""\
        "La Lista de Direcciones ha cambiado. \n¿Desea actualizar los eventos?"

    "HappyDays Export" =  "Exportar HappyDays"

"Would you like to export HappyDays List to Memo Pad?" =  ""\
        "¿Desea exportar la lista HappyDays al Bloc de notas?"

    "Custom Field Error" =  "Error en campo pers."
    "Help" =  "Ayuda"

    "HappyDays Cleanup" =  "Limpiar HappyDays"
    "^1: ^2"= "^1: ^2"

    "Notify warning" =  "Aviso"

"long_notifywarningString" =  ""\
        "^1: ¿Está seguro que desea crear notificaciones de HappyDays para "\
        "^2 registros?"

    "Invalid event format" =  "Formato de evento inválido."

"long_invalidformatString" =  ""\
        "El registro de agenda de ^1\n contiene un evento invalido. ¿Cómo desea proceder?"

    "Ignore" =  "Ignorar"
    "Ignore all" =  "Ignorar todos"

    "Cleanup Done" =  "Limpieza concluida"

"^1: ^2 HappyDays notify entries removed." =  ""\
        "^1: ^2 notificaciones de HappyDays eliminadas."

    "GPL free software" =  "Softwate gratuito GPL"

    "E-Mail & Web Page" =  "E-Mail & Página Web"

    "Translator" =  "Trad: Juan Fernando Calderón"
    "Translator's email" =  "jfcalderon@usa.net"

    "Processing" =  "Procesando"
    "Processed : " =  "Procesado : "	
END
