TRANSLATION "SPANISH"
BEGIN
	"long_notifySettingMoreString" = ""\
      "Para el número de icono de Action Names consulte su manual. "\
      "Los iconos de DateBk3 son leídos del bloc de notas. "\
      "Si no existe la entrada de DateBk3 en el bloc de notas no se muestra información.\n"

    "long_customErrorString" = ""\
    "'Nacimiento' es el nombre del campo personalizado por omisión."\
    "Para usar un campo personalizado diferente"\
    "seleccione el menú 'Preferencias'.\n\n"\
    "IMPORTANTE: Necesita utilizar la Lista de Direcciones y seleccionar 'Opciones/"\
    "Nombre campos pers...' para cambiar un campo personalizado a 'Nacimiento'"\
    " o el de su elección en las preferencias de "\
    "HappyDays.\n"

    "long_aboutString" = ""\
      "'HappyDays' le ayudará a recordar los cumpleaños y aniversarios "\
      "de sus amigos y familiares, así como otros eventos.\n\n"\
    "Por favor consulte el archivo index.html y manual.html para información detallada "\
    "sobre el uso de HappyDays\n\n"\
    "HappyDays se distribuye bajo los términos de la Licencia GNU General "\
    "Public License version 2.0.\n"

    "long_cleanupAlertString" = ""\
    "Las notificaciones se consideran HappyDays si tienen "\
	"{Ident. HappyDays} en el campo Nota. "\ 	
    "Si usa este formato en sus propias entradas, "\
    "este registro puede ser eliminado por la Limpieza.\n"

    "long_sl2lnString" = ""\
        "-) significa mes lunar normal\n"\
        "#) significa mes lunar bisiesto"

    "long_cantFindAddrString" = ""\
    "No es posible encontrar el campo personalizado: '%s'\n"\
    "Por favor renombre un campo personalizado en su Lista de Direcciones."

    "Select Time" = "Establecer hora"
    "No Time" = "Sin hora"
    "Invalid input date" = "Fecha inválida"
    "Export to Memo Pad is completed." = "Exportación a Bloc de notas lista."

    "SUN"   = "DOM"
    "MON"   = "LUN"
    "TUE"   = "MAR"
    "WED"   = "MIE"
    "THU"   = "JUE"
    "FRI"   = "VIE"
    "SAT"   = "SAB"

    "Not enough memory" = "Memoria Insuficiente"
    "%d notify entry is created.\n" = "%d notificaciones creadas.\n"
    "%d existing entry " = "%d notificaciones "
    "is kept untouched." = "sin modificar."
    "is modified." = "modificadas."

    "Collecting Information..." = "Recolectando información..."

    "HappyDays List" = "Lista HappyDays"
    "Look Up:" = "Buscar:"

    "HappyDays View" = "Detalle Evento"
    "Done"  = "Hecho"
    "DB" = "Agenda"
    "TD" = "Tareas"
    "Goto" = "Ir a"

    "Utilities" = "Utilerias"
    "Date Book Notify" = "Notificar en Agenda"
    "Cleanup Date Book"  = "Limpiar Agenda"
    "To Do Notify" = "Notificar en Tareas"
    "Cleanup To Do"  = "Limpiar Tareas"
    "Export to Memo Pad" = "Exportar a Bloc de notas"
    "Solar to Lunar" = "Solar -> Lunar"
    "Lunar to Solar" = "Lunar -> Solar"
    "Rescan Address Book" = "Actualizar Eventos"

    "Options" = "Opciones"
	"Font..." = "Fuente..."
    "Preferences" = "Preferencias"
	"Display Preferences" = "Preferencias de Pantalla"
    "About HappyDays" = "Acerca de HappyDays"

    "Edit" = "Edición"
    "Undo" = "Deshacer"
    "Cut" = "Cortar"
    "Copy" = "Copiar"
    "Paste" = "Pegar"
    "Select All" = "Selec todo"
    "Keyboard" = "Teclado"
    "Graffiti" = "Ayuda de Graffiti"


/* Font... */

/* preferences screen */
    "Custom field:" = "Campo pers:"
    "Instead of system date format" = "Formato de fecha alternativo"
    "Use" = "Usar"
    "M/D/Y" = "M/D/A"
    "D/M/Y" = "D/M/A"
    "D.M.Y" = "D.M.A"
    "D-M-Y" = "D-M-A"
    "Y/M/D" = "A/M/D"
    "Y.M.D" = "A.M.D"
    "Y-M-D" = "A-M-D"
	"Address Autoscan" = "Actualizar Eventos"
	"Always" = "Siempre"
	"Ask" = "Preguntar"
	"Never" = "Nunca"

      "Notify Format:" = "Formato de Notificación:"
      "[Last, First] E(1) Year" = "[Apellido, Nombre] E(1) Año"
	"[First Last] E(1) Year" = "[Nombre Apellido] E(1) Año"
	"Event - Last, First Year" = "Evento - Apellido, Nombre Año"
	"Event - First Last Year" = "Evento - Nombre Apellido Año"
	"First Last Year" = "Nombre Apellido Año"
    
	"Address Book:" = "Direcciones:"
	"Built-in" = "Interna"


/* Display preferences */
    "Emphasize Lunar Date" = "Preferir Calendario Lunar"


/* About HappyDays */	
	"GPL free software" = "Softwate gratuito GPL"
	"E-Mail & Web Page" = "E-Mail & Página Web"

    "Translator" = "Trad: Juan Fernando Calderón"
    "Translator's email" = "jfcalderon@usa.net"

    "OK" = "Hecho"
    "Cancel" = "Cancelar"

    "Solar to Lunar Convert" = "Solar -> Lunar"
    "Enter Solar date:" = "Indique la fecha Solar:"
    "Year must be in 1881-2043" = "El Año debe ser entre 1881 y 2043"
    "Result Lunar date:" = "Fecha Lunar resultado:"

    "Convert" = "Convertir"

    "Lunar to Solar Convert" = "Lunar -> Solar."
    "Enter Lunar date:" = "Indique la fecha Lunar:"
    "Leap" = "Bisiesto"
    "Result Solar date:" = "Fecha Solar resultado:"


/* Date Book & To Do Notify */
    "Records:" = "Registros:"
      "all" = "Todos"
      "selected" = "Marcado"
    "Existing:" = "Existente:"
      "keep" = "Dejar"
      "modify" = "Cambiar"
    "Priority:" = "Prioridad:"
	"Category:" = "Categoría:"
    "Private:" = "Confidencial:"
    "Alarm:" = "Alarma:"
    "Time:" = "Hora:"
    "Icon" = "Icono"

    "Repeat for:" = "Repetir:"
    "years" = "año(s)"

    "Notify warning" = "Aviso"
	"long_notifywarningString" = ""\
      "^1: ¿Está seguro que desea crear notificaciones de HappyDays para ^2 registros?"


/* Date Book Icon */
    "Date Book Icon" = "Icono de Agenda"  
      "Icon Support" = "Soporte de Iconos"
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "Número Icono AN:"
      "DateBk3 Icon:" = "Icono DateBk3:"

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "Limpiar HappyDays"

    "long_removeConfirmString" = ""\
    "¿Desea eliminar todas las notificaciones "\
    "de HappyDays?"



    "HappyDays says" = "HappyDays dice"

    "HappyDays Export" = "Exportar HappyDays"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
      "¿Desea exportar la lista HappyDays al Bloc de notas?"

    "Custom Field Error" = "Error en campo pers."
    "Help" = "Ayuda"


    "Invalid event format" = "Formato de evento invalido."

	"long_invalidformatString" = ""\
	"El registro de agenda de ^1\n contiene un evento invalido. ¿Cómo desea proceder?"


    "Ignore" = "Ignorar"
    "Ignore all" = "Ignorar todos"

    "Cleanup Done" = "Limpieza concluida"

    "^1: ^2 HappyDays notify entries removed." = ""\
      "^1: ^2 notificaciones de HappyDays eliminadas."

    "HappyDays Export List" = "Exportar Lista HappyDays"
    "(not exist in this year)" = "(no existe en este año)"
    "Please run Date Book once first." = "Por favor selecione la Agenda primero."

    "Days" = "Días"
    "Date Book" = "Agenda"
    "To Do" = "Tareas"
    "Scan note field" = "Buscar en Notas"
    "%d days left" = "%d días para el evento"  
    "%d days passed" = "%d días transcurridos"

      "Processing" = "Procesando"
	"Processed : " = "Procesado : "	

	"Address Change" = "Actualización de Agenda"
	"AddressDB is changed. \nDo you want to rescan it?"= ""\
		"La Lista de Direcciones. \n¿Desea actualizar los eventos?"

/* HappyDays view */
	"Type:" = "Tipo:"
	"Next Date:" = "Fecha:"
	"Origin:" = "Origen:"
	"Age:" = "Edad:"
	"UpTo Date:" = "A la fecha:"
	"%dY %dM %dD (%d)" = "%dA %dM %dD (%d)"
END
