TRANSLATION "THAI"
BEGIN
    "long_notifySettingMoreString" = ""\
    "สำหรับผู้ใช้ระดับสูง\n\n"\
    "Note สำหรับใช้กับโปรแกรม datebook อื่น "\
    "เช่น Action Names, DateBk3/4\n\n"\
    "คุณสามารถเซ็ต ไอคอน ฟอนต์ ฯลฯ โดยใช้ note นี้\n\n"\
    "หากต้องการรายละเอียดเพิ่มเติม กรุณาอ่านคู่มือของโปรแกรมนั้นๆ\n"

    "long_aboutString" = ""\
    "'HappyDays' ใช้สำหรับเตือน\nวันเกิดและวันครบรอบต่างๆ ของเพื่อนและครอบครัว "\
    "รวมถึงเหตุการณ์พิเศษอื่นๆ\n\n"\
    "อ่านรายละเอียดและวิธีการใช้งานไดที่ http://jmjeong.com/?HappyDays\n\n"\
    "HappyDays ถูกเผยแพร่ภายใต้ GNU General "\
    "Public License เวอร์ชั่น 2.0\n\n"\
	"= รูปแบบข้อมูล\n\n"\
	"[*[{ประเภทเหตุการณ์}]\\ws{รายละเอียด}\\ws{วันที่}[[รายการจำนวนวันครบรอบ]]\n\n"\
	"\\ws = เว้นวรรค (white space)\n"

    "long_cleanupAlertString" = ""\
    "รายการเตือนของ HappyDays จะมี "\
    "{HappyDays ID} ใน note "\   
    "ถ้าคุณใช้รูปแบบดังกล่าวในรายการเตือนอื่น "\
    "รายการเหล่า\nนั้นอาจถูกลบด้วยเช่นกัน\n"

    "long_sl2lnString" = ""\
        "-) คือวันที่ตามจันทรคติใน\n\tเดือนปกติ\n\n"\
        "#) คือวันที่ตามจันทรคติใน\n\tเดือนอธิกมาส"

    "Select Time" = "เลือกเวลา"
    "No Time" = "ไม่กำหนด"
    "Invalid input date" = "วันที่ที่ใส่ไม่ถูกต้อง"
    "Export to Memo Pad is completed." = "ส่งข้อมูลไป Memo Pad เรียบร้อยแล้ว"

    "SUN"   = "อา."
    "MON"   = "จ."
    "TUE"   = "อ."
    "WED"   = "พ."
    "THU"   = "พฤ."
    "FRI"   = "ศ."
    "SAT"   = "ส."

    "Not enough memory" = "หน่วยความจำไม่พอ"
    "%d notify entries have been created.\n" = "%d รายการใหม่\n\tได้ถูกสร้างขื้น\n"
    "%d existing entries " = "%d รายการที่มีอยู่\n\t"
    "are kept untouched." = "ไม่ได้ถูกเปลี่ยน"
    "have been modified." = "ได้ถูกเปลี่ยน"

    "Collecting Information" = "กำลังรวบรวมข้อมูล"

    "Look Up:" = "ค้นหา"

    "HappyDays View" = "HappyDays View"
    "Done"  = "เสร็จ"
    "DB" = "DB"
    "TD" = "TD"
    "Goto" = "ไปที่"

    "Utilities" = "อุปกรณ์  "
    "Date Book Notify" = "เตือนใน DateBook"
    "Cleanup Date Book"  = "ลบเตือนใน Datebook"
    "To Do Notify" = "เตือนใน To Do"
    "Cleanup To Do"  = "ลบเตือนใน To Do"
    "Export to Memo Pad" = "ส่งข้อมูลไป Memo Pad"
    "Solar to Lunar" = "สุริยคติ -> จันทรคติ"
    "Lunar to Solar" = "จันทรคติ -> สุริยคติ"
    "Rescan Address Book" = "สแกน Address Book อีกครั้ง"

    "Options" = "ตัวเลือก"
    "Font..." = "ฟอนต์..."
    "Preferences" = "ตั้งค่า"
    "Display Preferences" = "ตั้งค่าการแสดงผล"
    "About HappyDays" = "เกี่ยวกับ HappyDays"

    "Edit" = "แก้ไข"
    "Undo" = "กลับคืน"
    "Cut" = "ตัด"
    "Copy" = "คัดลอก"
    "Paste" = "แปะ"
    "Select All" = "เลือกทั้งหมด"
    "Keyboard" = "แป้นพิมพ์"
    "Graffiti" = "วิธีเขียนกราฟฟิตี"


/* Font... */

/* preferences screen */
    "Custom field:" = "Custom field:"
    "Instead of system date format" = "ไม่ใช้รูปแบบวันที่ตามระบบ"
    "Use" = "ใช้"
    "M/D/Y" = "ด/ว/ป"
    "D/M/Y" = "ว/ด/ป"
    "D.M.Y" = "ว.ด.ป"
    "D-M-Y" = "ว-ด-ป"
    "Y/M/D" = "ป/ด/ว"
    "Y.M.D" = "ป.ด.ว"
    "Y-M-D" = "ป-ด-ว"
    "Address Autoscan:" = "สแกน Address อัตโนมัติ:"
    "Always" = "ใช่"
    "Ask" = "ถาม"
    "Never" = "ไม่"

    "Notify Format:" = "รูปแบบที่ใช้เตือน:"
    "[Last, First] E(1) Year" = "[นามสกุล, ชื่อ] E(1) ปี"
    "[First Last] E(1) Year" = "[ชื่อ นามสกุล] E(1) ปี"
    "[First] E(1) Year" = "[ชื่อ] E(1) ปี" 
    "Event - Last, First Year" = "เหตุการณ์ - นามสกุล, ชื่อ ปี"
    "Event - First Last Year" = "เหตุการณ์ - ชื่อ นามสกุล ปี"
    "First Last Year" = "ชื่อ นามสกุล อายุ"
    
    "Address Book:" = "Address Book:"
    "Built-in" = "ที่มากับเครื่อง"


/* Display preferences */
    "Emphasize Lunar Date" = "ขีดเส้นใต้เน้นจันทรคติ"


/* About HappyDays */   
    "GPL free software" = "ซอฟท์แวร์ฟรีภายใต้ GPL"
    "E-Mail & Web Page" = "อีเมล์ & เว็บเพจ"

    "Translator" = "แปลโดย: กัปตัน เตียวตระกูล"
    "Translator's email" = "KTeotrakool@hotmail.com"

    "OK" = "ตกลง"
    "Cancel" = "ยกเลิก"

    "Solar to Lunar Convert" = "เปลี่ยน สุริยคติ -> จันทรคติ"
    "Enter Solar date:" = "ใส่วันที่ตามสุริยคติ:"
    "Year must be in 1881-2043" = "ปีต้องอยู่ระหว่าง ค.ศ. 1881 - 2043"
    "Result Lunar date:" = "ผลวันที่ตามจันทรคติ:"

    "Convert" = "เปลี่ยน"

    "Lunar to Solar Convert" = "เปลี่ยน จันทรคติ -> สุริยคติ"
    "Enter Lunar date:" = "ใส่วันที่ตามจันทรคติ:"
    "Leap" = "อธิกมาส   "
    "Result Solar date:" = "ผลวันที่ตามสุริยคติ:"


/* Date Book & To Do Notify */
    "Records:" = "เร็คคอร์ด:"
      "all" = "ทั้งหมด"
      "selected" = "ที่เลือก"
    "Existing:" = "ที่มีอยู่:"
      "keep" = "คงเดิม"
      "modify" = "เปลี่ยน"
    "Priority:" = "ลำดับ:"
    "Category:" = "หมวด:"
    "Private:" = "ส่วนตัว:"
    "Alarm:" = "เตือนล่วงหน้า:"
    "Time:" = "เวลา:"
    "Icon" = "ไอคอน"

    "Repeat for:" = "ซํ้าเป็นเวลา:"
    "years" = "ปี"

    "Notify warning" = "คำเตือน"
    "long_notifywarningString" = ""\
    "^1: ต้องการให้ HappyDays สรัาง\nรายการเตือน\n^2 รายการหรือไม่?"


/* Date Book Icon */
    "Date Book Icon" = "ไอคอนใน Date Book"
    "Icon Support" = "สนับสนุนไอคอน       "
    "AN" = "AN"  
    "DateBk3" = "DateBk3"  
    "AN Icon Number:" = "เลขไอคอนใน AN:   "
    "DateBk3 Icon:" = "ไอคอนใน DateBk3:"

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "HappyDays Cleanup" 

    "long_removeConfirmString" = ""\
    "ต้องการลบ\nรายการเตือนที่สร้างโดย HappyDays หรือไม่?"

    "HappyDays says" = "HappyDays Message"

    "HappyDays Export" = "HappyDays Export"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
        "ต้องการส่งข้อมูลใน HappyDays List ไป Memo Pad หรือไม่?"

    "Custom Field Error" = "มีข้อผิดพลาดใน Custom Field"
    "Help" = "วิธีใช้"

    "Invalid event format" = "รูปแบบไม่ถูกต้อง"

    "long_invalidformatString" = ""\
    "ระเบียนใน Address ของ\n^1\nมีรูปแบบไม่ถูกต้อง\nต้องการแก้ไขหรือไม่?"

    "Ignore" = "ทิ้งไว้"
    "Ignore all" = "ทิ้งไว้ทั้งหมด"

    "Cleanup Done" = "ลบเสร็จเรียบร้อย"

    "^1: ^2 HappyDays notify entries removed." = ""\
      "^1: ลบ ^2 รายการที่สร้างโดย HappyDays เสร็จเรียบร้อย"

    "HappyDays Export List" = "HappyDays Export List" 
    "(not exist in this year)" = "(ไม่ปรากฏในปีนี้)"
    "Please run Date Book once first." = "โปรดใช้ DateBook ก่อน 1 ครั้ง"
    
    "Days" = "วัน"
    "Date Book" = "Date Book"
    "To Do" = "To Do"
    "Scan note field" = "สแกนใน note      "
    "%ld days left" = "เหลืออีก %ld วัน"  
    "%ld days passed" = "ผ่านไป %ld วัน"  

    "Processing" = "กำลังประมวลผล"
    "Processed : " = "เสร็จแล้ว: "

    "Address Change" = "Address Rescan"
    "AddressDB is changed. \nDo you want to rescan it?"= ""\
        "ข้อมูลใน Address เปลี่ยน\nต้องการสแกนอีกครั้งหรือไม่?"

    "Ignore record with prefix '!'" = "ละเร็คคอร์ดที่ขึ้นต้นด้วย '!'"
    "Databook note" = "Databook note"
    "Add the following note" = "เพิ่ม note ต่อไปนี้"

/* HappyDays view */
    "Type:" = "ประเภท:"
    "Next Date:" = "ครั้งต่อไป:"
    "Origin:" = "วันเริ่มต้น:"
    "Age:" = "อายุ:"
    "UpTo Date:" = "ณ ปัจจุบัน:"
    "%dY %dM %dD (%ld)" = "%dปี %dเดือน %dวัน (%ld)"

    "Yes" = "ใช่"
    "No" = "ไม่"
END

