TRANSLATION "TURKISH"
BEGIN

    "Translator" = "Çeviri: Engin Utkan"
    "Translator's email" = "E-mail: engin.utkan@usa.net"

	"long_notifySettingMoreString" = ""\
	"Action Names ikon numarasý için AN manuelini inceleyiniz. DateBk3 ikonlarý"\
	"MemoPad'den okunmaktadýr. MemoPad'de DateBk3 ikonlarý için kayýt yoksa, "\
	"ikonlar gösterilemeyecektir.\n"

    "long_customErrorString" = ""\
    "'Birthday' öngörülmüþ tanýmlanabilir alan adýdýr (default custom field name)."\
    "Baþka bir öngörülmüþ tanýmlanabilir alan adý seçmek için"\
    "'Ayarlar' menü seçeneðinden deðiþiklik yapmanýz gerekmektedir.\n\n"\
    "ÖNEMLÝ: Address Book'u baþlatýp 'Options' menüsünden/"\
    "'Rename Custom Fields' seçeneðini seçerek, bir alan adýný 'Birthday'e"\
    "ya da Happydays'in Ayarlar menüsünde seçtiðiniz tanýmlanabilir alan adýna"\
    "deðiþtiriniz.\n"

    "long_aboutString" = ""\
    "'HappyDays' arkadaþlarýnýzýn ve aile fertlerinizin doðum günlerini,"\
    "yýl dönümlerini ve diðer önemli günlerini hatýrlamanýza yardýmcý olur.\n\n"\
    "Happyday'i nasýl kullanabileceðinize dair detaylý bilgi için index.html ve"\
    "manual.html dosyalarýný detaylý inceleyiniz\n\n"\
    "HappyDays'in daðýtýmý GNU General Public License version 2.0"\
    "kurallarý altýnda yapýlmaktadýr.\n"

    "long_cleanupAlertString" = ""\
    "Address Book ve To Do hatýrlatma kayýtlarý, 'note' alanlarýnda"\
    "HappyDays Kayýt No var ise HappyDays'e aittirler. "\ 	
    "Eðer siz de buna benzer þekilde 'note' alanýnda kayýt"\
    "tutuyorsanýz, kayýtlarýnýz 'Temizle' komutu ile silinebilir.\n"

    "long_sl2lnString" = ""\
        "-) lunar takvimde normal ay demektir\n"\
        "#) lunar takvimde artýk (leap) ay demektir"

    "long_cantFindAddrString" = ""\
    "Adres defterinde tanýmlanabilir alan adý bulunamadý: '%s'\n"\
    "Lütfen adres defterinde bir tanýmlanabilir alan adýný deðiþtiriniz."

    "Select Time" = "Zaman Seçiniz"
    "No Time" = "Zamansýz"
    "Invalid input date" = "Geçersiz giriþ tarihi"
    "Export to Memo Pad is completed." = "Memo Pad'e transfer tamamlandý."

    "SUN"   = "PZR"
    "MON"   = "PZT"
    "TUE"   = "SAL"
    "WED"   = "ÇAR"
    "THU"   = "PER"
    "FRI"   = "CUM"
    "SAT"   = "CMT"

    "Not enough memory" = "Yetersiz hafýza"
    "%d notify entry is created.\n" = "%d hatýrlatma kaydý yaratýldý.\n" 
    "%d existing entry " = "%d mevcut kayýt"
    "is kept untouched." = "deðiþtirilmedi."
    "is modified." = "güncellendi."

    "Collecting Information..." = "Bilgi derleniyor..."

    "HappyDays List" = "HappyDays Listesi"
    "Look Up:" = "Bak:"

    "HappyDays View" = "HappyDays Ekraný"
    "Done"  = "Tamamlandý"
    "DB" = "DB" 
    "TD" = "TD"
    "Goto" = "Git"

    "Utilities" = "Araçlar"
    "Date Book Notify" = "Date Book Hatýrlatma"
    "Cleanup Date Book"  = "Date Book'u Temizle"
    "To Do Notify" = "To Do Hatýrlatma"
    "Cleanup To Do"  = "To Do'yu Temizle"
    "Export to Memo Pad" = "Memo Pad'e Transfer"
    "Solar to Lunar" = "Solar'dan Lunar'a"
    "Lunar to Solar" = "Lunar'dan Solar'a"
	"Rescan Address Book" = "Address Book'u Tara"

    "Options" = "Seçenekler"
	"Font..." = "Yazý tipi..."
    "Preferences" = "Ayarlar"
	"Display Preferences" = "Ekran Ayarlarý"
    "About HappyDays" = "HappyDays Hakkýnda"

    "Edit" = "Deðiþtir"
    "Undo" = "Geri Al"
    "Cut" = "Kes"
    "Copy" = "Kopyala" 
    "Paste" = "Yapýþtýr" 
    "Select All" = "Tümünü Seç" 
    "Keyboard" = "Klavye" 
    "Graffiti" = "Graffiti"


/* Font... */

/* preferences screen */
    "Custom field:" = "Tanýmlanabilir alan:"
    "Instead of system date format" = "Sistem tarih biçemi yerine"  
    "Use" = "Kullan"  
    "M/D/Y" = "A/G/Y"  
    "D/M/Y" = "G/A/Y"  
    "D.M.Y" = "G.A.Y"  
    "D-M-Y" = "G-A-Y"  
    "Y/M/D" = "Y/A/G"  
    "Y.M.D" = "Y.A.G"  
    "Y-M-D" = "Y-A-G"  
	"Address Autoscan" = "Adresleri otomatik tara"
	"Always" = "Her zaman"
	"Ask" = "Sor"
	"Never" = "Hiç bir zaman"

    "Notify Format:" = "Hatýrlatma biçemi:"  
    "[Last, First] E(1) Year" = "[Son, Ýlk] E(1) Yýl"  
    "[First Last] E(1) Year" = "[Ýlk Son] E(1) Yýl"  
    "Event - Last, First Year" = "Önemli Gün - Son, Ýlk Yýl"  
    "Event - First Last Year" = "Önemli Gün - Ýlk Son Yýl"  
    "First Last Year" = "Ýlk Son Yýl"  
    
	"Address Book:" = "Adres Defteri:"
	"Built-in" = "Sistemde Gelen"


/* Display preferences */
    "Emphasize Lunar Date" = "Lunar Tarihi Vurgula"


/* About HappyDays */	
	"GPL free software" = "GPL ücretsiz yazýlým"
	"E-Mail & Web Page" = "E-Mail ve Web Sayfasý"



    "OK" = "Tamam"
    "Cancel" = "Vazgeç"

    "Solar to Lunar Convert" = "Solar'dan Lunar'a Çevir"
    "Enter Solar date:" = "Solar (Gregoryen/Miladi takvim) tarihi gir:"
    "Year must be in 1881-2043" = "Yýl 1881-2043 arasýnda olmalýdýr"
    "Result Lunar date:" = "Sonuç Lunar (Ay takvimi) tarihi:"

    "Convert" = "Çevir"

    "Lunar to Solar Convert" = "Lunar'dan Solar'a Çevir"
    "Enter Lunar date:" = "Lunar (Ay takvimi) tarihi gir:"
    "Leap" = "Artýk (Leap)"
    "Result Solar date:" = "Sonuç Solar (Gregoryen/Miladi takvimi) tarihi:"


/* Date Book & To Do Notify */
    "Records:" = "Kayýtlar:"
      "all" = "hepsi"
      "selected" = "seçim" 
    "Existing:" = "Mevcut:"
      "keep" = "tut"
      "modify" = "güncelle"
    "Priority:" = "Öncelik:"
    "Category:" = "Kategori:"
    "Private:" = "Özel:"
    "Alarm:" = "Alarm:"
    "Time:" = "Zaman:"
    "Icon" = "Ýkon"

    "Repeat for:" = "Tekrarla:"
    "years" = "yýl"

    "Notify warning" = "Hatýrlatma uyarýsý" 
	"long_notifywarningString" = ""\
  		"^1: Onayýnýzla"\
		"^2 HappyDays kaydý için hatýrlatma yaratýlacaktýr?" 
      
/* Date Book Icon */
    "Date Book Icon" = "Date Book Ýkonu"  
      "Icon Support" = "Ýkon Desteði"  
      "AN" = "AN"  
      "DateBk3" = "DateBk3"  
      "AN Icon Number:" = "AN Ýkon Numarasý:"  
      "DateBk3 Icon:" = "DateBk3 Ýkonu:"  

/* HappyDays Cleanup */
    "HappyDays Cleanup" = "HappyDays Temizle" 

    "long_removeConfirmString" = ""\
    "Bütün HappyDays hatýrlatma kayýtlarýný temizlemek "\
    "istediðinize emin misiniz?"



    "HappyDays says" = "HappyDays der ki"

    "HappyDays Export" = "HappyDays Transfer"
    "Would you like to export HappyDays List to Memo Pad?" = ""\
    	"HappyDays Listesini Memo Pad'e transfer etmek istediðinize emin misiniz?" 

    "Custom Field Error" = "Tanýmlanabilir Alan Hatasý"
    "Help" = "Yardým" 


    "Invalid event format" = "Geçersiz önemli gün biçemi" 

	"long_invalidformatString" = ""\
    	"\n[^1]\n adres kaydý geçersiz bir önemli gün kaydý içeriyor . "\
		"Nasýl iþlem yapmak istersiniz?" 

    "Ignore" = "Gözardý et" 
    "Ignore all" = "Tümünü gözardý et" 

    "Cleanup Done" = "Temizle Tamamlandý" 

    "^1: ^2 HappyDays notify entries removed." = ""\
    	"^1: ^2 HappyDays hatýrlatma kayýtlarý temizlendi." 

    "HappyDays Export List" = "HappyDays Transfer Listesi" 
    "(not exist in this year)" = "(bu yýlda mevcut deðil)" 
    "Please run Date Book once first." = "Date Book'u önce bir kere çalýþtýrýnýz."  
    
    "Days" = "Günler"  
    "Date Book" = "Date Book"  
    "To Do" = "To Do"  
    "Scan note field" = "Note alanýný tara"  
    "%ld days left" = "%ld gün kaldý"  
    "%ld days passed" = "%ld gün geçti"  

    "Processing" = "Ýþleniyor"  
    "Processed : " = "Ýþlendi : " 

	"Address Change" = "Adres Deðiþikliði"
	"AddressDB is changed. \nDo you want to rescan it?"= ""\
		"Address DB deðiþti. \nTekrar taramak ister misiniz?"

/* HappyDays view */
	"Type:" = "Tip:"
	"Next Date:" = "Bir Sonraki Tarih:"
	"Origin:" = "Orijin:"
	"Age:" = "Yaþ:"
	"UpTo Date:" = "Güncel:"
	"%dY %dM %dD (%ld)" = "%dY %dM %dD (%ld)"

	"Yes" = "Evet"
	"No" = "Hayýr"
END


